VIEW vi_arSvBanSvc
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   ban_rowid                        BAN_ROWID                        1        -        19       "@@"
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   customer_rowid                   CUSTOMER_ROWID                   1        -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   ctn_rowid                        CTN_ROWID                        1        -        19       "@@"
char     deployIndOnChg                   DEPLOYINDONCHG                   1        -        -        "@"
string   rowid                            ROWID                            1        -        19       "@@"
string   bl_req_st_grace_prd              BL_REQ_ST_GRACE_PRD              1        -        9        "@@"
string   bl_req_end_grace_prd             BL_REQ_END_GRACE_PRD             1        -        9        "@@"
long     cs_min_req_ctns                  CS_MIN_REQ_CTNS                  1        -        -        -1061109568
string   cs_com_start_date                CS_COM_START_DATE                1        -        9        "@@"
string   cs_com_end_date                  CS_COM_END_DATE                  1        -        9        "@@"
string   cs_com_reason_code               CS_COM_REASON_CODE               1        -        4        "@@"
short    cs_com_orig_no_month             CS_COM_ORIG_NO_MONTH             1        -        -        -16192
long     rowcount                         ROWCOUNT                         1        -        -        -1061109568
string   pSrvAgrBufrowid                  PSRVAGRBUFROWID                  50       -        19       "@@"
string   soc                              SOC                              50       -        10       "@@"
string   soc_effective_date               SOC_EFFECTIVE_DATE               50       -        9        "@@"
string   commitment_end_date              COMMITMENT_END_DATE              50       -        9        "@@"
char     service_type                     SERVICE_TYPE                     50       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   50       -        9        "@@"
string   expiration_date                  EXPIRATION_DATE                  50       -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   50       -        -        "@"
string   dealer_code                      DEALER_CODE                      50       -        6        "@@"
string   sales_agent                      SALES_AGENT                      50       -        6        "@@"
char     srv_mode                         SRV_MODE                         50       -        -        "@"
char     srv_sub_mode                     SRV_SUB_MODE                     50       -        -        "@"
long     soc_seq_no                       SOC_SEQ_NO                       50       -        -        -1061109568
long     srv_trx_id                       SRV_TRX_ID                       50       -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     50       -        -        -1061109568
string   campaign                         CAMPAIGN                         50       -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             50       -        -        -16192
string   product_type                     PRODUCT_TYPE                     50       -        4        "@@"
long     loan_ver_no                      LOAN_VER_NO                      50       -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      50       -        -        -1061109568
double   soc_actv_fee                     SOC_ACTV_FEE                     50       -        -        -8577.505882352939807
string   promotional_soc                  PROMOTIONAL_SOC                  50       -        10       "@@"
string   reason_code                      REASON_CODE                      50       -        5        "@@"
string   soc_start_rc_date                SOC_START_RC_DATE                50       -        9        "@@"
char     rc_date_copy_ind                 RC_DATE_COPY_IND                 50       -        -        "@"
long     loan_sub_id                      LOAN_SUB_ID                      50       -        -        -1061109568
short    soc_quantity                     SOC_QUANTITY                     50       -        -        -16192
string   bill_text                        BILL_TEXT                        50       -        41       "@@"
double   full_amt                         FULL_AMT                         50       -        -        -8577.505882352939807
double   first_install_rate               FIRST_INSTALL_RATE               50       -        -        -8577.505882352939807
double   other_install_rate               OTHER_INSTALL_RATE               50       -        -        -8577.505882352939807
double   last_install_rate                LAST_INSTALL_RATE                50       -        -        -8577.505882352939807
short    no_of_installments               NO_OF_INSTALLMENTS               50       -        -        -16192
long     pSrvFtrBufrowcount               PSRVFTRBUFROWCOUNT               1        -        -        -1061109568
string   pSrvFtrBufrowid                  PSRVFTRBUFROWID                  500      -        19       "@@"
string   pSrvFtrBufsoc                    PSRVFTRBUFSOC                    500      -        10       "@@"
string   pSrvFtrBufsoc_effective_date     PSRVFTRBUFSOC_EFFECTIVE_DATE     500      -        9        "@@"
string   feature_code                     FEATURE_CODE                     500      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     500      -        7        "@@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               500      -        9        "@@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              500      -        9        "@@"
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 500      -        -        "@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 500      -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               500      -        -        -1061109568
char     ftr_mode                         FTR_MODE                         500      -        -        "@"
long     pSrvFtrBufsoc_seq_no             PSRVFTRBUFSOC_SEQ_NO             500      -        -        -1061109568
char     ftr_sub_mode                     FTR_SUB_MODE                     500      -        -        "@"
string   ftr_add_param                    FTR_ADD_PARAM                    500      -        301      "@@"
string   feature_type                     FEATURE_TYPE                     500      -        4        "@@"
string   pSrvFtrBufproduct_type           PSRVFTRBUFPRODUCT_TYPE           500      -        4        "@@"
long     pSrvFtrBufcampaign_seq           PSRVFTRBUFCAMPAIGN_SEQ           500      -        -        -1061109568
string   ftr_special_telno                FTR_SPECIAL_TELNO                500      -        21       "@@"
char     switch_act_needed                SWITCH_ACT_NEEDED                500      -        -        "@"
string   switch_code                      SWITCH_CODE                      500      -        7        "@@"
char     msisdn_criteria                  MSISDN_CRITERIA                  500      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      500      -        4        "@@"
char     action_mode                      ACTION_MODE                      500      -        -        "@"
double   manual_rc_rate                   MANUAL_RC_RATE                   500      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               500      -        9        "@@"
string   manual_rc_eff_date               MANUAL_RC_EFF_DATE               500      -        9        "@@"
long     row_count                        ROW_COUNT                        1        -        -        -1061109568
string   act_code                         ACT_CODE                         50       -        4        "@@"
string   act_reason                       ACT_REASON                       50       -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                50       -        -        "@"
string   memo_ctn                         MEMO_CTN                         50       -        21       "@@"
string   user_text                        USER_TEXT                        50       -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      50       -        -        "@"
long     param_count                      PARAM_COUNT                      50       -        -        -1061109568
string   p1                               P1                               50       -        51       "@@"
string   p2                               P2                               50       -        51       "@@"
string   p3                               P3                               50       -        51       "@@"
string   p4                               P4                               50       -        51       "@@"
string   p5                               P5                               50       -        51       "@@"
string   p6                               P6                               50       -        51       "@@"
string   p7                               P7                               50       -        51       "@@"
string   p8                               P8                               50       -        51       "@@"
string   p9                               P9                               50       -        51       "@@"
string   p10                              P10                              50       -        51       "@@"
double   memo_amt                         MEMO_AMT                         50       -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     50       -        5        "@@"
double   charge_amt                       CHARGE_AMT                       50       -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   50       -        -        "@"
string   waive_reason                     WAIVE_REASON                     50       -        7        "@@"
char     waive_ind                        WAIVE_IND                        50       -        -        "@"
long     pcsFrndFmlrowCount               PCSFRNDFMLROWCOUNT               1        -        -        -1061109568
char     actionInd                        ACTIONIND                        10000    -        -        "@"
string   pcsFandFRecrowid                 PCSFANDFRECROWID                 10000    -        19       "@@"
string   pcsFandFReceffective_date        PCSFANDFRECEFFECTIVE_DATE        10000    -        15       "@@"
string   pcsFandFRecexpiration_date       PCSFANDFRECEXPIRATION_DATE       10000    -        15       "@@"
string   personal_tel                     PERSONAL_TEL                     10000    -        21       "@@"
string   personal_tel_to                  PERSONAL_TEL_TO                  10000    -        21       "@@"
string   ff_soc                           FF_SOC                           10000    -        10       "@@"
string   plan_code                        PLAN_CODE                        10000    -        10       "@@"
char     discount_type                    DISCOUNT_TYPE                    10000    -        -        "@"
string   start_hour                       START_HOUR                       10000    -        7        "@@"
double   duration                         DURATION                         10000    -        -        -8577.505882352939807
END

VIEW vo_arSvBanSvc
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     rowcount                         ROWCOUNT                         1        -        -        -1061109568
string   pSrvAgrBufrowid                  PSRVAGRBUFROWID                  50       -        19       "@@"
string   soc                              SOC                              50       -        10       "@@"
string   soc_effective_date               SOC_EFFECTIVE_DATE               50       -        9        "@@"
string   commitment_end_date              COMMITMENT_END_DATE              50       -        9        "@@"
char     service_type                     SERVICE_TYPE                     50       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   50       -        9        "@@"
string   expiration_date                  EXPIRATION_DATE                  50       -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   50       -        -        "@"
string   dealer_code                      DEALER_CODE                      50       -        6        "@@"
string   sales_agent                      SALES_AGENT                      50       -        6        "@@"
char     srv_mode                         SRV_MODE                         50       -        -        "@"
char     srv_sub_mode                     SRV_SUB_MODE                     50       -        -        "@"
long     soc_seq_no                       SOC_SEQ_NO                       50       -        -        -1061109568
long     srv_trx_id                       SRV_TRX_ID                       50       -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     50       -        -        -1061109568
string   campaign                         CAMPAIGN                         50       -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             50       -        -        -16192
string   product_type                     PRODUCT_TYPE                     50       -        4        "@@"
long     loan_ver_no                      LOAN_VER_NO                      50       -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      50       -        -        -1061109568
double   soc_actv_fee                     SOC_ACTV_FEE                     50       -        -        -8577.505882352939807
string   promotional_soc                  PROMOTIONAL_SOC                  50       -        10       "@@"
string   reason_code                      REASON_CODE                      50       -        5        "@@"
string   soc_start_rc_date                SOC_START_RC_DATE                50       -        9        "@@"
char     rc_date_copy_ind                 RC_DATE_COPY_IND                 50       -        -        "@"
long     loan_sub_id                      LOAN_SUB_ID                      50       -        -        -1061109568
short    soc_quantity                     SOC_QUANTITY                     50       -        -        -16192
string   bill_text                        BILL_TEXT                        50       -        41       "@@"
double   full_amt                         FULL_AMT                         50       -        -        -8577.505882352939807
double   first_install_rate               FIRST_INSTALL_RATE               50       -        -        -8577.505882352939807
double   other_install_rate               OTHER_INSTALL_RATE               50       -        -        -8577.505882352939807
double   last_install_rate                LAST_INSTALL_RATE                50       -        -        -8577.505882352939807
short    no_of_installments               NO_OF_INSTALLMENTS               50       -        -        -16192
long     pSrvFtrBufrowcount               PSRVFTRBUFROWCOUNT               1        -        -        -1061109568
string   pSrvFtrBufrowid                  PSRVFTRBUFROWID                  500      -        19       "@@"
string   pSrvFtrBufsoc                    PSRVFTRBUFSOC                    500      -        10       "@@"
string   pSrvFtrBufsoc_effective_date     PSRVFTRBUFSOC_EFFECTIVE_DATE     500      -        9        "@@"
string   feature_code                     FEATURE_CODE                     500      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     500      -        7        "@@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               500      -        9        "@@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              500      -        9        "@@"
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 500      -        -        "@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 500      -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               500      -        -        -1061109568
char     ftr_mode                         FTR_MODE                         500      -        -        "@"
long     pSrvFtrBufsoc_seq_no             PSRVFTRBUFSOC_SEQ_NO             500      -        -        -1061109568
char     ftr_sub_mode                     FTR_SUB_MODE                     500      -        -        "@"
string   ftr_add_param                    FTR_ADD_PARAM                    500      -        301      "@@"
string   feature_type                     FEATURE_TYPE                     500      -        4        "@@"
string   pSrvFtrBufproduct_type           PSRVFTRBUFPRODUCT_TYPE           500      -        4        "@@"
long     pSrvFtrBufcampaign_seq           PSRVFTRBUFCAMPAIGN_SEQ           500      -        -        -1061109568
string   ftr_special_telno                FTR_SPECIAL_TELNO                500      -        21       "@@"
char     switch_act_needed                SWITCH_ACT_NEEDED                500      -        -        "@"
string   switch_code                      SWITCH_CODE                      500      -        7        "@@"
char     msisdn_criteria                  MSISDN_CRITERIA                  500      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      500      -        4        "@@"
char     action_mode                      ACTION_MODE                      500      -        -        "@"
double   manual_rc_rate                   MANUAL_RC_RATE                   500      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               500      -        9        "@@"
string   manual_rc_eff_date               MANUAL_RC_EFF_DATE               500      -        9        "@@"
END


VIEW vi_arLsBanAgr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   date                             DATE                             1        -        9        "@@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
END

VIEW vo_arLsBanAgr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            600      -        19       "@@"
long     ban                              BAN                              600      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    600      -        21       "@@"
string   soc                              SOC                              600      -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       600      -        -        -1061109568
long     soc_ver_no                       SOC_VER_NO                       600      -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     600      -        -        -1061109568
string   campaign                         CAMPAIGN                         600      -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             600      -        -        -16192
string   soc_effective_date               SOC_EFFECTIVE_DATE               600      -        9        "@@"
long     customer_id                      CUSTOMER_ID                      600      -        -        -1061109568
string   effective_date                   EFFECTIVE_DATE                   600      -        9        "@@"
char     service_type                     SERVICE_TYPE                     600      -        -        "@"
string   expiration_date                  EXPIRATION_DATE                  600      -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   600      -        -        "@"
string   dealer_code                      DEALER_CODE                      600      -        6        "@@"
string   sales_agent                      SALES_AGENT                      600      -        6        "@@"
string   effective_issue_date             EFFECTIVE_ISSUE_DATE             600      -        9        "@@"
string   expiration_issue_date            EXPIRATION_ISSUE_DATE            600      -        9        "@@"
long     trx_id                           TRX_ID                           600      -        -        -1061109568
long     ins_trx_id                       INS_TRX_ID                       600      -        -        -1061109568
short    conv_run_no                      CONV_RUN_NO                      600      -        -        -16192
long     loan_ver_no                      LOAN_VER_NO                      600      -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      600      -        -        -1061109568
string   soc_start_rc_date                SOC_START_RC_DATE                600      -        9        "@@"
short    soc_quantity                     SOC_QUANTITY                     600      -        -        -16192
string   bill_text                        BILL_TEXT                        600      -        41       "@@"
string   soc_rowid                        SOC_ROWID                        600      -        19       "@@"
string   sale_eff_date                    SALE_EFF_DATE                    600      -        9        "@@"
string   sale_exp_date                    SALE_EXP_DATE                    600      -        9        "@@"
short    minimum_no_months                MINIMUM_NO_MONTHS                600      -        -        -16192
string   soc_description                  SOC_DESCRIPTION                  600      -        31       "@@"
string   soc_group                        SOC_GROUP                        600      -        7        "@@"
short    max_quantity                     MAX_QUANTITY                     600      -        -        -16192
char     allow_free_bill_txt              ALLOW_FREE_BILL_TXT              600      -        -        "@"
char     flexible_loan_ind                FLEXIBLE_LOAN_IND                600      -        -        "@"
string   external_party                   EXTERNAL_PARTY                   600      -        3        "@@"
string   prmt_rowid                       PRMT_ROWID                       600      -        19       "@@"
short    pt_duration                      PT_DURATION                      600      -        -        -16192
char     duration_ind                     DURATION_IND                     600      -        -        "@"
char     pp_ind                           PP_IND                           600      -        -        "@"
char     auto_renewal_ind                 AUTO_RENEWAL_IND                 600      -        -        "@"
string   cut_date                         CUT_DATE                         600      -        9        "@@"
string   trs_rowid                        TRS_ROWID                        600      -        19       "@@"
string   trs_expiration_date              TRS_EXPIRATION_DATE              600      -        9        "@@"
string   trs_soc                          TRS_SOC                          600      -        10       "@@"
char     call_type_code                   CALL_TYPE_CODE                   600      -        -        "@"
string   toll_rs_desc                     TOLL_RS_DESC                     600      -        31       "@@"
string   subln_rowid                      SUBLN_ROWID                      600      -        19       "@@"
double   full_amt                         FULL_AMT                         600      -        -        -8577.505882352939807
double   first_install_rate               FIRST_INSTALL_RATE               600      -        -        -8577.505882352939807
double   other_install_rate               OTHER_INSTALL_RATE               600      -        -        -8577.505882352939807
double   last_install_rate                LAST_INSTALL_RATE                600      -        -        -8577.505882352939807
short    no_of_installments               NO_OF_INSTALLMENTS               600      -        -        -16192
long     subscriber_id                    SUBSCRIBER_ID                    600      -        -        -1061109568
long     dci_error_code                   DCI_ERROR_CODE                   1        -        -        -1061109568
short    dci_error_type                   DCI_ERROR_TYPE                   1        -        -        -16192
string   dci_error_text                   DCI_ERROR_TEXT                   1        -        81       "@@"
long     dci_row_count                    DCI_ROW_COUNT                    1        -        -        -1061109568
short    dci_more_rows                    DCI_MORE_ROWS                    1        -        -        -16192
END


VIEW vi_arLsBanFtr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   date                             DATE                             1        -        9        "@@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
END

VIEW vo_arLsBanFtr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            400      -        19       "@@"
long     ban                              BAN                              400      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    400      -        21       "@@"
string   soc                              SOC                              400      -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       400      -        -        -1061109568
long     ftr_soc_ver_no                   FTR_SOC_VER_NO                   400      -        -        -1061109568
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               400      -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     400      -        -        -1061109568
string   campaign                         CAMPAIGN                         400      -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             400      -        -        -16192
string   soc_effective_date               SOC_EFFECTIVE_DATE               400      -        9        "@@"
long     customer_id                      CUSTOMER_ID                      400      -        -        -1061109568
string   feature_code                     FEATURE_CODE                     400      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     400      -        7        "@@"
char     service_type                     SERVICE_TYPE                     400      -        -        "@"
char     soc_level_code                   SOC_LEVEL_CODE                   400      -        -        "@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               400      -        9        "@@"
short    service_ftr_qty                  SERVICE_FTR_QTY                  400      -        -        -16192
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 400      -        -        "@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              400      -        9        "@@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 400      -        -        "@"
string   ftr_special_telno                FTR_SPECIAL_TELNO                400      -        21       "@@"
string   ftr_special_tn_date              FTR_SPECIAL_TN_DATE              400      -        9        "@@"
string   rc_waiver_eff_date               RC_WAIVER_EFF_DATE               400      -        9        "@@"
string   rc_waiver_expr_date              RC_WAIVER_EXPR_DATE              400      -        9        "@@"
string   rc_waiver_rsn                    RC_WAIVER_RSN                    400      -        7        "@@"
long     rc_waiver_opid                   RC_WAIVER_OPID                   400      -        -        -1061109568
string   ftr_eff_issue_date               FTR_EFF_ISSUE_DATE               400      -        9        "@@"
string   ftr_exp_issue_date               FTR_EXP_ISSUE_DATE               400      -        9        "@@"
short    conv_run_no                      CONV_RUN_NO                      400      -        -        -16192
long     loan_ver_no                      LOAN_VER_NO                      400      -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      400      -        -        -1061109568
double   manual_rc_rate                   MANUAL_RC_RATE                   400      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               400      -        9        "@@"
string   manual_rc_eff_date               MANUAL_RC_EFF_DATE               400      -        9        "@@"
string   ftr_add_sw_prm_trunc             FTR_ADD_SW_PRM_TRUNC             400      -        301      "@@"
long     ftr_add_sw_prm_len               FTR_ADD_SW_PRM_LEN               400      -        -        -1061109568
string   feature_desc                     FEATURE_DESC                     400      -        101      "@@"
string   feature_type                     FEATURE_TYPE                     400      -        4        "@@"
char     rc_info_ind                      RC_INFO_IND                      400      -        -        "@"
char     msisdn_criteria                  MSISDN_CRITERIA                  400      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      400      -        4        "@@"
string   switch_code                      SWITCH_CODE                      400      -        7        "@@"
long     dci_error_code                   DCI_ERROR_CODE                   1        -        -        -1061109568
short    dci_error_type                   DCI_ERROR_TYPE                   1        -        -        -16192
string   dci_error_text                   DCI_ERROR_TEXT                   1        -        81       "@@"
long     dci_row_count                    DCI_ROW_COUNT                    1        -        -        -1061109568
short    dci_more_rows                    DCI_MORE_ROWS                    1        -        -        -16192
END


VIEW vi_arLsDefAgr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   date                             DATE                             1        -        9        "@@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
END

VIEW vo_arLsDefAgr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            600      -        19       "@@"
long     ban                              BAN                              600      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    600      -        21       "@@"
string   soc                              SOC                              600      -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       600      -        -        -1061109568
long     soc_ver_no                       SOC_VER_NO                       600      -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     600      -        -        -1061109568
string   campaign                         CAMPAIGN                         600      -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             600      -        -        -16192
string   soc_effective_date               SOC_EFFECTIVE_DATE               600      -        9        "@@"
long     customer_id                      CUSTOMER_ID                      600      -        -        -1061109568
string   effective_date                   EFFECTIVE_DATE                   600      -        9        "@@"
char     service_type                     SERVICE_TYPE                     600      -        -        "@"
string   expiration_date                  EXPIRATION_DATE                  600      -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   600      -        -        "@"
string   dealer_code                      DEALER_CODE                      600      -        6        "@@"
string   sales_agent                      SALES_AGENT                      600      -        6        "@@"
string   effective_issue_date             EFFECTIVE_ISSUE_DATE             600      -        9        "@@"
string   expiration_issue_date            EXPIRATION_ISSUE_DATE            600      -        9        "@@"
long     trx_id                           TRX_ID                           600      -        -        -1061109568
long     ins_trx_id                       INS_TRX_ID                       600      -        -        -1061109568
short    conv_run_no                      CONV_RUN_NO                      600      -        -        -16192
long     loan_ver_no                      LOAN_VER_NO                      600      -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      600      -        -        -1061109568
string   soc_start_rc_date                SOC_START_RC_DATE                600      -        9        "@@"
short    soc_quantity                     SOC_QUANTITY                     600      -        -        -16192
string   bill_text                        BILL_TEXT                        600      -        41       "@@"
string   soc_rowid                        SOC_ROWID                        600      -        19       "@@"
string   sale_eff_date                    SALE_EFF_DATE                    600      -        9        "@@"
string   sale_exp_date                    SALE_EXP_DATE                    600      -        9        "@@"
short    minimum_no_months                MINIMUM_NO_MONTHS                600      -        -        -16192
string   soc_description                  SOC_DESCRIPTION                  600      -        31       "@@"
short    max_quantity                     MAX_QUANTITY                     600      -        -        -16192
char     allow_free_bill_txt              ALLOW_FREE_BILL_TXT              600      -        -        "@"
char     flexible_loan_ind                FLEXIBLE_LOAN_IND                600      -        -        "@"
string   external_party                   EXTERNAL_PARTY                   600      -        3        "@@"
string   prmt_rowid                       PRMT_ROWID                       600      -        19       "@@"
short    pt_duration                      PT_DURATION                      600      -        -        -16192
char     duration_ind                     DURATION_IND                     600      -        -        "@"
char     pp_ind                           PP_IND                           600      -        -        "@"
char     auto_renewal_ind                 AUTO_RENEWAL_IND                 600      -        -        "@"
string   cut_date                         CUT_DATE                         600      -        9        "@@"
string   trs_rowid                        TRS_ROWID                        600      -        19       "@@"
string   trs_expiration_date              TRS_EXPIRATION_DATE              600      -        9        "@@"
string   trs_soc                          TRS_SOC                          600      -        10       "@@"
char     call_type_code                   CALL_TYPE_CODE                   600      -        -        "@"
string   toll_rs_desc                     TOLL_RS_DESC                     600      -        31       "@@"
string   subln_rowid                      SUBLN_ROWID                      600      -        19       "@@"
double   full_amt                         FULL_AMT                         600      -        -        -8577.505882352939807
double   first_install_rate               FIRST_INSTALL_RATE               600      -        -        -8577.505882352939807
double   other_install_rate               OTHER_INSTALL_RATE               600      -        -        -8577.505882352939807
double   last_install_rate                LAST_INSTALL_RATE                600      -        -        -8577.505882352939807
short    no_of_installments               NO_OF_INSTALLMENTS               600      -        -        -16192
long     subscriber_id                    SUBSCRIBER_ID                    600      -        -        -1061109568
long     dci_error_code                   DCI_ERROR_CODE                   1        -        -        -1061109568
short    dci_error_type                   DCI_ERROR_TYPE                   1        -        -        -16192
string   dci_error_text                   DCI_ERROR_TEXT                   1        -        81       "@@"
long     dci_row_count                    DCI_ROW_COUNT                    1        -        -        -1061109568
short    dci_more_rows                    DCI_MORE_ROWS                    1        -        -        -16192
END


VIEW vi_arLsDefFtr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   date                             DATE                             1        -        9        "@@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
END

VIEW vo_arLsDefFtr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            400      -        19       "@@"
long     ban                              BAN                              400      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    400      -        21       "@@"
string   soc                              SOC                              400      -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       400      -        -        -1061109568
long     ftr_soc_ver_no                   FTR_SOC_VER_NO                   400      -        -        -1061109568
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               400      -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     400      -        -        -1061109568
string   campaign                         CAMPAIGN                         400      -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             400      -        -        -16192
string   soc_effective_date               SOC_EFFECTIVE_DATE               400      -        9        "@@"
long     customer_id                      CUSTOMER_ID                      400      -        -        -1061109568
string   feature_code                     FEATURE_CODE                     400      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     400      -        7        "@@"
char     service_type                     SERVICE_TYPE                     400      -        -        "@"
char     soc_level_code                   SOC_LEVEL_CODE                   400      -        -        "@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               400      -        9        "@@"
short    service_ftr_qty                  SERVICE_FTR_QTY                  400      -        -        -16192
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 400      -        -        "@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              400      -        9        "@@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 400      -        -        "@"
string   ftr_special_telno                FTR_SPECIAL_TELNO                400      -        21       "@@"
string   ftr_special_tn_date              FTR_SPECIAL_TN_DATE              400      -        9        "@@"
string   rc_waiver_eff_date               RC_WAIVER_EFF_DATE               400      -        9        "@@"
string   rc_waiver_expr_date              RC_WAIVER_EXPR_DATE              400      -        9        "@@"
string   rc_waiver_rsn                    RC_WAIVER_RSN                    400      -        7        "@@"
long     rc_waiver_opid                   RC_WAIVER_OPID                   400      -        -        -1061109568
string   ftr_eff_issue_date               FTR_EFF_ISSUE_DATE               400      -        9        "@@"
string   ftr_exp_issue_date               FTR_EXP_ISSUE_DATE               400      -        9        "@@"
short    conv_run_no                      CONV_RUN_NO                      400      -        -        -16192
long     loan_ver_no                      LOAN_VER_NO                      400      -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      400      -        -        -1061109568
double   manual_rc_rate                   MANUAL_RC_RATE                   400      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               400      -        9        "@@"
string   manual_rc_eff_date               MANUAL_RC_EFF_DATE               400      -        9        "@@"
string   ftr_add_sw_prm_trunc             FTR_ADD_SW_PRM_TRUNC             400      -        301      "@@"
long     ftr_add_sw_prm_len               FTR_ADD_SW_PRM_LEN               400      -        -        -1061109568
string   feature_desc                     FEATURE_DESC                     400      -        101      "@@"
string   feature_type                     FEATURE_TYPE                     400      -        4        "@@"
char     rc_info_ind                      RC_INFO_IND                      400      -        -        "@"
char     msisdn_criteria                  MSISDN_CRITERIA                  400      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      400      -        4        "@@"
string   switch_code                      SWITCH_CODE                      400      -        7        "@@"
long     dci_error_code                   DCI_ERROR_CODE                   1        -        -        -1061109568
short    dci_error_type                   DCI_ERROR_TYPE                   1        -        -        -16192
string   dci_error_text                   DCI_ERROR_TEXT                   1        -        81       "@@"
long     dci_row_count                    DCI_ROW_COUNT                    1        -        -        -1061109568
short    dci_more_rows                    DCI_MORE_ROWS                    1        -        -        -16192
END


VIEW vi_arGtFutPP
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   soc                              SOC                              1        -        10       "@@"
END

VIEW vo_arGtFutPP
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
long     total_count                      TOTAL_COUNT                      1        -        -        -1061109568
string   rowid                            ROWID                            600      -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    600      -        21       "@@"
string   soc                              SOC                              600      -        10       "@@"
string   effective_date                   EFFECTIVE_DATE                   600      -        9        "@@"
END


VIEW vi_arRmBanSrv
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   ban_rowid                        BAN_ROWID                        1        -        19       "@@"
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   customer_rowid                   CUSTOMER_ROWID                   1        -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   ctn_rowid                        CTN_ROWID                        1        -        19       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   product_type                     PRODUCT_TYPE                     10       -        4        "@@"
long     pSocBufrowcount                  PSOCBUFROWCOUNT                  1        -        -        -1061109568
string   rowid                            ROWID                            50       -        19       "@@"
string   soc                              SOC                              50       -        10       "@@"
string   soc_effective_date               SOC_EFFECTIVE_DATE               50       -        9        "@@"
string   commitment_end_date              COMMITMENT_END_DATE              50       -        9        "@@"
char     service_type                     SERVICE_TYPE                     50       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   50       -        9        "@@"
string   expiration_date                  EXPIRATION_DATE                  50       -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   50       -        -        "@"
string   dealer_code                      DEALER_CODE                      50       -        6        "@@"
string   sales_agent                      SALES_AGENT                      50       -        6        "@@"
char     srv_mode                         SRV_MODE                         50       -        -        "@"
char     srv_sub_mode                     SRV_SUB_MODE                     50       -        -        "@"
long     soc_seq_no                       SOC_SEQ_NO                       50       -        -        -1061109568
long     srv_trx_id                       SRV_TRX_ID                       50       -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     50       -        -        -1061109568
string   campaign                         CAMPAIGN                         50       -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             50       -        -        -16192
string   pSocBufproduct_type              PSOCBUFPRODUCT_TYPE              50       -        4        "@@"
long     loan_ver_no                      LOAN_VER_NO                      50       -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      50       -        -        -1061109568
double   soc_actv_fee                     SOC_ACTV_FEE                     50       -        -        -8577.505882352939807
string   promotional_soc                  PROMOTIONAL_SOC                  50       -        10       "@@"
string   reason_code                      REASON_CODE                      50       -        5        "@@"
string   soc_start_rc_date                SOC_START_RC_DATE                50       -        9        "@@"
char     rc_date_copy_ind                 RC_DATE_COPY_IND                 50       -        -        "@"
long     loan_sub_id                      LOAN_SUB_ID                      50       -        -        -1061109568
short    soc_quantity                     SOC_QUANTITY                     50       -        -        -16192
string   bill_text                        BILL_TEXT                        50       -        41       "@@"
double   full_amt                         FULL_AMT                         50       -        -        -8577.505882352939807
double   first_install_rate               FIRST_INSTALL_RATE               50       -        -        -8577.505882352939807
double   other_install_rate               OTHER_INSTALL_RATE               50       -        -        -8577.505882352939807
double   last_install_rate                LAST_INSTALL_RATE                50       -        -        -8577.505882352939807
short    no_of_installments               NO_OF_INSTALLMENTS               50       -        -        -16192
long     pSrvFtrBufrowcount               PSRVFTRBUFROWCOUNT               1        -        -        -1061109568
string   pSrvFtrBufrowid                  PSRVFTRBUFROWID                  500      -        19       "@@"
string   pSrvFtrBufsoc                    PSRVFTRBUFSOC                    500      -        10       "@@"
string   pSrvFtrBufsoc_effective_date     PSRVFTRBUFSOC_EFFECTIVE_DATE     500      -        9        "@@"
string   feature_code                     FEATURE_CODE                     500      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     500      -        7        "@@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               500      -        9        "@@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              500      -        9        "@@"
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 500      -        -        "@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 500      -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               500      -        -        -1061109568
char     ftr_mode                         FTR_MODE                         500      -        -        "@"
long     pSrvFtrBufsoc_seq_no             PSRVFTRBUFSOC_SEQ_NO             500      -        -        -1061109568
char     ftr_sub_mode                     FTR_SUB_MODE                     500      -        -        "@"
string   ftr_add_param                    FTR_ADD_PARAM                    500      -        301      "@@"
string   feature_type                     FEATURE_TYPE                     500      -        4        "@@"
string   pSrvFtrBufproduct_type           PSRVFTRBUFPRODUCT_TYPE           500      -        4        "@@"
long     pSrvFtrBufcampaign_seq           PSRVFTRBUFCAMPAIGN_SEQ           500      -        -        -1061109568
string   ftr_special_telno                FTR_SPECIAL_TELNO                500      -        21       "@@"
char     switch_act_needed                SWITCH_ACT_NEEDED                500      -        -        "@"
string   switch_code                      SWITCH_CODE                      500      -        7        "@@"
char     msisdn_criteria                  MSISDN_CRITERIA                  500      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      500      -        4        "@@"
char     action_mode                      ACTION_MODE                      500      -        -        "@"
double   manual_rc_rate                   MANUAL_RC_RATE                   500      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               500      -        9        "@@"
string   manual_rc_eff_date               MANUAL_RC_EFF_DATE               500      -        9        "@@"
END

VIEW vo_arRmBanSrv
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_arChkFnfSoc
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   rc_fnf_soc                       RC_FNF_SOC                       1        -        10       "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        9        "@@"
string   expiration_date                  EXPIRATION_DATE                  1        -        9        "@@"
long     ctn_number                       CTN_NUMBER                       1        -        -        -1061109568
END

VIEW vo_arChkFnfSoc
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
string   fnf_soc_sts                      FNF_SOC_STS                      1        -        3        "@@"
long     root_ban                         ROOT_BAN                         1        -        -        -1061109568
string   ban_fnf_plan_code                BAN_FNF_PLAN_CODE                1        -        10       "@@"
string   root_ban_fnf_plan_code           ROOT_BAN_FNF_PLAN_CODE           1        -        10       "@@"
char     ban_fnf_plan_code_disc_tp        BAN_FNF_PLAN_CODE_DISC_TP        1        -        -        "@"
char     root_ban_fnf_plan_code_disc_tp   ROOT_BAN_FNF_PLAN_CODE_DISC_TP   1        -        -        "@"
END


VIEW vi_arMoveBanLn
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     sourceBan                        SOURCEBAN                        1        -        -        -1061109568
long     targetBan                        TARGETBAN                        1        -        -        -1061109568
string   loanSocCode                      LOANSOCCODE                      1        -        10       "@@"
long     loanSeqNo                        LOANSEQNO                        1        -        -        -1061109568
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        51       "@@"
string   p2                               P2                               1        -        51       "@@"
string   p3                               P3                               1        -        51       "@@"
string   p4                               P4                               1        -        51       "@@"
string   p5                               P5                               1        -        51       "@@"
string   p6                               P6                               1        -        51       "@@"
string   p7                               P7                               1        -        51       "@@"
string   p8                               P8                               1        -        51       "@@"
string   p9                               P9                               1        -        51       "@@"
string   p10                              P10                              1        -        51       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
string   source_ban_last_update_date      SOURCE_BAN_LAST_UPDATE_DATE      1        -        15       "@@"
short    source_ban_last_update_stamp     SOURCE_BAN_LAST_UPDATE_STAMP     1        -        -        -16192
END

VIEW vo_arMoveBanLn
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


