VIEW vi_gnLsLnkBans
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   effectiveDate                    EFFECTIVEDATE                    1        -        9        "@@"
long     bufferSize                       BUFFERSIZE                       1        -        -        -1061109568
END

VIEW vo_gnLsLnkBans
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     bansCount                        BANSCOUNT                        1        -        -        -1061109568
string   rowid                            ROWID                            1000     -        19       "@@"
long     ban                              BAN                              1000     -        -        -1061109568
char     account_type                     ACCOUNT_TYPE                     1000     -        -        "@"
string   account_sub_type                 ACCOUNT_SUB_TYPE                 1000     -        3        "@@"
char     ban_status                       BAN_STATUS                       1000     -        -        "@"
string   description                      DESCRIPTION                      1000     -        41       "@@"
long     link_seq_no                      LINK_SEQ_NO                      1000     -        -        -1061109568
END


VIEW vi_gnLsLnkSubs
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriberNo                     SUBSCRIBERNO                     1        -        21       "@@"
string   effectiveDate                    EFFECTIVEDATE                    1        -        9        "@@"
long     bufferSize                       BUFFERSIZE                       1        -        -        -1061109568
END

VIEW vo_gnLsLnkSubs
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     subsCount                        SUBSCOUNT                        1        -        -        -1061109568
string   rowid                            ROWID                            1000     -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1000     -        21       "@@"
long     customer_ban                     CUSTOMER_BAN                     1000     -        -        -1061109568
char     sub_status                       SUB_STATUS                       1000     -        -        "@"
long     link_seq_no                      LINK_SEQ_NO                      1000     -        -        -1061109568
END


VIEW vi_gnGtAdNmLnk
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   link_row_id                      LINK_ROW_ID                      1        -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      1        -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   link_type_str                    LINK_TYPE_STR                    1        -        21       "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   1        -        -        -1061109568
END

VIEW vo_gnGtAdNmLnk
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
char     link_mode                        LINK_MODE                        20       -        -        "@"
long     link_ban                         LINK_BAN                         20       -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  20       -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      20       -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      20       -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      20       -        -        -1061109568
long     ban                              BAN                              20       -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    20       -        21       "@@"
char     link_type                        LINK_TYPE                        20       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   20       -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   20       -        -        -1061109568
char     billing_ind                      BILLING_IND                      20       -        -        "@"
char     mailing_ind                      MAILING_IND                      20       -        -        "@"
char     user_ind                         USER_IND                         20       -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 20       -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 20       -        -        "@"
char     link_user_ind                    LINK_USER_IND                    20       -        -        "@"
char     nm_mode                          NM_MODE                          20       -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       20       -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   20       -        9        "@@"
string   rowid                            ROWID                            20       -        19       "@@"
long     name_id                          NAME_ID                          20       -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                20       -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  20       -        15       "@@"
long     operator_id                      OPERATOR_ID                      20       -        -        -1061109568
string   application_id                   APPLICATION_ID                   20       -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  20       -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  20       -        -        -16192
string   control_name                     CONTROL_NAME                     20       -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               20       -        61       "@@"
string   first_name                       FIRST_NAME                       20       -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 20       -        61       "@@"
char     name_format                      NAME_FORMAT                      20       -        -        "@"
string   birth_date                       BIRTH_DATE                       20       -        9        "@@"
string   identify                         IDENTIFY                         20       -        21       "@@"
string   id_type                          ID_TYPE                          20       -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      20       -        51       "@@"
double   kob                              KOB                              20       -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   20       -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    20       -        11       "@@"
short    conv_run_no                      CONV_RUN_NO                      20       -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            20       -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   20       -        4        "@@"
char     gender                           GENDER                           20       -        -        "@"
string   marital_status                   MARITAL_STATUS                   20       -        5        "@@"
char     role_ind                         ROLE_IND                         20       -        -        "@"
char     adr_mode                         ADR_MODE                         20       -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      20       -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  20       -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  20       -        19       "@@"
long     address_id                       ADDRESS_ID                       20       -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      20       -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        20       -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            20       -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         20       -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        20       -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        20       -        -        -16192
char     adr_type                         ADR_TYPE                         20       -        -        "@"
char     adr_status                       ADR_STATUS                       20       -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  20       -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 20       -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   20       -        101      "@@"
string   adr_city                         ADR_CITY                         20       -        40       "@@"
string   adr_zip                          ADR_ZIP                          20       -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     20       -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  20       -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    20       -        3        "@@"
string   adr_pob                          ADR_POB                          20       -        11       "@@"
string   adr_country                      ADR_COUNTRY                      20       -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 20       -        3        "@@"
string   adr_story                        ADR_STORY                        20       -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      20       -        5        "@@"
string   adr_email                        ADR_EMAIL                        20       -        151      "@@"
string   since_date                       SINCE_DATE                       20       -        9        "@@"
string   adr_district                     ADR_DISTRICT                     20       -        41       "@@"
char     co_ind                           CO_IND                           20       -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            20       -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               20       -        5        "@@"
string   county_code                      COUNTY_CODE                      20       -        3        "@@"
string   community_name                   COMMUNITY_NAME                   20       -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      20       -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   20       -        61       "@@"
string   adr_p1                           ADR_P1                           20       -        61       "@@"
string   adr_p2                           ADR_P2                           20       -        61       "@@"
string   adr_p3                           ADR_P3                           20       -        61       "@@"
string   adr_p4                           ADR_P4                           20       -        61       "@@"
string   adr_p5                           ADR_P5                           20       -        61       "@@"
string   adr_p6                           ADR_P6                           20       -        61       "@@"
string   adr_p7                           ADR_P7                           20       -        61       "@@"
string   adr_p8                           ADR_P8                           20       -        61       "@@"
string   adr_p9                           ADR_P9                           20       -        61       "@@"
string   adr_p10                          ADR_P10                          20       -        61       "@@"
END


VIEW vi_gnUpLnkEnt
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        51       "@@"
string   p2                               P2                               1        -        51       "@@"
string   p3                               P3                               1        -        51       "@@"
string   p4                               P4                               1        -        51       "@@"
string   p5                               P5                               1        -        51       "@@"
string   p6                               P6                               1        -        51       "@@"
string   p7                               P7                               1        -        51       "@@"
string   p8                               P8                               1        -        51       "@@"
string   p9                               P9                               1        -        51       "@@"
string   p10                              P10                              1        -        51       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
char     link_mode                        LINK_MODE                        1        -        -        "@"
long     link_ban                         LINK_BAN                         1        -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  1        -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      1        -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      1        -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
char     link_type                        LINK_TYPE                        1        -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   1        -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   1        -        -        -1061109568
char     billing_ind                      BILLING_IND                      1        -        -        "@"
char     mailing_ind                      MAILING_IND                      1        -        -        "@"
char     user_ind                         USER_IND                         1        -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 1        -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 1        -        -        "@"
char     link_user_ind                    LINK_USER_IND                    1        -        -        "@"
char     nm_mode                          NM_MODE                          1        -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       1        -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   1        -        9        "@@"
string   rowid                            ROWID                            1        -        19       "@@"
long     name_id                          NAME_ID                          1        -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               1        -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   control_name                     CONTROL_NAME                     1        -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               1        -        61       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 1        -        61       "@@"
char     name_format                      NAME_FORMAT                      1        -        -        "@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   identify                         IDENTIFY                         1        -        21       "@@"
string   id_type                          ID_TYPE                          1        -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      1        -        51       "@@"
double   kob                              KOB                              1        -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   1        -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    1        -        11       "@@"
short    conv_run_no                      CONV_RUN_NO                      1        -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            1        -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   1        -        4        "@@"
char     gender                           GENDER                           1        -        -        "@"
string   marital_status                   MARITAL_STATUS                   1        -        5        "@@"
char     role_ind                         ROLE_IND                         1        -        -        "@"
char     adr_mode                         ADR_MODE                         1        -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      1        -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  1        -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  1        -        19       "@@"
long     address_id                       ADDRESS_ID                       1        -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      1        -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        1        -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            1        -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         1        -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        1        -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        1        -        -        -16192
char     adr_type                         ADR_TYPE                         1        -        -        "@"
char     adr_status                       ADR_STATUS                       1        -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  1        -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 1        -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   1        -        101      "@@"
string   adr_city                         ADR_CITY                         1        -        40       "@@"
string   adr_zip                          ADR_ZIP                          1        -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     1        -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  1        -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    1        -        3        "@@"
string   adr_pob                          ADR_POB                          1        -        11       "@@"
string   adr_country                      ADR_COUNTRY                      1        -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 1        -        3        "@@"
string   adr_story                        ADR_STORY                        1        -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      1        -        5        "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   since_date                       SINCE_DATE                       1        -        9        "@@"
string   adr_district                     ADR_DISTRICT                     1        -        41       "@@"
char     co_ind                           CO_IND                           1        -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            1        -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               1        -        5        "@@"
string   county_code                      COUNTY_CODE                      1        -        3        "@@"
string   community_name                   COMMUNITY_NAME                   1        -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      1        -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   1        -        61       "@@"
string   adr_p1                           ADR_P1                           1        -        61       "@@"
string   adr_p2                           ADR_P2                           1        -        61       "@@"
string   adr_p3                           ADR_P3                           1        -        61       "@@"
string   adr_p4                           ADR_P4                           1        -        61       "@@"
string   adr_p5                           ADR_P5                           1        -        61       "@@"
string   adr_p6                           ADR_P6                           1        -        61       "@@"
string   adr_p7                           ADR_P7                           1        -        61       "@@"
string   adr_p8                           ADR_P8                           1        -        61       "@@"
string   adr_p9                           ADR_P9                           1        -        61       "@@"
string   adr_p10                          ADR_P10                          1        -        61       "@@"
END

VIEW vo_gnUpLnkEnt
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
char     link_mode                        LINK_MODE                        1        -        -        "@"
long     link_ban                         LINK_BAN                         1        -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  1        -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      1        -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      1        -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
char     link_type                        LINK_TYPE                        1        -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   1        -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   1        -        -        -1061109568
char     billing_ind                      BILLING_IND                      1        -        -        "@"
char     mailing_ind                      MAILING_IND                      1        -        -        "@"
char     user_ind                         USER_IND                         1        -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 1        -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 1        -        -        "@"
char     link_user_ind                    LINK_USER_IND                    1        -        -        "@"
char     nm_mode                          NM_MODE                          1        -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       1        -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   1        -        9        "@@"
string   rowid                            ROWID                            1        -        19       "@@"
long     name_id                          NAME_ID                          1        -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               1        -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   control_name                     CONTROL_NAME                     1        -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               1        -        61       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 1        -        61       "@@"
char     name_format                      NAME_FORMAT                      1        -        -        "@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   identify                         IDENTIFY                         1        -        21       "@@"
string   id_type                          ID_TYPE                          1        -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      1        -        51       "@@"
double   kob                              KOB                              1        -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   1        -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    1        -        11       "@@"
short    conv_run_no                      CONV_RUN_NO                      1        -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            1        -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   1        -        4        "@@"
char     gender                           GENDER                           1        -        -        "@"
string   marital_status                   MARITAL_STATUS                   1        -        5        "@@"
char     role_ind                         ROLE_IND                         1        -        -        "@"
char     adr_mode                         ADR_MODE                         1        -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      1        -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  1        -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  1        -        19       "@@"
long     address_id                       ADDRESS_ID                       1        -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      1        -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        1        -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            1        -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         1        -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        1        -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        1        -        -        -16192
char     adr_type                         ADR_TYPE                         1        -        -        "@"
char     adr_status                       ADR_STATUS                       1        -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  1        -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 1        -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   1        -        101      "@@"
string   adr_city                         ADR_CITY                         1        -        40       "@@"
string   adr_zip                          ADR_ZIP                          1        -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     1        -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  1        -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    1        -        3        "@@"
string   adr_pob                          ADR_POB                          1        -        11       "@@"
string   adr_country                      ADR_COUNTRY                      1        -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 1        -        3        "@@"
string   adr_story                        ADR_STORY                        1        -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      1        -        5        "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   since_date                       SINCE_DATE                       1        -        9        "@@"
string   adr_district                     ADR_DISTRICT                     1        -        41       "@@"
char     co_ind                           CO_IND                           1        -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            1        -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               1        -        5        "@@"
string   county_code                      COUNTY_CODE                      1        -        3        "@@"
string   community_name                   COMMUNITY_NAME                   1        -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      1        -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   1        -        61       "@@"
string   adr_p1                           ADR_P1                           1        -        61       "@@"
string   adr_p2                           ADR_P2                           1        -        61       "@@"
string   adr_p3                           ADR_P3                           1        -        61       "@@"
string   adr_p4                           ADR_P4                           1        -        61       "@@"
string   adr_p5                           ADR_P5                           1        -        61       "@@"
string   adr_p6                           ADR_P6                           1        -        61       "@@"
string   adr_p7                           ADR_P7                           1        -        61       "@@"
string   adr_p8                           ADR_P8                           1        -        61       "@@"
string   adr_p9                           ADR_P9                           1        -        61       "@@"
string   adr_p10                          ADR_P10                          1        -        61       "@@"
END


VIEW vi_gnGtAdrItm
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   zip                              ZIP                              1        -        10       "@@"
string   city                             CITY                             1        -        40       "@@"
string   streetName                       STREETNAME                       1        -        61       "@@"
string   houseNo                          HOUSENO                          1        -        21       "@@"
char     adrValidMode                     ADRVALIDMODE                     1        -        -        "@"
END

VIEW vo_gnGtAdrItm
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   addrZipArr                       ADDRZIPARR                       100      -        10       "@@"
string   addrCityArr                      ADDRCITYARR                      100      -        40       "@@"
string   addrStreetArr                    ADDRSTREETARR                    100      -        61       "@@"
string   rowid                            ROWID                            100      -        19       "@@"
long     seq_no                           SEQ_NO                           100      -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                100      -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  100      -        15       "@@"
long     operator_id                      OPERATOR_ID                      100      -        -        -1061109568
string   application_id                   APPLICATION_ID                   100      -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  100      -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  100      -        -        -16192
string   zip_code                         ZIP_CODE                         100      -        10       "@@"
string   city                             CITY                             100      -        40       "@@"
string   street_name                      STREET_NAME                      100      -        61       "@@"
string   house_letter_begin_range         HOUSE_LETTER_BEGIN_RANGE         100      -        3        "@@"
string   house_letter_end_range           HOUSE_LETTER_END_RANGE           100      -        3        "@@"
string   house_no_begin_range             HOUSE_NO_BEGIN_RANGE             100      -        21       "@@"
string   house_no_end_range               HOUSE_NO_END_RANGE               100      -        21       "@@"
char     validation_type                  VALIDATION_TYPE                  100      -        -        "@"
string   adr_pob                          ADR_POB                          100      -        11       "@@"
char     adr_type                         ADR_TYPE                         100      -        -        "@"
string   canton                           CANTON                           100      -        3        "@@"
string   county_code                      COUNTY_CODE                      100      -        3        "@@"
string   community_name                   COMMUNITY_NAME                   100      -        31       "@@"
string   district                         DISTRICT                         100      -        41       "@@"
END


VIEW vi_gnChkAdrVld
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   zip                              ZIP                              1        -        10       "@@"
string   city                             CITY                             1        -        40       "@@"
char     addrType                         ADDRTYPE                         1        -        -        "@"
string   streetName                       STREETNAME                       1        -        61       "@@"
string   houseNo                          HOUSENO                          1        -        21       "@@"
string   letter                           LETTER                           1        -        3        "@@"
string   pob                              POB                              1        -        11       "@@"
END

VIEW vo_gnChkAdrVld
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
char     validation_status                VALIDATION_STATUS                1        -        -        "@"
END


VIEW vi_gnUpNmAdr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   ban_rowid                        BAN_ROWID                        1        -        19       "@@"
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   customer_rowid                   CUSTOMER_ROWID                   1        -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   ctn_rowid                        CTN_ROWID                        1        -        19       "@@"
long     row_count                        ROW_COUNT                        1        -        -        -1061109568
string   act_code                         ACT_CODE                         50       -        4        "@@"
string   act_reason                       ACT_REASON                       50       -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                50       -        -        "@"
string   memo_ctn                         MEMO_CTN                         50       -        21       "@@"
string   user_text                        USER_TEXT                        50       -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      50       -        -        "@"
long     param_count                      PARAM_COUNT                      50       -        -        -1061109568
string   p1                               P1                               50       -        51       "@@"
string   p2                               P2                               50       -        51       "@@"
string   p3                               P3                               50       -        51       "@@"
string   p4                               P4                               50       -        51       "@@"
string   p5                               P5                               50       -        51       "@@"
string   p6                               P6                               50       -        51       "@@"
string   p7                               P7                               50       -        51       "@@"
string   p8                               P8                               50       -        51       "@@"
string   p9                               P9                               50       -        51       "@@"
string   p10                              P10                              50       -        51       "@@"
double   memo_amt                         MEMO_AMT                         50       -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     50       -        5        "@@"
double   charge_amt                       CHARGE_AMT                       50       -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   50       -        -        "@"
string   waive_reason                     WAIVE_REASON                     50       -        7        "@@"
char     waive_ind                        WAIVE_IND                        50       -        -        "@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
char     link_mode                        LINK_MODE                        20       -        -        "@"
long     link_ban                         LINK_BAN                         20       -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  20       -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      20       -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      20       -        -        -1061109568
long     lnkReccustomer_id                LNKRECCUSTOMER_ID                20       -        -        -1061109568
long     lnkRecban                        LNKRECBAN                        20       -        -        -1061109568
string   lnkRecsubscriber_no              LNKRECSUBSCRIBER_NO              20       -        21       "@@"
char     link_type                        LINK_TYPE                        20       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   20       -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   20       -        -        -1061109568
char     billing_ind                      BILLING_IND                      20       -        -        "@"
char     mailing_ind                      MAILING_IND                      20       -        -        "@"
char     user_ind                         USER_IND                         20       -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 20       -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 20       -        -        "@"
char     link_user_ind                    LINK_USER_IND                    20       -        -        "@"
char     nm_mode                          NM_MODE                          20       -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       20       -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   20       -        9        "@@"
string   rowid                            ROWID                            20       -        19       "@@"
long     name_id                          NAME_ID                          20       -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                20       -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  20       -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               20       -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            20       -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  20       -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  20       -        -        -16192
string   control_name                     CONTROL_NAME                     20       -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               20       -        61       "@@"
string   first_name                       FIRST_NAME                       20       -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 20       -        61       "@@"
char     name_format                      NAME_FORMAT                      20       -        -        "@"
string   birth_date                       BIRTH_DATE                       20       -        9        "@@"
string   identify                         IDENTIFY                         20       -        21       "@@"
string   id_type                          ID_TYPE                          20       -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      20       -        51       "@@"
double   kob                              KOB                              20       -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   20       -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    20       -        11       "@@"
short    conv_run_no                      CONV_RUN_NO                      20       -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            20       -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   20       -        4        "@@"
char     gender                           GENDER                           20       -        -        "@"
string   marital_status                   MARITAL_STATUS                   20       -        5        "@@"
char     role_ind                         ROLE_IND                         20       -        -        "@"
char     adr_mode                         ADR_MODE                         20       -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      20       -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  20       -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  20       -        19       "@@"
long     address_id                       ADDRESS_ID                       20       -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      20       -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        20       -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            20       -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         20       -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        20       -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        20       -        -        -16192
char     adr_type                         ADR_TYPE                         20       -        -        "@"
char     adr_status                       ADR_STATUS                       20       -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  20       -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 20       -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   20       -        101      "@@"
string   adr_city                         ADR_CITY                         20       -        40       "@@"
string   adr_zip                          ADR_ZIP                          20       -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     20       -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  20       -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    20       -        3        "@@"
string   adr_pob                          ADR_POB                          20       -        11       "@@"
string   adr_country                      ADR_COUNTRY                      20       -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 20       -        3        "@@"
string   adr_story                        ADR_STORY                        20       -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      20       -        5        "@@"
string   adr_email                        ADR_EMAIL                        20       -        151      "@@"
string   since_date                       SINCE_DATE                       20       -        9        "@@"
string   adr_district                     ADR_DISTRICT                     20       -        41       "@@"
char     co_ind                           CO_IND                           20       -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            20       -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               20       -        5        "@@"
string   county_code                      COUNTY_CODE                      20       -        3        "@@"
string   community_name                   COMMUNITY_NAME                   20       -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      20       -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   20       -        61       "@@"
string   adr_p1                           ADR_P1                           20       -        61       "@@"
string   adr_p2                           ADR_P2                           20       -        61       "@@"
string   adr_p3                           ADR_P3                           20       -        61       "@@"
string   adr_p4                           ADR_P4                           20       -        61       "@@"
string   adr_p5                           ADR_P5                           20       -        61       "@@"
string   adr_p6                           ADR_P6                           20       -        61       "@@"
string   adr_p7                           ADR_P7                           20       -        61       "@@"
string   adr_p8                           ADR_P8                           20       -        61       "@@"
string   adr_p9                           ADR_P9                           20       -        61       "@@"
string   adr_p10                          ADR_P10                          20       -        61       "@@"
END

VIEW vo_gnUpNmAdr
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
char     link_mode                        LINK_MODE                        20       -        -        "@"
long     link_ban                         LINK_BAN                         20       -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  20       -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      20       -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      20       -        -        -1061109568
long     lnkReccustomer_id                LNKRECCUSTOMER_ID                20       -        -        -1061109568
long     lnkRecban                        LNKRECBAN                        20       -        -        -1061109568
string   lnkRecsubscriber_no              LNKRECSUBSCRIBER_NO              20       -        21       "@@"
char     link_type                        LINK_TYPE                        20       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   20       -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   20       -        -        -1061109568
char     billing_ind                      BILLING_IND                      20       -        -        "@"
char     mailing_ind                      MAILING_IND                      20       -        -        "@"
char     user_ind                         USER_IND                         20       -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 20       -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 20       -        -        "@"
char     link_user_ind                    LINK_USER_IND                    20       -        -        "@"
char     nm_mode                          NM_MODE                          20       -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       20       -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   20       -        9        "@@"
string   rowid                            ROWID                            20       -        19       "@@"
long     name_id                          NAME_ID                          20       -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                20       -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  20       -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               20       -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            20       -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  20       -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  20       -        -        -16192
string   control_name                     CONTROL_NAME                     20       -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               20       -        61       "@@"
string   first_name                       FIRST_NAME                       20       -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 20       -        61       "@@"
char     name_format                      NAME_FORMAT                      20       -        -        "@"
string   birth_date                       BIRTH_DATE                       20       -        9        "@@"
string   identify                         IDENTIFY                         20       -        21       "@@"
string   id_type                          ID_TYPE                          20       -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      20       -        51       "@@"
double   kob                              KOB                              20       -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   20       -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    20       -        11       "@@"
short    conv_run_no                      CONV_RUN_NO                      20       -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            20       -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   20       -        4        "@@"
char     gender                           GENDER                           20       -        -        "@"
string   marital_status                   MARITAL_STATUS                   20       -        5        "@@"
char     role_ind                         ROLE_IND                         20       -        -        "@"
char     adr_mode                         ADR_MODE                         20       -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      20       -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  20       -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  20       -        19       "@@"
long     address_id                       ADDRESS_ID                       20       -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      20       -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        20       -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            20       -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         20       -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        20       -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        20       -        -        -16192
char     adr_type                         ADR_TYPE                         20       -        -        "@"
char     adr_status                       ADR_STATUS                       20       -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  20       -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 20       -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   20       -        101      "@@"
string   adr_city                         ADR_CITY                         20       -        40       "@@"
string   adr_zip                          ADR_ZIP                          20       -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     20       -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  20       -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    20       -        3        "@@"
string   adr_pob                          ADR_POB                          20       -        11       "@@"
string   adr_country                      ADR_COUNTRY                      20       -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 20       -        3        "@@"
string   adr_story                        ADR_STORY                        20       -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      20       -        5        "@@"
string   adr_email                        ADR_EMAIL                        20       -        151      "@@"
string   since_date                       SINCE_DATE                       20       -        9        "@@"
string   adr_district                     ADR_DISTRICT                     20       -        41       "@@"
char     co_ind                           CO_IND                           20       -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            20       -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               20       -        5        "@@"
string   county_code                      COUNTY_CODE                      20       -        3        "@@"
string   community_name                   COMMUNITY_NAME                   20       -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      20       -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   20       -        61       "@@"
string   adr_p1                           ADR_P1                           20       -        61       "@@"
string   adr_p2                           ADR_P2                           20       -        61       "@@"
string   adr_p3                           ADR_P3                           20       -        61       "@@"
string   adr_p4                           ADR_P4                           20       -        61       "@@"
string   adr_p5                           ADR_P5                           20       -        61       "@@"
string   adr_p6                           ADR_P6                           20       -        61       "@@"
string   adr_p7                           ADR_P7                           20       -        61       "@@"
string   adr_p8                           ADR_P8                           20       -        61       "@@"
string   adr_p9                           ADR_P9                           20       -        61       "@@"
string   adr_p10                          ADR_P10                          20       -        61       "@@"
END


