VIEW vi_arCrCrg
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
char     chg_impact                       CHG_IMPACT                       1        -        -        "@"
string   chg_due_date                     CHG_DUE_DATE                     1        -        9        "@@"
string   rowid                            ROWID                            1        -        19       "@@"
short    bill_cycle                       BILL_CYCLE                       1        -        -        -16192
short    bl_next_cycle                    BL_NEXT_CYCLE                    1        -        -        -16192
string   bl_next_cyc_eff_date             BL_NEXT_CYC_EFF_DATE             1        -        9        "@@"
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
string   pChargeRecrowid                  PCHARGERECROWID                  1        -        19       "@@"
long     root_ban                         ROOT_BAN                         1        -        -        -1061109568
long     pChargeRecban                    PCHARGERECBAN                    1        -        -        -1061109568
short    actv_bill_seq_no                 ACTV_BILL_SEQ_NO                 1        -        -        -16192
long     ent_seq_no                       ENT_SEQ_NO                       1        -        -        -1061109568
short    actv_seq_no                      ACTV_SEQ_NO                      1        -        -        -16192
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     pChargeRecoperator_id            PCHARGERECOPERATOR_ID            1        -        -        -1061109568
string   pChargeRecapplication_id         PCHARGERECAPPLICATION_ID         1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   voucher_num                      VOUCHER_NUM                      1        -        14       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   department                       DEPARTMENT                       1        -        5        "@@"
string   org_code                         ORG_CODE                         1        -        6        "@@"
string   product_type                     PRODUCT_TYPE                     1        -        4        "@@"
string   sub_market_cd                    SUB_MARKET_CD                    1        -        4        "@@"
string   priod_cvrg_st_date               PRIOD_CVRG_ST_DATE               1        -        9        "@@"
string   priod_cvrg_nd_date               PRIOD_CVRG_ND_DATE               1        -        9        "@@"
string   chg_creation_date                CHG_CREATION_DATE                1        -        9        "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        9        "@@"
string   finance_eff_date                 FINANCE_EFF_DATE                 1        -        9        "@@"
string   last_rg_rc_date                  LAST_RG_RC_DATE                  1        -        9        "@@"
string   actv_date                        ACTV_DATE                        1        -        9        "@@"
string   actv_code                        ACTV_CODE                        1        -        5        "@@"
string   actv_reason_code                 ACTV_REASON_CODE                 1        -        7        "@@"
double   actv_amt                         ACTV_AMT                         1        -        -        -8577.505882352939807
double   duration                         DURATION                         1        -        -        -8577.505882352939807
long     num_of_calls                     NUM_OF_CALLS                     1        -        -        -1061109568
string   feature_code                     FEATURE_CODE                     1        -        7        "@@"
string   ftr_revenue_code                 FTR_REVENUE_CODE                 1        -        4        "@@"
string   feature_category                 FEATURE_CATEGORY                 1        -        5        "@@"
string   secondary_feature_cd             SECONDARY_FEATURE_CD             1        -        7        "@@"
char     au_rating_scheme_ind             AU_RATING_SCHEME_IND             1        -        -        "@"
char     balance_impact_code              BALANCE_IMPACT_CODE              1        -        -        "@"
string   soc                              SOC                              1        -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       1        -        -        -1061109568
long     soc_ver_no                       SOC_VER_NO                       1        -        -        -1061109568
string   soc_date                         SOC_DATE                         1        -        9        "@@"
char     service_type                     SERVICE_TYPE                     1        -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               1        -        -        -1061109568
string   toll_rs_code                     TOLL_RS_CODE                     1        -        10       "@@"
char     source_appl_code                 SOURCE_APPL_CODE                 1        -        -        "@"
char     asgn_to_bill_appl_cd             ASGN_TO_BILL_APPL_CD             1        -        -        "@"
long     inv_seq_no                       INV_SEQ_NO                       1        -        -        -1061109568
double   vat_amt                          VAT_AMT                          1        -        -        -8577.505882352939807
double   vat_exmp_amt                     VAT_EXMP_AMT                     1        -        -        -8577.505882352939807
char     tax_code                         TAX_CODE                         1        -        -        "@"
double   vat_percent_rate                 VAT_PERCENT_RATE                 1        -        -        -8577.505882352939807
char     vat_exmp_ind                     VAT_EXMP_IND                     1        -        -        "@"
double   rc_ftr_pre_pror_amt              RC_FTR_PRE_PROR_AMT              1        -        -        -8577.505882352939807
double   before_discnt_amt                BEFORE_DISCNT_AMT                1        -        -        -8577.505882352939807
double   discount_amt                     DISCOUNT_AMT                     1        -        -        -8577.505882352939807
double   discount_pct                     DISCOUNT_PCT                     1        -        -        -8577.505882352939807
string   discount_code                    DISCOUNT_CODE                    1        -        10       "@@"
char     credit_level                     CREDIT_LEVEL                     1        -        -        "@"
short    crg_quantity                     CRG_QUANTITY                     1        -        -        -16192
string   au_issue_code                    AU_ISSUE_CODE                    1        -        7        "@@"
long     au_seq_no                        AU_SEQ_NO                        1        -        -        -1061109568
char     action_direction_cd              ACTION_DIRECTION_CD              1        -        -        "@"
char     manual_override_ind              MANUAL_OVERRIDE_IND              1        -        -        "@"
long     memo_id                          MEMO_ID                          1        -        -        -1061109568
char     bl_ignore_ind                    BL_IGNORE_IND                    1        -        -        "@"
char     charge_type                      CHARGE_TYPE                      1        -        -        "@"
string   utc_discount_type                UTC_DISCOUNT_TYPE                1        -        3        "@@"
short    frwd_fm_bill_seq_no              FRWD_FM_BILL_SEQ_NO              1        -        -        -16192
char     chg_group_level                  CHG_GROUP_LEVEL                  1        -        -        "@"
long     chg_group_id                     CHG_GROUP_ID                     1        -        -        -1061109568
char     charge_hist_ind                  CHARGE_HIST_IND                  1        -        -        "@"
long     utc_from_to_ban                  UTC_FROM_TO_BAN                  1        -        -        -1061109568
string   utc_from_subscriber              UTC_FROM_SUBSCRIBER              1        -        21       "@@"
string   bill_prod_grp                    BILL_PROD_GRP                    1        -        3        "@@"
char     utc_ind                          UTC_IND                          1        -        -        "@"
long     orig_seq_no                      ORIG_SEQ_NO                      1        -        -        -1061109568
string   channel_seizure_dt               CHANNEL_SEIZURE_DT               1        -        15       "@@"
string   message_switch_id                MESSAGE_SWITCH_ID                1        -        8        "@@"
string   message_identifier               MESSAGE_IDENTIFIER               1        -        25       "@@"
short    no_of_install_from               NO_OF_INSTALL_FROM               1        -        -        -16192
short    no_of_install_to                 NO_OF_INSTALL_TO                 1        -        -        -16192
short    total_no_of_install              TOTAL_NO_OF_INSTALL              1        -        -        -16192
string   rms_inv_store_id                 RMS_INV_STORE_ID                 1        -        5        "@@"
long     rms_inv_id                       RMS_INV_ID                       1        -        -        -1061109568
short    rms_inv_line_seq                 RMS_INV_LINE_SEQ                 1        -        -        -16192
short    rms_inv_subln_seq                RMS_INV_SUBLN_SEQ                1        -        -        -16192
char     rms_inv_actv_type                RMS_INV_ACTV_TYPE                1        -        -        "@"
string   bill_comment                     BILL_COMMENT                     1        -        501      "@@"
short    conv_run_no                      CONV_RUN_NO                      1        -        -        -16192
short    adj_msg_bill_seq_no              ADJ_MSG_BILL_SEQ_NO              1        -        -        -16192
string   designated_inv                   DESIGNATED_INV                   1        -        14       "@@"
long     designated_item                  DESIGNATED_ITEM                  1        -        -        -1061109568
char     bill_relevance_ind               BILL_RELEVANCE_IND               1        -        -        "@"
short    num_of_days_pym_late             NUM_OF_DAYS_PYM_LATE             1        -        -        -16192
double   percentage_rate                  PERCENTAGE_RATE                  1        -        -        -8577.505882352939807
string   bill_num_for_late_pym            BILL_NUM_FOR_LATE_PYM            1        -        14       "@@"
long     orig_oper_id                     ORIG_OPER_ID                     1        -        -        -1061109568
double   disc_utc_amt                     DISC_UTC_AMT                     1        -        -        -8577.505882352939807
double   disc_utc_vat                     DISC_UTC_VAT                     1        -        -        -8577.505882352939807
double   chrg_amt_prd_1                   CHRG_AMT_PRD_1                   1        -        -        -8577.505882352939807
double   chrg_amt_prd_2                   CHRG_AMT_PRD_2                   1        -        -        -8577.505882352939807
short    match_tier_level                 MATCH_TIER_LEVEL                 1        -        -        -16192
END

VIEW vo_arCrCrg
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   pChargeRecrowid                  PCHARGERECROWID                  1        -        19       "@@"
long     root_ban                         ROOT_BAN                         1        -        -        -1061109568
long     pChargeRecban                    PCHARGERECBAN                    1        -        -        -1061109568
short    actv_bill_seq_no                 ACTV_BILL_SEQ_NO                 1        -        -        -16192
long     ent_seq_no                       ENT_SEQ_NO                       1        -        -        -1061109568
short    actv_seq_no                      ACTV_SEQ_NO                      1        -        -        -16192
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     pChargeRecoperator_id            PCHARGERECOPERATOR_ID            1        -        -        -1061109568
string   pChargeRecapplication_id         PCHARGERECAPPLICATION_ID         1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   voucher_num                      VOUCHER_NUM                      1        -        14       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   department                       DEPARTMENT                       1        -        5        "@@"
string   org_code                         ORG_CODE                         1        -        6        "@@"
string   product_type                     PRODUCT_TYPE                     1        -        4        "@@"
string   sub_market_cd                    SUB_MARKET_CD                    1        -        4        "@@"
string   priod_cvrg_st_date               PRIOD_CVRG_ST_DATE               1        -        9        "@@"
string   priod_cvrg_nd_date               PRIOD_CVRG_ND_DATE               1        -        9        "@@"
string   chg_creation_date                CHG_CREATION_DATE                1        -        9        "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        9        "@@"
string   finance_eff_date                 FINANCE_EFF_DATE                 1        -        9        "@@"
string   last_rg_rc_date                  LAST_RG_RC_DATE                  1        -        9        "@@"
string   actv_date                        ACTV_DATE                        1        -        9        "@@"
string   actv_code                        ACTV_CODE                        1        -        5        "@@"
string   actv_reason_code                 ACTV_REASON_CODE                 1        -        7        "@@"
double   actv_amt                         ACTV_AMT                         1        -        -        -8577.505882352939807
double   duration                         DURATION                         1        -        -        -8577.505882352939807
long     num_of_calls                     NUM_OF_CALLS                     1        -        -        -1061109568
string   feature_code                     FEATURE_CODE                     1        -        7        "@@"
string   ftr_revenue_code                 FTR_REVENUE_CODE                 1        -        4        "@@"
string   feature_category                 FEATURE_CATEGORY                 1        -        5        "@@"
string   secondary_feature_cd             SECONDARY_FEATURE_CD             1        -        7        "@@"
char     au_rating_scheme_ind             AU_RATING_SCHEME_IND             1        -        -        "@"
char     balance_impact_code              BALANCE_IMPACT_CODE              1        -        -        "@"
string   soc                              SOC                              1        -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       1        -        -        -1061109568
long     soc_ver_no                       SOC_VER_NO                       1        -        -        -1061109568
string   soc_date                         SOC_DATE                         1        -        9        "@@"
char     service_type                     SERVICE_TYPE                     1        -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               1        -        -        -1061109568
string   toll_rs_code                     TOLL_RS_CODE                     1        -        10       "@@"
char     source_appl_code                 SOURCE_APPL_CODE                 1        -        -        "@"
char     asgn_to_bill_appl_cd             ASGN_TO_BILL_APPL_CD             1        -        -        "@"
long     inv_seq_no                       INV_SEQ_NO                       1        -        -        -1061109568
double   vat_amt                          VAT_AMT                          1        -        -        -8577.505882352939807
double   vat_exmp_amt                     VAT_EXMP_AMT                     1        -        -        -8577.505882352939807
char     tax_code                         TAX_CODE                         1        -        -        "@"
double   vat_percent_rate                 VAT_PERCENT_RATE                 1        -        -        -8577.505882352939807
char     vat_exmp_ind                     VAT_EXMP_IND                     1        -        -        "@"
double   rc_ftr_pre_pror_amt              RC_FTR_PRE_PROR_AMT              1        -        -        -8577.505882352939807
double   before_discnt_amt                BEFORE_DISCNT_AMT                1        -        -        -8577.505882352939807
double   discount_amt                     DISCOUNT_AMT                     1        -        -        -8577.505882352939807
double   discount_pct                     DISCOUNT_PCT                     1        -        -        -8577.505882352939807
string   discount_code                    DISCOUNT_CODE                    1        -        10       "@@"
char     credit_level                     CREDIT_LEVEL                     1        -        -        "@"
short    crg_quantity                     CRG_QUANTITY                     1        -        -        -16192
string   au_issue_code                    AU_ISSUE_CODE                    1        -        7        "@@"
long     au_seq_no                        AU_SEQ_NO                        1        -        -        -1061109568
char     action_direction_cd              ACTION_DIRECTION_CD              1        -        -        "@"
char     manual_override_ind              MANUAL_OVERRIDE_IND              1        -        -        "@"
long     memo_id                          MEMO_ID                          1        -        -        -1061109568
char     bl_ignore_ind                    BL_IGNORE_IND                    1        -        -        "@"
char     charge_type                      CHARGE_TYPE                      1        -        -        "@"
string   utc_discount_type                UTC_DISCOUNT_TYPE                1        -        3        "@@"
short    frwd_fm_bill_seq_no              FRWD_FM_BILL_SEQ_NO              1        -        -        -16192
char     chg_group_level                  CHG_GROUP_LEVEL                  1        -        -        "@"
long     chg_group_id                     CHG_GROUP_ID                     1        -        -        -1061109568
char     charge_hist_ind                  CHARGE_HIST_IND                  1        -        -        "@"
long     utc_from_to_ban                  UTC_FROM_TO_BAN                  1        -        -        -1061109568
string   utc_from_subscriber              UTC_FROM_SUBSCRIBER              1        -        21       "@@"
string   bill_prod_grp                    BILL_PROD_GRP                    1        -        3        "@@"
char     utc_ind                          UTC_IND                          1        -        -        "@"
long     orig_seq_no                      ORIG_SEQ_NO                      1        -        -        -1061109568
string   channel_seizure_dt               CHANNEL_SEIZURE_DT               1        -        15       "@@"
string   message_switch_id                MESSAGE_SWITCH_ID                1        -        8        "@@"
string   message_identifier               MESSAGE_IDENTIFIER               1        -        25       "@@"
short    no_of_install_from               NO_OF_INSTALL_FROM               1        -        -        -16192
short    no_of_install_to                 NO_OF_INSTALL_TO                 1        -        -        -16192
short    total_no_of_install              TOTAL_NO_OF_INSTALL              1        -        -        -16192
string   rms_inv_store_id                 RMS_INV_STORE_ID                 1        -        5        "@@"
long     rms_inv_id                       RMS_INV_ID                       1        -        -        -1061109568
short    rms_inv_line_seq                 RMS_INV_LINE_SEQ                 1        -        -        -16192
short    rms_inv_subln_seq                RMS_INV_SUBLN_SEQ                1        -        -        -16192
char     rms_inv_actv_type                RMS_INV_ACTV_TYPE                1        -        -        "@"
string   bill_comment                     BILL_COMMENT                     1        -        501      "@@"
short    conv_run_no                      CONV_RUN_NO                      1        -        -        -16192
short    adj_msg_bill_seq_no              ADJ_MSG_BILL_SEQ_NO              1        -        -        -16192
string   designated_inv                   DESIGNATED_INV                   1        -        14       "@@"
long     designated_item                  DESIGNATED_ITEM                  1        -        -        -1061109568
char     bill_relevance_ind               BILL_RELEVANCE_IND               1        -        -        "@"
short    num_of_days_pym_late             NUM_OF_DAYS_PYM_LATE             1        -        -        -16192
double   percentage_rate                  PERCENTAGE_RATE                  1        -        -        -8577.505882352939807
string   bill_num_for_late_pym            BILL_NUM_FOR_LATE_PYM            1        -        14       "@@"
long     orig_oper_id                     ORIG_OPER_ID                     1        -        -        -1061109568
double   disc_utc_amt                     DISC_UTC_AMT                     1        -        -        -8577.505882352939807
double   disc_utc_vat                     DISC_UTC_VAT                     1        -        -        -8577.505882352939807
double   chrg_amt_prd_1                   CHRG_AMT_PRD_1                   1        -        -        -8577.505882352939807
double   chrg_amt_prd_2                   CHRG_AMT_PRD_2                   1        -        -        -8577.505882352939807
short    match_tier_level                 MATCH_TIER_LEVEL                 1        -        -        -16192
string   bill_close_date                  BILL_CLOSE_DATE                  1        -        9        "@@"
END


VIEW vi_arGtOcInfo
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   feature_code                     FEATURE_CODE                     1        -        7        "@@"
END

VIEW vo_arGtOcInfo
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
string   feature_code                     FEATURE_CODE                     1        -        7        "@@"
char     manual_oc_create_ind             MANUAL_OC_CREATE_IND             1        -        -        "@"
char     mnl_oc_txt_ovrd_ind              MNL_OC_TXT_OVRD_IND              1        -        -        "@"
char     mnl_oc_chrg_level                MNL_OC_CHRG_LEVEL                1        -        -        "@"
char     mnl_oc_amt_ovrd_ind              MNL_OC_AMT_OVRD_IND              1        -        -        "@"
string   bill_fixed_text                  BILL_FIXED_TEXT                  1        -        61       "@@"
double   oc_charge_amt                    OC_CHARGE_AMT                    1        -        -        -8577.505882352939807
END


VIEW vi_arGtManOc
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   chg_category                     CHG_CATEGORY                     1        -        3        "@@"
END

VIEW vo_arGtManOc
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            600      -        19       "@@"
string   feature_code                     FEATURE_CODE                     600      -        7        "@@"
char     manual_oc_create_ind             MANUAL_OC_CREATE_IND             600      -        -        "@"
char     mnl_oc_txt_ovrd_ind              MNL_OC_TXT_OVRD_IND              600      -        -        "@"
char     mnl_oc_chrg_level                MNL_OC_CHRG_LEVEL                600      -        -        "@"
char     mnl_oc_amt_ovrd_ind              MNL_OC_AMT_OVRD_IND              600      -        -        "@"
string   bill_fixed_text                  BILL_FIXED_TEXT                  600      -        61       "@@"
double   oc_charge_amt                    OC_CHARGE_AMT                    600      -        -        -8577.505882352939807
END


VIEW vi_arDlCrg
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
long     ent_seq_no                       ENT_SEQ_NO                       1        -        -        -1061109568
short    actv_seq_no                      ACTV_SEQ_NO                      1        -        -        -16192
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_arDlCrg
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


