VIEW vi_csApiBan
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     pBanCustRecoperator_id           PBANCUSTRECOPERATOR_ID           1        -        -        -1061109568
string   pBanCustRecapplication_id        PBANCUSTRECAPPLICATION_ID        1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   customer_telno                   CUSTOMER_TELNO                   1        -        21       "@@"
string   customer_fax                     CUSTOMER_FAX                     1        -        21       "@@"
string   work_telno                       WORK_TELNO                       1        -        21       "@@"
string   work_fax                         WORK_FAX                         1        -        21       "@@"
string   dealer_code                      DEALER_CODE                      1        -        6        "@@"
string   sales_agent                      SALES_AGENT                      1        -        6        "@@"
string   market_id                        MARKET_ID                        1        -        4        "@@"
string   acc_password                     ACC_PASSWORD                     1        -        21       "@@"
string   verified_date                    VERIFIED_DATE                    1        -        9        "@@"
string   conv_cust_id                     CONV_CUST_ID                     1        -        11       "@@"
string   business_entity                  BUSINESS_ENTITY                  1        -        4        "@@"
string   location                         LOCATION                         1        -        5        "@@"
short    conv_run_no                      CONV_RUN_NO                      1        -        -        -16192
char     age_verification_status          AGE_VERIFICATION_STATUS          1        -        -        "@"
string   employment_type                  EMPLOYMENT_TYPE                  1        -        5        "@@"
string   employment_date                  EMPLOYMENT_DATE                  1        -        9        "@@"
string   open_bank_account_date           OPEN_BANK_ACCOUNT_DATE           1        -        9        "@@"
string   e_post                           E_POST                           1        -        151      "@@"
string   pBanRecrowid                     PBANRECROWID                     1        -        19       "@@"
long     ban                              BAN                              1        -        -        -1061109568
string   pBanRecsys_creation_date         PBANRECSYS_CREATION_DATE         1        -        15       "@@"
string   pBanRecsys_update_date           PBANRECSYS_UPDATE_DATE           1        -        15       "@@"
long     pBanRecoperator_id               PBANRECOPERATOR_ID               1        -        -        -1061109568
string   pBanRecapplication_id            PBANRECAPPLICATION_ID            1        -        7        "@@"
long     pBanReccustomer_id               PBANRECCUSTOMER_ID               1        -        -        -1061109568
string   start_service_date               START_SERVICE_DATE               1        -        9        "@@"
char     col_delinq_status                COL_DELINQ_STATUS                1        -        -        "@"
char     ban_status                       BAN_STATUS                       1        -        -        "@"
string   status_last_date                 STATUS_LAST_DATE                 1        -        9        "@@"
string   status_actv_code                 STATUS_ACTV_CODE                 1        -        4        "@@"
string   status_actv_rsn_code             STATUS_ACTV_RSN_CODE             1        -        5        "@@"
short    bill_cycle                       BILL_CYCLE                       1        -        -        -16192
double   ar_balance                       AR_BALANCE                       1        -        -        -8577.505882352939807
short    bl_cur_bill_seq_no               BL_CUR_BILL_SEQ_NO               1        -        -        -16192
string   bl_last_rg_cyc_date              BL_LAST_RG_CYC_DATE              1        -        9        "@@"
char     bl_complt_status                 BL_COMPLT_STATUS                 1        -        -        "@"
short    bl_special_cycle                 BL_SPECIAL_CYCLE                 1        -        -        -16192
string   account_sub_type                 ACCOUNT_SUB_TYPE                 1        -        3        "@@"
string   bl_man_hndl_rsn                  BL_MAN_HNDL_RSN                  1        -        3        "@@"
string   bl_man_hndl_eff_date             BL_MAN_HNDL_EFF_DATE             1        -        9        "@@"
string   bl_man_hndl_exp_date             BL_MAN_HNDL_EXP_DATE             1        -        9        "@@"
long     bl_man_hndl_req_opid             BL_MAN_HNDL_REQ_OPID             1        -        -        -1061109568
long     bl_man_hndl_by_opid              BL_MAN_HNDL_BY_OPID              1        -        -        -1061109568
string   bl_req_st_grace_prd              BL_REQ_ST_GRACE_PRD              1        -        9        "@@"
string   bl_req_end_grace_prd             BL_REQ_END_GRACE_PRD             1        -        9        "@@"
short    bl_next_cycle                    BL_NEXT_CYCLE                    1        -        -        -16192
string   bl_next_cyc_eff_date             BL_NEXT_CYC_EFF_DATE             1        -        9        "@@"
long     cs_min_req_ctns                  CS_MIN_REQ_CTNS                  1        -        -        -1061109568
char     cs_spec_memo_ind                 CS_SPEC_MEMO_IND                 1        -        -        "@"
char     ar_excpt_acct_ind                AR_EXCPT_ACCT_IND                1        -        -        "@"
string   cs_com_start_date                CS_COM_START_DATE                1        -        9        "@@"
string   cs_com_end_date                  CS_COM_END_DATE                  1        -        9        "@@"
string   cs_com_reason_code               CS_COM_REASON_CODE               1        -        4        "@@"
short    cs_com_orig_no_month             CS_COM_ORIG_NO_MONTH             1        -        -        -16192
char     ar_wo_ind                        AR_WO_IND                        1        -        -        "@"
char     account_type                     ACCOUNT_TYPE                     1        -        -        "@"
string   col_assigned_coll                COL_ASSIGNED_COLL                1        -        9        "@@"
char     bl_zero_balanc_ind               BL_ZERO_BALANC_IND               1        -        -        "@"
string   default_sub_market               DEFAULT_SUB_MARKET               1        -        4        "@@"
char     bl_def_mailing_ind               BL_DEF_MAILING_IND               1        -        -        "@"
char     bl_bill_prod_ind                 BL_BILL_PROD_IND                 1        -        -        "@"
char     bl_bal_handle_ind                BL_BAL_HANDLE_IND                1        -        -        "@"
char     bl_no_mnsp_ind                   BL_NO_MNSP_IND                   1        -        -        "@"
char     cs_ban_trx_off_ind               CS_BAN_TRX_OFF_IND               1        -        -        "@"
char     cs_handle_by_ctn_ind             CS_HANDLE_BY_CTN_IND             1        -        -        "@"
char     cs_lock_mechanism                CS_LOCK_MECHANISM                1        -        -        "@"
double   comp_crd_lmt                     COMP_CRD_LMT                     1        -        -        -8577.505882352939807
char     credit_class                     CREDIT_CLASS                     1        -        -        "@"
string   credit_date                      CREDIT_DATE                      1        -        15       "@@"
char     credit_source                    CREDIT_SOURCE                    1        -        -        "@"
string   credit_status                    CREDIT_STATUS                    1        -        3        "@@"
double   equ_crd_lmt                      EQU_CRD_LMT                      1        -        -        -8577.505882352939807
char     bl_vat_exempt_ind                BL_VAT_EXEMPT_IND                1        -        -        "@"
string   bl_vat_exempt_date               BL_VAT_EXEMPT_DATE               1        -        9        "@@"
string   bl_vat_exempt_ref_no             BL_VAT_EXEMPT_REF_NO             1        -        17       "@@"
string   bl_vat_exempt_rsn_cd             BL_VAT_EXEMPT_RSN_CD             1        -        4        "@@"
string   default_department               DEFAULT_DEPARTMENT               1        -        5        "@@"
char     col_code                         COL_CODE                         1        -        -        "@"
long     curr_root_ban                    CURR_ROOT_BAN                    1        -        -        -1061109568
long     next_root_ban                    NEXT_ROOT_BAN                    1        -        -        -1061109568
long     partition_root_ban               PARTITION_ROOT_BAN               1        -        -        -1061109568
short    cycle_frequency                  CYCLE_FREQUENCY                  1        -        -        -16192
short    cycle_first_bill_month           CYCLE_FIRST_BILL_MONTH           1        -        -        -16192
short    bl_due_day                       BL_DUE_DAY                       1        -        -        -16192
char     vip_ind                          VIP_IND                          1        -        -        "@"
char     black_listed_ind                 BLACK_LISTED_IND                 1        -        -        "@"
string   bl_prt_category                  BL_PRT_CATEGORY                  1        -        3        "@@"
string   cs_def_product_type              CS_DEF_PRODUCT_TYPE              1        -        4        "@@"
string   org_code                         ORG_CODE                         1        -        6        "@@"
char     bl_hier_ban_ind                  BL_HIER_BAN_IND                  1        -        -        "@"
string   payment_method                   PAYMENT_METHOD                   1        -        3        "@@"
string   payment_sub_method               PAYMENT_SUB_METHOD               1        -        3        "@@"
string   old_account_id                   OLD_ACCOUNT_ID                   1        -        21       "@@"
char     carry_over_bill                  CARRY_OVER_BILL                  1        -        -        "@"
char     hide_phone_digits_ind            HIDE_PHONE_DIGITS_IND            1        -        -        "@"
string   sec_department                   SEC_DEPARTMENT                   1        -        5        "@@"
long     next_conf_root_ban               NEXT_CONF_ROOT_BAN               1        -        -        -1061109568
double   edi_location_number              EDI_LOCATION_NUMBER              1        -        -        -8577.505882352939807
char     allow_advertising_ind            ALLOW_ADVERTISING_IND            1        -        -        "@"
string   agency_ref_no                    AGENCY_REF_NO                    1        -        9        "@@"
string   col_agency_conf_dt               COL_AGENCY_CONF_DT               1        -        9        "@@"
string   ban_group_no                     BAN_GROUP_NO                     1        -        11       "@@"
char     caap_type                        CAAP_TYPE                        1        -        -        "@"
string   col_agncy_code                   COL_AGNCY_CODE                   1        -        9        "@@"
char     invoice_fee_waive_ind            INVOICE_FEE_WAIVE_IND            1        -        -        "@"
char     prd_zero_rate_bill               PRD_ZERO_RATE_BILL               1        -        -        "@"
char     brand_id                         BRAND_ID                         1        -        -        "@"
char     cs_credit_class                  CS_CREDIT_CLASS                  1        -        -        "@"
short    cs_approved_ctn_qty              CS_APPROVED_CTN_QTY              1        -        -        -16192
long     cas_order_number                 CAS_ORDER_NUMBER                 1        -        -        -1061109568
long     pCtnAgrPrmRecban                 PCTNAGRPRMRECBAN                 1        -        -        -1061109568
string   ban_rowid                        BAN_ROWID                        1        -        19       "@@"
long     pCtnAgrPrmReccustomer_id         PCTNAGRPRMRECCUSTOMER_ID         1        -        -        -1061109568
string   customer_rowid                   CUSTOMER_ROWID                   1        -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
string   ctn_rowid                        CTN_ROWID                        1        -        19       "@@"
string   pCtnRecrowid                     PCTNRECROWID                     1        -        19       "@@"
string   pCtnRecsubscriber_no             PCTNRECSUBSCRIBER_NO             1        -        21       "@@"
long     pCtnReccustomer_id               PCTNRECCUSTOMER_ID               1        -        -        -1061109568
string   pCtnRecsys_creation_date         PCTNRECSYS_CREATION_DATE         1        -        15       "@@"
string   pCtnRecsys_update_date           PCTNRECSYS_UPDATE_DATE           1        -        15       "@@"
long     pCtnRecoperator_id               PCTNRECOPERATOR_ID               1        -        -        -1061109568
string   pCtnRecapplication_id            PCTNRECAPPLICATION_ID            1        -        7        "@@"
string   pCtnRecdl_service_code           PCTNRECDL_SERVICE_CODE           1        -        6        "@@"
short    pCtnRecdl_update_stamp           PCTNRECDL_UPDATE_STAMP           1        -        -        -16192
string   effective_date                   EFFECTIVE_DATE                   1        -        15       "@@"
string   init_activation_date             INIT_ACTIVATION_DATE             1        -        9        "@@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
string   sub_status_date                  SUB_STATUS_DATE                  1        -        9        "@@"
string   original_init_date               ORIGINAL_INIT_DATE               1        -        15       "@@"
string   sub_status_last_act              SUB_STATUS_LAST_ACT              1        -        4        "@@"
string   sub_status_rsn_code              SUB_STATUS_RSN_CODE              1        -        5        "@@"
string   product_type                     PRODUCT_TYPE                     1        -        4        "@@"
long     customer_ban                     CUSTOMER_BAN                     1        -        -        -1061109568
long     ctn_seq_no                       CTN_SEQ_NO                       1        -        -        -1061109568
string   req_st_grace_period              REQ_ST_GRACE_PERIOD              1        -        9        "@@"
string   req_end_grace_period             REQ_END_GRACE_PERIOD             1        -        9        "@@"
string   commit_start_date                COMMIT_START_DATE                1        -        9        "@@"
string   commit_end_date                  COMMIT_END_DATE                  1        -        9        "@@"
string   commit_reason_code               COMMIT_REASON_CODE               1        -        4        "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             1        -        -        -16192
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   contract_no                      CONTRACT_NO                      1        -        11       "@@"
long     cnt_seq_no                       CNT_SEQ_NO                       1        -        -        -1061109568
string   pCtnRecdealer_code               PCTNRECDEALER_CODE               1        -        6        "@@"
string   org_dealer_code                  ORG_DEALER_CODE                  1        -        6        "@@"
string   pCtnRecsales_agent               PCTNRECSALES_AGENT               1        -        6        "@@"
string   org_sales_agent                  ORG_SALES_AGENT                  1        -        6        "@@"
double   req_deposit_amt                  REQ_DEPOSIT_AMT                  1        -        -        -8577.505882352939807
string   leading_number                   LEADING_NUMBER                   1        -        21       "@@"
char     pabx_ind                         PABX_IND                         1        -        -        "@"
string   next_ctn                         NEXT_CTN                         1        -        21       "@@"
string   next_ctn_chg_date                NEXT_CTN_CHG_DATE                1        -        9        "@@"
string   prv_ctn                          PRV_CTN                          1        -        21       "@@"
string   prv_ctn_chg_date                 PRV_CTN_CHG_DATE                 1        -        9        "@@"
long     next_ban                         NEXT_BAN                         1        -        -        -1061109568
string   next_ban_move_date               NEXT_BAN_MOVE_DATE               1        -        9        "@@"
long     prv_ban                          PRV_BAN                          1        -        -        -1061109568
string   prv_ban_move_date                PRV_BAN_MOVE_DATE                1        -        9        "@@"
string   sub_sts_issue_date               SUB_STS_ISSUE_DATE               1        -        9        "@@"
string   activate_waive_rsn               ACTIVATE_WAIVE_RSN               1        -        7        "@@"
string   earliest_actv_date               EARLIEST_ACTV_DATE               1        -        9        "@@"
string   sub_actv_location                SUB_ACTV_LOCATION                1        -        5        "@@"
double   cust_watch_lmt                   CUST_WATCH_LMT                   1        -        -        -8577.505882352939807
string   cust_watch_date                  CUST_WATCH_DATE                  1        -        9        "@@"
double   basic_watch_lmt                  BASIC_WATCH_LMT                  1        -        -        -8577.505882352939807
short    credit_watch_pin_cd              CREDIT_WATCH_PIN_CD              1        -        -        -16192
string   sub_market_code                  SUB_MARKET_CODE                  1        -        4        "@@"
short    limit_reserved_days              LIMIT_RESERVED_DAYS              1        -        -        -16192
string   ff_expiration_date               FF_EXPIRATION_DATE               1        -        15       "@@"
char     flex_ind                         FLEX_IND                         1        -        -        "@"
char     duo_ind                          DUO_IND                          1        -        -        "@"
char     listed_ind                       LISTED_IND                       1        -        -        "@"
string   sub_department_cd                SUB_DEPARTMENT_CD                1        -        5        "@@"
string   last_subs_disc_dt                LAST_SUBS_DISC_DT                1        -        9        "@@"
string   last_subs_disc_dt_ud             LAST_SUBS_DISC_DT_UD             1        -        9        "@@"
short    last_subscr_disc_sn              LAST_SUBSCR_DISC_SN              1        -        -        -16192
short    last_subscr_disc_sn_ud           LAST_SUBSCR_DISC_SN_UD           1        -        -        -16192
string   pni                              PNI                              1        -        11       "@@"
string   rms_ref_store_id                 RMS_REF_STORE_ID                 1        -        5        "@@"
char     rms_ref_type                     RMS_REF_TYPE                     1        -        -        "@"
long     rms_ref_od                       RMS_REF_OD                       1        -        -        -1061109568
double   dlr_act_fee                      DLR_ACT_FEE                      1        -        -        -8577.505882352939807
double   prep_amount                      PREP_AMOUNT                      1        -        -        -8577.505882352939807
long     subscriber_id                    SUBSCRIBER_ID                    1        -        -        -1061109568
string   sub_lang                         SUB_LANG                         1        -        3        "@@"
string   sms_rcv_style_code               SMS_RCV_STYLE_CODE               1        -        3        "@@"
short    pCtnRecconv_run_no               PCTNRECCONV_RUN_NO               1        -        -        -16192
char     pCtnRecallow_advertising_ind     PCTNRECALLOW_ADVERTISING_IND     1        -        -        "@"
short    ivr_wrong_access_no              IVR_WRONG_ACCESS_NO              1        -        -        -16192
double   threshold_amt                    THRESHOLD_AMT                    1        -        -        -8577.505882352939807
string   publish_level                    PUBLISH_LEVEL                    1        -        31       "@@"
char     auto_release_ind                 AUTO_RELEASE_IND                 1        -        -        "@"
string   cust_watch_eff_date              CUST_WATCH_EFF_DATE              1        -        9        "@@"
string   cust_watch_exp_date              CUST_WATCH_EXP_DATE              1        -        9        "@@"
double   operator_cw_lmt                  OPERATOR_CW_LMT                  1        -        -        -8577.505882352939807
char     send_sms_for_match               SEND_SMS_FOR_MATCH               1        -        -        "@"
char     cps_status                       CPS_STATUS                       1        -        -        "@"
short    cps_transaction                  CPS_TRANSACTION                  1        -        -        -16192
short    cps_type                         CPS_TYPE                         1        -        -        -16192
string   isp_pass                         ISP_PASS                         1        -        31       "@@"
string   isp_type                         ISP_TYPE                         1        -        3        "@@"
string   operator_tmp_date                OPERATOR_TMP_DATE                1        -        9        "@@"
double   operator_tmp_lmt                 OPERATOR_TMP_LMT                 1        -        -        -8577.505882352939807
string   sub_org_cd                       SUB_ORG_CD                       1        -        11       "@@"
string   org_member_no                    ORG_MEMBER_NO                    1        -        21       "@@"
char     fixed_as_gsm_ind                 FIXED_AS_GSM_IND                 1        -        -        "@"
char     early_port_out                   EARLY_PORT_OUT                   1        -        -        "@"
char     early_po_waive_ind               EARLY_PO_WAIVE_IND               1        -        -        "@"
string   early_po_waive_reason            EARLY_PO_WAIVE_REASON            1        -        7        "@@"
char     fullTable                        FULLTABLE                        1        -        -        "@"
string   paper_work_status                PAPER_WORK_STATUS                1        -        3        "@@"
char     paper_work_required              PAPER_WORK_REQUIRED              1        -        -        "@"
string   paper_work_date                  PAPER_WORK_DATE                  1        -        9        "@@"
string   paper_work_ref_no                PAPER_WORK_REF_NO                1        -        12       "@@"
string   paper_work_trns_no               PAPER_WORK_TRNS_NO               1        -        26       "@@"
char     delivery_type                    DELIVERY_TYPE                    1        -        -        "@"
long     rowcount                         ROWCOUNT                         1        -        -        -1061109568
string   pAgrSocBufrowid                  PAGRSOCBUFROWID                  50       -        19       "@@"
string   soc                              SOC                              50       -        10       "@@"
string   soc_effective_date               SOC_EFFECTIVE_DATE               50       -        9        "@@"
string   commitment_end_date              COMMITMENT_END_DATE              50       -        9        "@@"
char     service_type                     SERVICE_TYPE                     50       -        -        "@"
string   pAgrSocBufeffective_date         PAGRSOCBUFEFFECTIVE_DATE         50       -        9        "@@"
string   expiration_date                  EXPIRATION_DATE                  50       -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   50       -        -        "@"
string   pAgrSocBufdealer_code            PAGRSOCBUFDEALER_CODE            50       -        6        "@@"
string   pAgrSocBufsales_agent            PAGRSOCBUFSALES_AGENT            50       -        6        "@@"
char     srv_mode                         SRV_MODE                         50       -        -        "@"
char     srv_sub_mode                     SRV_SUB_MODE                     50       -        -        "@"
long     soc_seq_no                       SOC_SEQ_NO                       50       -        -        -1061109568
long     srv_trx_id                       SRV_TRX_ID                       50       -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     50       -        -        -1061109568
string   campaign                         CAMPAIGN                         50       -        10       "@@"
short    pAgrSocBufcommit_orig_no_month   PAGRSOCBUFCOMMIT_ORIG_NO_MONTH   50       -        -        -16192
string   pAgrSocBufproduct_type           PAGRSOCBUFPRODUCT_TYPE           50       -        4        "@@"
long     loan_ver_no                      LOAN_VER_NO                      50       -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      50       -        -        -1061109568
double   soc_actv_fee                     SOC_ACTV_FEE                     50       -        -        -8577.505882352939807
string   promotional_soc                  PROMOTIONAL_SOC                  50       -        10       "@@"
string   reason_code                      REASON_CODE                      50       -        5        "@@"
string   soc_start_rc_date                SOC_START_RC_DATE                50       -        9        "@@"
char     rc_date_copy_ind                 RC_DATE_COPY_IND                 50       -        -        "@"
long     loan_sub_id                      LOAN_SUB_ID                      50       -        -        -1061109568
long     pAgrFrndFmlrowCount              PAGRFRNDFMLROWCOUNT              1        -        -        -1061109568
char     actionInd                        ACTIONIND                        10000    -        -        "@"
string   pcsFandFRecrowid                 PCSFANDFRECROWID                 10000    -        19       "@@"
string   pcsFandFReceffective_date        PCSFANDFRECEFFECTIVE_DATE        10000    -        15       "@@"
string   pcsFandFRecexpiration_date       PCSFANDFRECEXPIRATION_DATE       10000    -        15       "@@"
string   personal_tel                     PERSONAL_TEL                     10000    -        21       "@@"
string   personal_tel_to                  PERSONAL_TEL_TO                  10000    -        21       "@@"
string   ff_soc                           FF_SOC                           10000    -        10       "@@"
string   plan_code                        PLAN_CODE                        10000    -        10       "@@"
char     discount_type                    DISCOUNT_TYPE                    10000    -        -        "@"
string   start_hour                       START_HOUR                       10000    -        7        "@@"
double   duration                         DURATION                         10000    -        -        -8577.505882352939807
long     pAgrFtrDepBufrowcount            PAGRFTRDEPBUFROWCOUNT            1        -        -        -1061109568
char     deposit_type                     DEPOSIT_TYPE                     2        -        -        "@"
double   deposit_amount                   DEPOSIT_AMOUNT                   2        -        -        -8577.505882352939807
long     row_count                        ROW_COUNT                        1        -        -        -1061109568
string   act_code                         ACT_CODE                         25       -        4        "@@"
string   act_reason                       ACT_REASON                       25       -        5        "@@"
char     pEfCsmActvBufsusp_rc_rate_type   PEFCSMACTVBUFSUSP_RC_RATE_TYPE   25       -        -        "@"
string   memo_ctn                         MEMO_CTN                         25       -        21       "@@"
string   user_text                        USER_TEXT                        25       -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      25       -        -        "@"
long     param_count                      PARAM_COUNT                      25       -        -        -1061109568
string   p1                               P1                               25       -        21       "@@"
string   p2                               P2                               25       -        21       "@@"
string   p3                               P3                               25       -        21       "@@"
string   p4                               P4                               25       -        21       "@@"
string   p5                               P5                               25       -        21       "@@"
string   p6                               P6                               25       -        21       "@@"
string   p7                               P7                               25       -        21       "@@"
string   p8                               P8                               25       -        21       "@@"
string   p9                               P9                               25       -        21       "@@"
string   p10                              P10                              25       -        21       "@@"
double   memo_amt                         MEMO_AMT                         25       -        -        -8577.505882352939807
string   rms_act_code                     RMS_ACT_CODE                     25       -        5        "@@"
double   charge_amt                       CHARGE_AMT                       25       -        -        -8577.505882352939807
char     charge_amt_ind                   CHARGE_AMT_IND                   25       -        -        "@"
string   waive_reason                     WAIVE_REASON                     25       -        7        "@@"
char     waive_ind                        WAIVE_IND                        25       -        -        "@"
long     pSrvTpInpBufrowCount             PSRVTPINPBUFROWCOUNT             1        -        -        -1061109568
char     tuxSrvTp                         TUXSRVTP                         25       -        -        "@"
long     pNameAdrBufrowCount              PNAMEADRBUFROWCOUNT              1        -        -        -1061109568
char     link_mode                        LINK_MODE                        20       -        -        "@"
long     link_ban                         LINK_BAN                         20       -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  20       -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      20       -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      20       -        -        -1061109568
long     lnkReccustomer_id                LNKRECCUSTOMER_ID                20       -        -        -1061109568
long     lnkRecban                        LNKRECBAN                        20       -        -        -1061109568
string   lnkRecsubscriber_no              LNKRECSUBSCRIBER_NO              20       -        21       "@@"
char     link_type                        LINK_TYPE                        20       -        -        "@"
string   lnkReceffective_date             LNKRECEFFECTIVE_DATE             20       -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   20       -        -        -1061109568
char     billing_ind                      BILLING_IND                      20       -        -        "@"
char     mailing_ind                      MAILING_IND                      20       -        -        "@"
char     user_ind                         USER_IND                         20       -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 20       -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 20       -        -        "@"
char     link_user_ind                    LINK_USER_IND                    20       -        -        "@"
char     nm_mode                          NM_MODE                          20       -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       20       -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   20       -        9        "@@"
string   NameRecrowid                     NAMERECROWID                     20       -        19       "@@"
long     name_id                          NAME_ID                          20       -        -        -1061109568
string   NameRecsys_creation_date         NAMERECSYS_CREATION_DATE         20       -        15       "@@"
string   NameRecsys_update_date           NAMERECSYS_UPDATE_DATE           20       -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               20       -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            20       -        7        "@@"
string   NameRecdl_service_code           NAMERECDL_SERVICE_CODE           20       -        6        "@@"
short    NameRecdl_update_stamp           NAMERECDL_UPDATE_STAMP           20       -        -        -16192
string   control_name                     CONTROL_NAME                     20       -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               20       -        61       "@@"
string   first_name                       FIRST_NAME                       20       -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 20       -        61       "@@"
char     name_format                      NAME_FORMAT                      20       -        -        "@"
string   birth_date                       BIRTH_DATE                       20       -        9        "@@"
string   identify                         IDENTIFY                         20       -        21       "@@"
string   id_type                          ID_TYPE                          20       -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      20       -        21       "@@"
double   kob                              KOB                              20       -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   20       -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    20       -        11       "@@"
short    NameRecconv_run_no               NAMERECCONV_RUN_NO               20       -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            20       -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   20       -        4        "@@"
char     gender                           GENDER                           20       -        -        "@"
string   marital_status                   MARITAL_STATUS                   20       -        5        "@@"
char     role_ind                         ROLE_IND                         20       -        -        "@"
char     adr_mode                         ADR_MODE                         20       -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      20       -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  20       -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  20       -        19       "@@"
long     address_id                       ADDRESS_ID                       20       -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      20       -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        20       -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            20       -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         20       -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        20       -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        20       -        -        -16192
char     adr_type                         ADR_TYPE                         20       -        -        "@"
char     adr_status                       ADR_STATUS                       20       -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  20       -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 20       -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   20       -        101      "@@"
string   adr_city                         ADR_CITY                         20       -        40       "@@"
string   adr_zip                          ADR_ZIP                          20       -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     20       -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  20       -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    20       -        3        "@@"
string   adr_pob                          ADR_POB                          20       -        11       "@@"
string   adr_country                      ADR_COUNTRY                      20       -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 20       -        3        "@@"
string   adr_story                        ADR_STORY                        20       -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      20       -        5        "@@"
string   adr_email                        ADR_EMAIL                        20       -        151      "@@"
string   since_date                       SINCE_DATE                       20       -        9        "@@"
string   adr_district                     ADR_DISTRICT                     20       -        41       "@@"
char     co_ind                           CO_IND                           20       -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            20       -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               20       -        5        "@@"
string   county_code                      COUNTY_CODE                      20       -        3        "@@"
string   community_name                   COMMUNITY_NAME                   20       -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      20       -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   20       -        61       "@@"
string   adr_p1                           ADR_P1                           20       -        61       "@@"
string   adr_p2                           ADR_P2                           20       -        61       "@@"
string   adr_p3                           ADR_P3                           20       -        61       "@@"
string   adr_p4                           ADR_P4                           20       -        61       "@@"
string   adr_p5                           ADR_P5                           20       -        61       "@@"
string   adr_p6                           ADR_P6                           20       -        61       "@@"
string   adr_p7                           ADR_P7                           20       -        61       "@@"
string   adr_p8                           ADR_P8                           20       -        61       "@@"
string   adr_p9                           ADR_P9                           20       -        61       "@@"
string   adr_p10                          ADR_P10                          20       -        61       "@@"
long     pEsnBufrowCount                  PESNBUFROWCOUNT                  1        -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     50       -        21       "@@"
long     phd_seq_no                       PHD_SEQ_NO                       50       -        -        -1061109568
short    equipment_level                  EQUIPMENT_LEVEL                  50       -        -        -16192
string   imsi                             IMSI                             50       -        16       "@@"
string   phyDevArrayexpiration_date       PHYDEVARRAYEXPIRATION_DATE       50       -        15       "@@"
string   phyDevArrayeffective_date        PHYDEVARRAYEFFECTIVE_DATE        50       -        15       "@@"
string   ownership_code                   OWNERSHIP_CODE                   50       -        3        "@@"
char     sw_state_ind                     SW_STATE_IND                     50       -        -        "@"
string   last_sw_actv_date                LAST_SW_ACTV_DATE                50       -        9        "@@"
char     next_actv_code                   NEXT_ACTV_CODE                   50       -        -        "@"
string   next_actv_date                   NEXT_ACTV_DATE                   50       -        9        "@@"
string   next_actv_issue_dt               NEXT_ACTV_ISSUE_DT               50       -        9        "@@"
char     device_type                      DEVICE_TYPE                      50       -        -        "@"
char     esn_mode                         ESN_MODE                         50       -        -        "@"
string   item_id                          ITEM_ID                          50       -        16       "@@"
string   pool                             POOL                             50       -        3        "@@"
string   location_id                      LOCATION_ID                      50       -        5        "@@"
string   activity_code                    ACTIVITY_CODE                    50       -        5        "@@"
string   activity_date                    ACTIVITY_DATE                    50       -        15       "@@"
char     operation_status                 OPERATION_STATUS                 50       -        -        "@"
char     item_ownership                   ITEM_OWNERSHIP                   50       -        -        "@"
string   item_ownership_dt                ITEM_OWNERSHIP_DT                50       -        15       "@@"
char     curr_possession                  CURR_POSSESSION                  50       -        -        "@"
string   curr_possession_dt               CURR_POSSESSION_DT               50       -        15       "@@"
char     missing_ind                      MISSING_IND                      50       -        -        "@"
char     in_repair_ind                    IN_REPAIR_IND                    50       -        -        "@"
char     in_transit_ind                   IN_TRANSIT_IND                   50       -        -        "@"
char     comited_to_pos_ind               COMITED_TO_POS_IND               50       -        -        "@"
string   comited_date                     COMITED_DATE                     50       -        15       "@@"
string   activity_reason                  ACTIVITY_REASON                  50       -        4        "@@"
char     upgrade_ind                      UPGRADE_IND                      50       -        -        "@"
string   expected_rtrn_date               EXPECTED_RTRN_DATE               50       -        15       "@@"
string   police_report_no                 POLICE_REPORT_NO                 50       -        16       "@@"
string   police_report_date               POLICE_REPORT_DATE               50       -        15       "@@"
string   police_station                   POLICE_STATION                   50       -        31       "@@"
long     puk                              PUK                              50       -        -        -1061109568
long     puk2                             PUK2                             50       -        -        -1061109568
string   first_used_date                  FIRST_USED_DATE                  50       -        15       "@@"
char     sim_status                       SIM_STATUS                       50       -        -        "@"
char     suspend_ind                      SUSPEND_IND                      50       -        -        "@"
string   suspend_date                     SUSPEND_DATE                     50       -        15       "@@"
char     sent_to_auc_ind                  SENT_TO_AUC_IND                  50       -        -        "@"
string   hlr_cd                           HLR_CD                           50       -        4        "@@"
string   k4id                             K4ID                             50       -        41       "@@"
string   phyDevArraydealer_code           PHYDEVARRAYDEALER_CODE           50       -        6        "@@"
long     pSocFtrBufrowcount               PSOCFTRBUFROWCOUNT               1        -        -        -1061109568
string   pSocFtrBufrowid                  PSOCFTRBUFROWID                  200      -        19       "@@"
string   pSocFtrBufsoc                    PSOCFTRBUFSOC                    200      -        10       "@@"
string   pSocFtrBufsoc_effective_date     PSOCFTRBUFSOC_EFFECTIVE_DATE     200      -        9        "@@"
string   feature_code                     FEATURE_CODE                     200      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     200      -        7        "@@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               200      -        9        "@@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              200      -        9        "@@"
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 200      -        -        "@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 200      -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               200      -        -        -1061109568
char     ftr_mode                         FTR_MODE                         200      -        -        "@"
long     pSocFtrBufsoc_seq_no             PSOCFTRBUFSOC_SEQ_NO             200      -        -        -1061109568
char     ftr_sub_mode                     FTR_SUB_MODE                     200      -        -        "@"
string   ftr_add_param                    FTR_ADD_PARAM                    200      -        301      "@@"
string   feature_type                     FEATURE_TYPE                     200      -        4        "@@"
string   pSocFtrBufproduct_type           PSOCFTRBUFPRODUCT_TYPE           200      -        4        "@@"
long     pSocFtrBufcampaign_seq           PSOCFTRBUFCAMPAIGN_SEQ           200      -        -        -1061109568
string   ftr_special_telno                FTR_SPECIAL_TELNO                200      -        21       "@@"
char     switch_act_needed                SWITCH_ACT_NEEDED                200      -        -        "@"
string   switch_code                      SWITCH_CODE                      200      -        7        "@@"
char     msisdn_criteria                  MSISDN_CRITERIA                  200      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      200      -        4        "@@"
char     action_mode                      ACTION_MODE                      200      -        -        "@"
double   manual_rc_rate                   MANUAL_RC_RATE                   200      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               200      -        9        "@@"
long     pNpInfoBuffrowCount              PNPINFOBUFFROWCOUNT              1        -        -        -1061109568
string   NpNumInfoRecrowid                NPNUMINFORECROWID                500      -        19       "@@"
string   port_number                      PORT_NUMBER                      500      -        21       "@@"
string   NpNumInfoReceffective_date       NPNUMINFORECEFFECTIVE_DATE       500      -        15       "@@"
string   NpNumInfoRecsys_creation_date    NPNUMINFORECSYS_CREATION_DATE    500      -        15       "@@"
string   NpNumInfoRecsys_update_date      NPNUMINFORECSYS_UPDATE_DATE      500      -        15       "@@"
long     NpNumInfoRecoperator_id          NPNUMINFORECOPERATOR_ID          500      -        -        -1061109568
string   NpNumInfoRecapplication_id       NPNUMINFORECAPPLICATION_ID       500      -        7        "@@"
string   NpNumInfoRecdl_service_code      NPNUMINFORECDL_SERVICE_CODE      500      -        6        "@@"
short    NpNumInfoRecdl_update_stamp      NPNUMINFORECDL_UPDATE_STAMP      500      -        -        -16192
string   NpNumInfoRecexpiration_date      NPNUMINFORECEXPIRATION_DATE      500      -        15       "@@"
double   int_order_id                     INT_ORDER_ID                     500      -        -        -8577.505882352939807
string   org_customer_id                  ORG_CUSTOMER_ID                  500      -        61       "@@"
char     port_ind                         PORT_IND                         500      -        -        "@"
char     number_type                      NUMBER_TYPE                      500      -        -        "@"
string   port_request_date                PORT_REQUEST_DATE                500      -        15       "@@"
string   org_operator                     ORG_OPERATOR                     500      -        6        "@@"
long     NpNumInfoRecsubscriber_id        NPNUMINFORECSUBSCRIBER_ID        500      -        -        -1061109568
double   last_int_ord_id                  LAST_INT_ORD_ID                  500      -        -        -8577.505882352939807
char     function_port_ind                FUNCTION_PORT_IND                500      -        -        "@"
char     passive_ind                      PASSIVE_IND                      500      -        -        "@"
char     auto_confirm                     AUTO_CONFIRM                     500      -        -        "@"
string   temporary_msisdn                 TEMPORARY_MSISDN                 500      -        21       "@@"
char     handle_mode                      HANDLE_MODE                      500      -        -        "@"
char     send_ind                         SEND_IND                         500      -        -        "@"
string   ordid_str                        ORDID_STR                        500      -        21       "@@"
string   last_ordid_str                   LAST_ORDID_STR                   500      -        21       "@@"
string   icc                              ICC                              500      -        61       "@@"
string   customer_name                    CUSTOMER_NAME                    500      -        255      "@@"
string   NpInfoBuffcustomer_id            NPINFOBUFFCUSTOMER_ID            500      -        61       "@@"
string   service_provider                 SERVICE_PROVIDER                 500      -        6        "@@"
string   rsnCode                          RSNCODE                          1        -        5        "@@"
END

VIEW vo_csApiBan
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     pNameAdrBufrowCount              PNAMEADRBUFROWCOUNT              1        -        -        -1061109568
char     link_mode                        LINK_MODE                        20       -        -        "@"
long     link_ban                         LINK_BAN                         20       -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  20       -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      20       -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      20       -        -        -1061109568
long     lnkReccustomer_id                LNKRECCUSTOMER_ID                20       -        -        -1061109568
long     lnkRecban                        LNKRECBAN                        20       -        -        -1061109568
string   lnkRecsubscriber_no              LNKRECSUBSCRIBER_NO              20       -        21       "@@"
char     link_type                        LINK_TYPE                        20       -        -        "@"
string   lnkReceffective_date             LNKRECEFFECTIVE_DATE             20       -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   20       -        -        -1061109568
char     billing_ind                      BILLING_IND                      20       -        -        "@"
char     mailing_ind                      MAILING_IND                      20       -        -        "@"
char     user_ind                         USER_IND                         20       -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 20       -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 20       -        -        "@"
char     link_user_ind                    LINK_USER_IND                    20       -        -        "@"
char     nm_mode                          NM_MODE                          20       -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       20       -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   20       -        9        "@@"
string   NameRecrowid                     NAMERECROWID                     20       -        19       "@@"
long     name_id                          NAME_ID                          20       -        -        -1061109568
string   NameRecsys_creation_date         NAMERECSYS_CREATION_DATE         20       -        15       "@@"
string   NameRecsys_update_date           NAMERECSYS_UPDATE_DATE           20       -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               20       -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            20       -        7        "@@"
string   NameRecdl_service_code           NAMERECDL_SERVICE_CODE           20       -        6        "@@"
short    NameRecdl_update_stamp           NAMERECDL_UPDATE_STAMP           20       -        -        -16192
string   control_name                     CONTROL_NAME                     20       -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               20       -        61       "@@"
string   first_name                       FIRST_NAME                       20       -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 20       -        61       "@@"
char     name_format                      NAME_FORMAT                      20       -        -        "@"
string   birth_date                       BIRTH_DATE                       20       -        9        "@@"
string   identify                         IDENTIFY                         20       -        21       "@@"
string   id_type                          ID_TYPE                          20       -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      20       -        21       "@@"
double   kob                              KOB                              20       -        -        -8577.505882352939807
string   middle_initial                   MIDDLE_INITIAL                   20       -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    20       -        11       "@@"
short    NameRecconv_run_no               NAMERECCONV_RUN_NO               20       -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            20       -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   20       -        4        "@@"
char     gender                           GENDER                           20       -        -        "@"
string   marital_status                   MARITAL_STATUS                   20       -        5        "@@"
char     role_ind                         ROLE_IND                         20       -        -        "@"
char     adr_mode                         ADR_MODE                         20       -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      20       -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  20       -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  20       -        19       "@@"
long     address_id                       ADDRESS_ID                       20       -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      20       -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        20       -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            20       -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         20       -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        20       -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        20       -        -        -16192
char     adr_type                         ADR_TYPE                         20       -        -        "@"
char     adr_status                       ADR_STATUS                       20       -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  20       -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 20       -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   20       -        101      "@@"
string   adr_city                         ADR_CITY                         20       -        40       "@@"
string   adr_zip                          ADR_ZIP                          20       -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     20       -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  20       -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    20       -        3        "@@"
string   adr_pob                          ADR_POB                          20       -        11       "@@"
string   adr_country                      ADR_COUNTRY                      20       -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 20       -        3        "@@"
string   adr_story                        ADR_STORY                        20       -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      20       -        5        "@@"
string   adr_email                        ADR_EMAIL                        20       -        151      "@@"
string   since_date                       SINCE_DATE                       20       -        9        "@@"
string   adr_district                     ADR_DISTRICT                     20       -        41       "@@"
char     co_ind                           CO_IND                           20       -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            20       -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               20       -        5        "@@"
string   county_code                      COUNTY_CODE                      20       -        3        "@@"
string   community_name                   COMMUNITY_NAME                   20       -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      20       -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   20       -        61       "@@"
string   adr_p1                           ADR_P1                           20       -        61       "@@"
string   adr_p2                           ADR_P2                           20       -        61       "@@"
string   adr_p3                           ADR_P3                           20       -        61       "@@"
string   adr_p4                           ADR_P4                           20       -        61       "@@"
string   adr_p5                           ADR_P5                           20       -        61       "@@"
string   adr_p6                           ADR_P6                           20       -        61       "@@"
string   adr_p7                           ADR_P7                           20       -        61       "@@"
string   adr_p8                           ADR_P8                           20       -        61       "@@"
string   adr_p9                           ADR_P9                           20       -        61       "@@"
string   adr_p10                          ADR_P10                          20       -        61       "@@"
long     pEsnBufrowCount                  PESNBUFROWCOUNT                  1        -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     50       -        21       "@@"
long     phd_seq_no                       PHD_SEQ_NO                       50       -        -        -1061109568
short    equipment_level                  EQUIPMENT_LEVEL                  50       -        -        -16192
string   imsi                             IMSI                             50       -        16       "@@"
string   phyDevArrayexpiration_date       PHYDEVARRAYEXPIRATION_DATE       50       -        15       "@@"
string   phyDevArrayeffective_date        PHYDEVARRAYEFFECTIVE_DATE        50       -        15       "@@"
string   ownership_code                   OWNERSHIP_CODE                   50       -        3        "@@"
char     sw_state_ind                     SW_STATE_IND                     50       -        -        "@"
string   last_sw_actv_date                LAST_SW_ACTV_DATE                50       -        9        "@@"
char     next_actv_code                   NEXT_ACTV_CODE                   50       -        -        "@"
string   next_actv_date                   NEXT_ACTV_DATE                   50       -        9        "@@"
string   next_actv_issue_dt               NEXT_ACTV_ISSUE_DT               50       -        9        "@@"
char     device_type                      DEVICE_TYPE                      50       -        -        "@"
char     esn_mode                         ESN_MODE                         50       -        -        "@"
string   item_id                          ITEM_ID                          50       -        16       "@@"
string   pool                             POOL                             50       -        3        "@@"
string   location_id                      LOCATION_ID                      50       -        5        "@@"
string   activity_code                    ACTIVITY_CODE                    50       -        5        "@@"
string   activity_date                    ACTIVITY_DATE                    50       -        15       "@@"
char     operation_status                 OPERATION_STATUS                 50       -        -        "@"
char     item_ownership                   ITEM_OWNERSHIP                   50       -        -        "@"
string   item_ownership_dt                ITEM_OWNERSHIP_DT                50       -        15       "@@"
char     curr_possession                  CURR_POSSESSION                  50       -        -        "@"
string   curr_possession_dt               CURR_POSSESSION_DT               50       -        15       "@@"
char     missing_ind                      MISSING_IND                      50       -        -        "@"
char     in_repair_ind                    IN_REPAIR_IND                    50       -        -        "@"
char     in_transit_ind                   IN_TRANSIT_IND                   50       -        -        "@"
char     comited_to_pos_ind               COMITED_TO_POS_IND               50       -        -        "@"
string   comited_date                     COMITED_DATE                     50       -        15       "@@"
string   activity_reason                  ACTIVITY_REASON                  50       -        4        "@@"
char     upgrade_ind                      UPGRADE_IND                      50       -        -        "@"
string   expected_rtrn_date               EXPECTED_RTRN_DATE               50       -        15       "@@"
string   police_report_no                 POLICE_REPORT_NO                 50       -        16       "@@"
string   police_report_date               POLICE_REPORT_DATE               50       -        15       "@@"
string   police_station                   POLICE_STATION                   50       -        31       "@@"
long     puk                              PUK                              50       -        -        -1061109568
long     puk2                             PUK2                             50       -        -        -1061109568
string   first_used_date                  FIRST_USED_DATE                  50       -        15       "@@"
char     sim_status                       SIM_STATUS                       50       -        -        "@"
char     suspend_ind                      SUSPEND_IND                      50       -        -        "@"
string   suspend_date                     SUSPEND_DATE                     50       -        15       "@@"
char     sent_to_auc_ind                  SENT_TO_AUC_IND                  50       -        -        "@"
string   hlr_cd                           HLR_CD                           50       -        4        "@@"
string   k4id                             K4ID                             50       -        41       "@@"
string   phyDevArraydealer_code           PHYDEVARRAYDEALER_CODE           50       -        6        "@@"
long     pSocFtrBufrowcount               PSOCFTRBUFROWCOUNT               1        -        -        -1061109568
string   pSocFtrBufrowid                  PSOCFTRBUFROWID                  200      -        19       "@@"
string   pSocFtrBufsoc                    PSOCFTRBUFSOC                    200      -        10       "@@"
string   pSocFtrBufsoc_effective_date     PSOCFTRBUFSOC_EFFECTIVE_DATE     200      -        9        "@@"
string   feature_code                     FEATURE_CODE                     200      -        7        "@@"
string   mps_ftr_code                     MPS_FTR_CODE                     200      -        7        "@@"
string   ftr_effective_date               FTR_EFFECTIVE_DATE               200      -        9        "@@"
string   ftr_expiration_date              FTR_EXPIRATION_DATE              200      -        9        "@@"
char     ftr_eff_rsn_code                 FTR_EFF_RSN_CODE                 200      -        -        "@"
char     ftr_exp_rsn_code                 FTR_EXP_RSN_CODE                 200      -        -        "@"
long     service_ftr_seq_no               SERVICE_FTR_SEQ_NO               200      -        -        -1061109568
char     ftr_mode                         FTR_MODE                         200      -        -        "@"
long     pSocFtrBufsoc_seq_no             PSOCFTRBUFSOC_SEQ_NO             200      -        -        -1061109568
char     ftr_sub_mode                     FTR_SUB_MODE                     200      -        -        "@"
string   ftr_add_param                    FTR_ADD_PARAM                    200      -        301      "@@"
string   feature_type                     FEATURE_TYPE                     200      -        4        "@@"
string   pSocFtrBufproduct_type           PSOCFTRBUFPRODUCT_TYPE           200      -        4        "@@"
long     pSocFtrBufcampaign_seq           PSOCFTRBUFCAMPAIGN_SEQ           200      -        -        -1061109568
string   ftr_special_telno                FTR_SPECIAL_TELNO                200      -        21       "@@"
char     switch_act_needed                SWITCH_ACT_NEEDED                200      -        -        "@"
string   switch_code                      SWITCH_CODE                      200      -        7        "@@"
char     msisdn_criteria                  MSISDN_CRITERIA                  200      -        -        "@"
string   tn_class_cd                      TN_CLASS_CD                      200      -        4        "@@"
char     action_mode                      ACTION_MODE                      200      -        -        "@"
double   manual_rc_rate                   MANUAL_RC_RATE                   200      -        -        -8577.505882352939807
string   manual_rc_exp_date               MANUAL_RC_EXP_DATE               200      -        9        "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   msisdn                           MSISDN                           100      -        21       "@@"
string   nl                               NL                               100      -        4        "@@"
long     code                             CODE                             100      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    100      -        21       "@@"
string   gsmbuffeature_code               GSMBUFFEATURE_CODE               100      -        7        "@@"
string   errorDesc                        ERRORDESC                        1        -        2001     "@@"
long     pNpInfoBuffrowCount              PNPINFOBUFFROWCOUNT              1        -        -        -1061109568
string   NpNumInfoRecrowid                NPNUMINFORECROWID                500      -        19       "@@"
string   port_number                      PORT_NUMBER                      500      -        21       "@@"
string   NpNumInfoReceffective_date       NPNUMINFORECEFFECTIVE_DATE       500      -        15       "@@"
string   NpNumInfoRecsys_creation_date    NPNUMINFORECSYS_CREATION_DATE    500      -        15       "@@"
string   NpNumInfoRecsys_update_date      NPNUMINFORECSYS_UPDATE_DATE      500      -        15       "@@"
long     NpNumInfoRecoperator_id          NPNUMINFORECOPERATOR_ID          500      -        -        -1061109568
string   NpNumInfoRecapplication_id       NPNUMINFORECAPPLICATION_ID       500      -        7        "@@"
string   NpNumInfoRecdl_service_code      NPNUMINFORECDL_SERVICE_CODE      500      -        6        "@@"
short    NpNumInfoRecdl_update_stamp      NPNUMINFORECDL_UPDATE_STAMP      500      -        -        -16192
string   NpNumInfoRecexpiration_date      NPNUMINFORECEXPIRATION_DATE      500      -        15       "@@"
double   int_order_id                     INT_ORDER_ID                     500      -        -        -8577.505882352939807
string   org_customer_id                  ORG_CUSTOMER_ID                  500      -        61       "@@"
char     port_ind                         PORT_IND                         500      -        -        "@"
char     number_type                      NUMBER_TYPE                      500      -        -        "@"
string   port_request_date                PORT_REQUEST_DATE                500      -        15       "@@"
string   org_operator                     ORG_OPERATOR                     500      -        6        "@@"
long     NpNumInfoRecsubscriber_id        NPNUMINFORECSUBSCRIBER_ID        500      -        -        -1061109568
double   last_int_ord_id                  LAST_INT_ORD_ID                  500      -        -        -8577.505882352939807
char     function_port_ind                FUNCTION_PORT_IND                500      -        -        "@"
char     passive_ind                      PASSIVE_IND                      500      -        -        "@"
char     auto_confirm                     AUTO_CONFIRM                     500      -        -        "@"
string   temporary_msisdn                 TEMPORARY_MSISDN                 500      -        21       "@@"
char     handle_mode                      HANDLE_MODE                      500      -        -        "@"
char     send_ind                         SEND_IND                         500      -        -        "@"
string   ordid_str                        ORDID_STR                        500      -        21       "@@"
string   last_ordid_str                   LAST_ORDID_STR                   500      -        21       "@@"
string   icc                              ICC                              500      -        61       "@@"
string   customer_name                    CUSTOMER_NAME                    500      -        255      "@@"
string   NpInfoBuffcustomer_id            NPINFOBUFFCUSTOMER_ID            500      -        61       "@@"
string   service_provider                 SERVICE_PROVIDER                 500      -        6        "@@"
END


