VIEW vi_csLsNpTrx
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   port_number                      PORT_NUMBER                      1        -        21       "@@"
long     user_id                          USER_ID                          1        -        -        -1061109568
short    np_trx_code                      NP_TRX_CODE                      1        -        -        -16192
double   int_order_id                     INT_ORDER_ID                     1        -        -        -8577.505882352939800
double   ext_order_id                     EXT_ORDER_ID                     1        -        -        -8577.505882352939800
char     trx_status                       TRX_STATUS                       1        -        -        "@"
char     order_status                     ORDER_STATUS                     1        -        -        "@"
string   from_date                        FROM_DATE                        1        -        9        "@@"
string   to_date                          TO_DATE                          1        -        9        "@@"
string   initi_order_tp                   INITI_ORDER_TP                   1        -        6        "@@"
long     page                             PAGE                             1        -        -        -1061109568
long     buffer_size                      BUFFER_SIZE                      1        -        -        -1061109568
string   ordid_str                        ORDID_STR                        1        -        21       "@@"
string   originating_number               ORIGINATING_NUMBER               1        -        255      "@@"
string   temporary_msisdn                 TEMPORARY_MSISDN                 1        -        21       "@@"
END

VIEW vo_csLsNpTrx
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   trx_code                         TRX_CODE                         1        -        4        "@@"
long     totalCount                       TOTALCOUNT                       1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            200      -        19       "@@"
short    NpTrxDetBuftrx_code              NPTRXDETBUFTRX_CODE              200      -        -        -16192
double   int_order_id                     INT_ORDER_ID                     200      -        -        -8577.505882352939800
string   trx_source                       TRX_SOURCE                       200      -        4        "@@"
string   sys_creation_date                SYS_CREATION_DATE                200      -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  200      -        15       "@@"
long     operator_id                      OPERATOR_ID                      200      -        -        -1061109568
string   application_id                   APPLICATION_ID                   200      -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  200      -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  200      -        -        -16192
string   ext_unique_id                    EXT_UNIQUE_ID                    200      -        13       "@@"
long     int_trx_seq                      INT_TRX_SEQ                      200      -        -        -1061109568
long     initi_order_seq                  INITI_ORDER_SEQ                  200      -        -        -1061109568
string   cont_category                    CONT_CATEGORY                    200      -        4        "@@"
double   ext_order_id                     EXT_ORDER_ID                     200      -        -        -8577.505882352939800
string   trx_datetime                     TRX_DATETIME                     200      -        15       "@@"
char     trx_status                       TRX_STATUS                       200      -        -        "@"
string   trx_sts_date                     TRX_STS_DATE                     200      -        15       "@@"
string   customer_name                    CUSTOMER_NAME                    200      -        255      "@@"
string   NpTrxDetBufcustomer_id           NPTRXDETBUFCUSTOMER_ID           200      -        61       "@@"
string   np_product_type                  NP_PRODUCT_TYPE                  200      -        255      "@@"
string   new_num_type                     NEW_NUM_TYPE                     200      -        255      "@@"
string   main_number                      MAIN_NUMBER                      200      -        21       "@@"
string   additional_number_1              ADDITIONAL_NUMBER_1              200      -        255      "@@"
string   additional_number_2              ADDITIONAL_NUMBER_2              200      -        255      "@@"
string   additional_number_3              ADDITIONAL_NUMBER_3              200      -        255      "@@"
string   additional_number_4              ADDITIONAL_NUMBER_4              200      -        255      "@@"
string   additional_number_5              ADDITIONAL_NUMBER_5              200      -        255      "@@"
string   additional_number_6              ADDITIONAL_NUMBER_6              200      -        255      "@@"
string   additional_number_7              ADDITIONAL_NUMBER_7              200      -        255      "@@"
string   additional_number_8              ADDITIONAL_NUMBER_8              200      -        255      "@@"
string   additional_number_9              ADDITIONAL_NUMBER_9              200      -        255      "@@"
string   additional_number_10             ADDITIONAL_NUMBER_10             200      -        255      "@@"
string   primary_num                      PRIMARY_NUM                      200      -        21       "@@"
string   request_exec_date                REQUEST_EXEC_DATE                200      -        15       "@@"
string   conf_exec_date                   CONF_EXEC_DATE                   200      -        15       "@@"
string   conf_status                      CONF_STATUS                      200      -        4        "@@"
long     error_uniq_id                    ERROR_UNIQ_ID                    200      -        -        -1061109568
long     series_uniq_id                   SERIES_UNIQ_ID                   200      -        -        -1061109568
string   curr_serv_oper                   CURR_SERV_OPER                   200      -        6        "@@"
string   recip_serv_oper                  RECIP_SERV_OPER                  200      -        6        "@@"
string   curr_net_oper                    CURR_NET_OPER                    200      -        6        "@@"
string   recip_net_oper                   RECIP_NET_OPER                   200      -        6        "@@"
string   initi_order_tp                   INITI_ORDER_TP                   200      -        6        "@@"
string   text_comment                     TEXT_COMMENT                     200      -        256      "@@"
char     delay_ind                        DELAY_IND                        200      -        -        "@"
string   file_name                        FILE_NAME                        200      -        256      "@@"
string   municipality                     MUNICIPALITY                     200      -        4        "@@"
string   ext_trx_sts                      EXT_TRX_STS                      200      -        11       "@@"
string   last_trx_sts                     LAST_TRX_STS                     200      -        11       "@@"
string   initi_timestamp                  INITI_TIMESTAMP                  200      -        15       "@@"
string   other_operator                   OTHER_OPERATOR                   200      -        6        "@@"
string   point_of_connection              POINT_OF_CONNECTION              200      -        61       "@@"
char     range_upd_tp                     RANGE_UPD_TP                     200      -        -        "@"
string   csnpspc                          CSNPSPC                          200      -        7        "@@"
string   routing_info                     ROUTING_INFO                     200      -        9        "@@"
string   rating_tp                        RATING_TP                        200      -        5        "@@"
char     man_aut                          MAN_AUT                          200      -        -        "@"
string   term_conf_date                   TERM_CONF_DATE                   200      -        9        "@@"
string   service_provider                 SERVICE_PROVIDER                 200      -        6        "@@"
string   np_card_sts                      NP_CARD_STS                      200      -        13       "@@"
string   charging_info                    CHARGING_INFO                    200      -        9        "@@"
string   directory_info                   DIRECTORY_INFO                   200      -        14       "@@"
char     num_ported_ind                   NUM_PORTED_IND                   200      -        -        "@"
string   porting_case                     PORTING_CASE                     200      -        61       "@@"
string   porting_tp                       PORTING_TP                       200      -        61       "@@"
string   range                            RANGE                            200      -        18       "@@"
string   series_count                     SERIES_COUNT                     200      -        4        "@@"
string   eidnodsign                       EIDNODSIGN                       200      -        7        "@@"
string   eidntyp                          EIDNTYP                          200      -        5        "@@"
string   eidntypnumb                      EIDNTYPNUMB                      200      -        5        "@@"
string   neidnodsign                      NEIDNODSIGN                      200      -        7        "@@"
string   neidntyp                         NEIDNTYP                         200      -        5        "@@"
string   neidntypnumb                     NEIDNTYPNUMB                     200      -        5        "@@"
string   contact_name                     CONTACT_NAME                     200      -        255      "@@"
string   contact_number                   CONTACT_NUMBER                   200      -        255      "@@"
string   contact_email                    CONTACT_EMAIL                    200      -        255      "@@"
string   error_contact_name               ERROR_CONTACT_NAME               200      -        255      "@@"
string   error_contact_number             ERROR_CONTACT_NUMBER             200      -        255      "@@"
string   error_contact_email              ERROR_CONTACT_EMAIL              200      -        255      "@@"
string   text_1                           TEXT_1                           200      -        255      "@@"
string   text_2                           TEXT_2                           200      -        255      "@@"
string   text_3                           TEXT_3                           200      -        255      "@@"
string   text_4                           TEXT_4                           200      -        255      "@@"
string   text_5                           TEXT_5                           200      -        255      "@@"
string   text_6                           TEXT_6                           200      -        255      "@@"
string   text_7                           TEXT_7                           200      -        255      "@@"
string   text_8                           TEXT_8                           200      -        255      "@@"
string   text_9                           TEXT_9                           200      -        255      "@@"
string   text_10                          TEXT_10                          200      -        255      "@@"
string   rpsp                             RPSP                             200      -        255      "@@"
string   trx_sent_datetime                TRX_SENT_DATETIME                200      -        15       "@@"
string   originating_number               ORIGINATING_NUMBER               200      -        255      "@@"
string   icc                              ICC                              200      -        61       "@@"
char     coordination_ind                 COORDINATION_IND                 200      -        -        "@"
short    port_ended                       PORT_ENDED                       200      -        -        -16192
short    port_ended_main                  PORT_ENDED_MAIN                  200      -        -        -16192
short    port_ended_additional1           PORT_ENDED_ADDITIONAL1           200      -        -        -16192
short    port_ended_additional2           PORT_ENDED_ADDITIONAL2           200      -        -        -16192
short    port_ended_additional3           PORT_ENDED_ADDITIONAL3           200      -        -        -16192
short    port_ended_additional4           PORT_ENDED_ADDITIONAL4           200      -        -        -16192
short    port_ended_additional5           PORT_ENDED_ADDITIONAL5           200      -        -        -16192
short    port_ended_additional6           PORT_ENDED_ADDITIONAL6           200      -        -        -16192
short    port_ended_additional7           PORT_ENDED_ADDITIONAL7           200      -        -        -16192
short    port_ended_additional8           PORT_ENDED_ADDITIONAL8           200      -        -        -16192
short    port_ended_additional9           PORT_ENDED_ADDITIONAL9           200      -        -        -16192
short    port_ended_additional10          PORT_ENDED_ADDITIONAL10          200      -        -        -16192
string   dtsp                             DTSP                             200      -        4        "@@"
string   rtsp                             RTSP                             200      -        4        "@@"
string   ordid_str_buf                    ORDID_STR_BUF                    200      -        21       "@@"
long     pNpOrdBufrowCount                PNPORDBUFROWCOUNT                1        -        -        -1061109568
string   NpOrdDatRecrowid                 NPORDDATRECROWID                 50       -        19       "@@"
double   NpOrdDatRecint_order_id          NPORDDATRECINT_ORDER_ID          50       -        -        -8577.505882352939800
string   NpOrdDatRecsys_creation_date     NPORDDATRECSYS_CREATION_DATE     50       -        15       "@@"
string   NpOrdDatRecsys_update_date       NPORDDATRECSYS_UPDATE_DATE       50       -        15       "@@"
long     NpOrdDatRecoperator_id           NPORDDATRECOPERATOR_ID           50       -        -        -1061109568
string   NpOrdDatRecapplication_id        NPORDDATRECAPPLICATION_ID        50       -        7        "@@"
string   NpOrdDatRecdl_service_code       NPORDDATRECDL_SERVICE_CODE       50       -        6        "@@"
short    NpOrdDatRecdl_update_stamp       NPORDDATRECDL_UPDATE_STAMP       50       -        -        -16192
char     order_status                     ORDER_STATUS                     50       -        -        "@"
string   last_sts_date                    LAST_STS_DATE                    50       -        9        "@@"
double   ord_ext_id                       ORD_EXT_ID                       50       -        -        -8577.505882352939800
string   ordid_str                        ORDID_STR                        50       -        21       "@@"
string   temporary_msisdn                 TEMPORARY_MSISDN                 50       -        21       "@@"
long     pNpErrBufrowCount                PNPERRBUFROWCOUNT                1        -        -        -1061109568
string   NpTrxErrBufrowid                 NPTRXERRBUFROWID                 500      -        19       "@@"
long     NpTrxErrBuferror_uniq_id         NPTRXERRBUFERROR_UNIQ_ID         500      -        -        -1061109568
long     rej_err_seq                      REJ_ERR_SEQ                      500      -        -        -1061109568
string   NpTrxErrBufsys_creation_date     NPTRXERRBUFSYS_CREATION_DATE     500      -        15       "@@"
string   NpTrxErrBufsys_update_date       NPTRXERRBUFSYS_UPDATE_DATE       500      -        15       "@@"
long     NpTrxErrBufoperator_id           NPTRXERRBUFOPERATOR_ID           500      -        -        -1061109568
string   NpTrxErrBufapplication_id        NPTRXERRBUFAPPLICATION_ID        500      -        7        "@@"
string   NpTrxErrBufdl_service_code       NPTRXERRBUFDL_SERVICE_CODE       500      -        6        "@@"
short    NpTrxErrBufdl_update_stamp       NPTRXERRBUFDL_UPDATE_STAMP       500      -        -        -16192
long     rej_err_cd                       REJ_ERR_CD                       500      -        -        -1061109568
string   rej_err_txt                      REJ_ERR_TXT                      500      -        256      "@@"
string   err_field                        ERR_FIELD                        500      -        256      "@@"
long     dci_error_code                   DCI_ERROR_CODE                   1        -        -        -1061109568
short    dci_error_type                   DCI_ERROR_TYPE                   1        -        -        -16192
string   dci_error_text                   DCI_ERROR_TEXT                   1        -        81       "@@"
long     dci_row_count                    DCI_ROW_COUNT                    1        -        -        -1061109568
short    dci_more_rows                    DCI_MORE_ROWS                    1        -        -        -16192
long     pNpSerBufrowCount                PNPSERBUFROWCOUNT                1        -        -        -1061109568
string   NpTrxSerBufrowid                 NPTRXSERBUFROWID                 500      -        19       "@@"
long     NpTrxSerBufseries_uniq_id        NPTRXSERBUFSERIES_UNIQ_ID        500      -        -        -1061109568
string   series                           SERIES                           500      -        18       "@@"
string   NpTrxSerBufsys_creation_date     NPTRXSERBUFSYS_CREATION_DATE     500      -        15       "@@"
string   NpTrxSerBufsys_update_date       NPTRXSERBUFSYS_UPDATE_DATE       500      -        15       "@@"
long     NpTrxSerBufoperator_id           NPTRXSERBUFOPERATOR_ID           500      -        -        -1061109568
string   NpTrxSerBufapplication_id        NPTRXSERBUFAPPLICATION_ID        500      -        7        "@@"
string   NpTrxSerBufdl_service_code       NPTRXSERBUFDL_SERVICE_CODE       500      -        6        "@@"
short    NpTrxSerBufdl_update_stamp       NPTRXSERBUFDL_UPDATE_STAMP       500      -        -        -16192
END


VIEW vi_csCrNpTrx
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   trx_code                         TRX_CODE                         1        -        4        "@@"
string   rowid                            ROWID                            1        -        19       "@@"
short    pNpTrxNewRectrx_code             PNPTRXNEWRECTRX_CODE             1        -        -        -16192
double   int_order_id                     INT_ORDER_ID                     1        -        -        -8577.505882352939800
string   trx_source                       TRX_SOURCE                       1        -        4        "@@"
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     pNpTrxNewRecoperator_id          PNPTRXNEWRECOPERATOR_ID          1        -        -        -1061109568
string   pNpTrxNewRecapplication_id       PNPTRXNEWRECAPPLICATION_ID       1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   ext_unique_id                    EXT_UNIQUE_ID                    1        -        13       "@@"
long     int_trx_seq                      INT_TRX_SEQ                      1        -        -        -1061109568
long     initi_order_seq                  INITI_ORDER_SEQ                  1        -        -        -1061109568
string   cont_category                    CONT_CATEGORY                    1        -        4        "@@"
double   ext_order_id                     EXT_ORDER_ID                     1        -        -        -8577.505882352939800
string   trx_datetime                     TRX_DATETIME                     1        -        15       "@@"
char     trx_status                       TRX_STATUS                       1        -        -        "@"
string   trx_sts_date                     TRX_STS_DATE                     1        -        15       "@@"
string   customer_name                    CUSTOMER_NAME                    1        -        255      "@@"
string   pNpTrxNewReccustomer_id          PNPTRXNEWRECCUSTOMER_ID          1        -        61       "@@"
string   np_product_type                  NP_PRODUCT_TYPE                  1        -        255      "@@"
string   new_num_type                     NEW_NUM_TYPE                     1        -        255      "@@"
string   main_number                      MAIN_NUMBER                      1        -        21       "@@"
string   additional_number_1              ADDITIONAL_NUMBER_1              1        -        255      "@@"
string   additional_number_2              ADDITIONAL_NUMBER_2              1        -        255      "@@"
string   additional_number_3              ADDITIONAL_NUMBER_3              1        -        255      "@@"
string   additional_number_4              ADDITIONAL_NUMBER_4              1        -        255      "@@"
string   additional_number_5              ADDITIONAL_NUMBER_5              1        -        255      "@@"
string   additional_number_6              ADDITIONAL_NUMBER_6              1        -        255      "@@"
string   additional_number_7              ADDITIONAL_NUMBER_7              1        -        255      "@@"
string   additional_number_8              ADDITIONAL_NUMBER_8              1        -        255      "@@"
string   additional_number_9              ADDITIONAL_NUMBER_9              1        -        255      "@@"
string   additional_number_10             ADDITIONAL_NUMBER_10             1        -        255      "@@"
string   primary_num                      PRIMARY_NUM                      1        -        21       "@@"
string   request_exec_date                REQUEST_EXEC_DATE                1        -        15       "@@"
string   conf_exec_date                   CONF_EXEC_DATE                   1        -        15       "@@"
string   conf_status                      CONF_STATUS                      1        -        4        "@@"
long     error_uniq_id                    ERROR_UNIQ_ID                    1        -        -        -1061109568
long     series_uniq_id                   SERIES_UNIQ_ID                   1        -        -        -1061109568
string   curr_serv_oper                   CURR_SERV_OPER                   1        -        6        "@@"
string   recip_serv_oper                  RECIP_SERV_OPER                  1        -        6        "@@"
string   curr_net_oper                    CURR_NET_OPER                    1        -        6        "@@"
string   recip_net_oper                   RECIP_NET_OPER                   1        -        6        "@@"
string   initi_order_tp                   INITI_ORDER_TP                   1        -        6        "@@"
string   text_comment                     TEXT_COMMENT                     1        -        256      "@@"
char     delay_ind                        DELAY_IND                        1        -        -        "@"
string   file_name                        FILE_NAME                        1        -        256      "@@"
string   municipality                     MUNICIPALITY                     1        -        4        "@@"
string   ext_trx_sts                      EXT_TRX_STS                      1        -        11       "@@"
string   last_trx_sts                     LAST_TRX_STS                     1        -        11       "@@"
string   initi_timestamp                  INITI_TIMESTAMP                  1        -        15       "@@"
string   other_operator                   OTHER_OPERATOR                   1        -        6        "@@"
string   point_of_connection              POINT_OF_CONNECTION              1        -        61       "@@"
char     range_upd_tp                     RANGE_UPD_TP                     1        -        -        "@"
string   csnpspc                          CSNPSPC                          1        -        7        "@@"
string   routing_info                     ROUTING_INFO                     1        -        9        "@@"
string   rating_tp                        RATING_TP                        1        -        5        "@@"
char     man_aut                          MAN_AUT                          1        -        -        "@"
string   term_conf_date                   TERM_CONF_DATE                   1        -        9        "@@"
string   service_provider                 SERVICE_PROVIDER                 1        -        6        "@@"
string   np_card_sts                      NP_CARD_STS                      1        -        13       "@@"
string   charging_info                    CHARGING_INFO                    1        -        9        "@@"
string   directory_info                   DIRECTORY_INFO                   1        -        14       "@@"
char     num_ported_ind                   NUM_PORTED_IND                   1        -        -        "@"
string   porting_case                     PORTING_CASE                     1        -        61       "@@"
string   porting_tp                       PORTING_TP                       1        -        61       "@@"
string   range                            RANGE                            1        -        18       "@@"
string   series_count                     SERIES_COUNT                     1        -        4        "@@"
string   eidnodsign                       EIDNODSIGN                       1        -        7        "@@"
string   eidntyp                          EIDNTYP                          1        -        5        "@@"
string   eidntypnumb                      EIDNTYPNUMB                      1        -        5        "@@"
string   neidnodsign                      NEIDNODSIGN                      1        -        7        "@@"
string   neidntyp                         NEIDNTYP                         1        -        5        "@@"
string   neidntypnumb                     NEIDNTYPNUMB                     1        -        5        "@@"
string   contact_name                     CONTACT_NAME                     1        -        255      "@@"
string   contact_number                   CONTACT_NUMBER                   1        -        255      "@@"
string   contact_email                    CONTACT_EMAIL                    1        -        255      "@@"
string   error_contact_name               ERROR_CONTACT_NAME               1        -        255      "@@"
string   error_contact_number             ERROR_CONTACT_NUMBER             1        -        255      "@@"
string   error_contact_email              ERROR_CONTACT_EMAIL              1        -        255      "@@"
string   text_1                           TEXT_1                           1        -        255      "@@"
string   text_2                           TEXT_2                           1        -        255      "@@"
string   text_3                           TEXT_3                           1        -        255      "@@"
string   text_4                           TEXT_4                           1        -        255      "@@"
string   text_5                           TEXT_5                           1        -        255      "@@"
string   text_6                           TEXT_6                           1        -        255      "@@"
string   text_7                           TEXT_7                           1        -        255      "@@"
string   text_8                           TEXT_8                           1        -        255      "@@"
string   text_9                           TEXT_9                           1        -        255      "@@"
string   text_10                          TEXT_10                          1        -        255      "@@"
string   rpsp                             RPSP                             1        -        255      "@@"
string   trx_sent_datetime                TRX_SENT_DATETIME                1        -        15       "@@"
string   originating_number               ORIGINATING_NUMBER               1        -        255      "@@"
string   icc                              ICC                              1        -        61       "@@"
char     coordination_ind                 COORDINATION_IND                 1        -        -        "@"
short    port_ended                       PORT_ENDED                       1        -        -        -16192
short    port_ended_main                  PORT_ENDED_MAIN                  1        -        -        -16192
short    port_ended_additional1           PORT_ENDED_ADDITIONAL1           1        -        -        -16192
short    port_ended_additional2           PORT_ENDED_ADDITIONAL2           1        -        -        -16192
short    port_ended_additional3           PORT_ENDED_ADDITIONAL3           1        -        -        -16192
short    port_ended_additional4           PORT_ENDED_ADDITIONAL4           1        -        -        -16192
short    port_ended_additional5           PORT_ENDED_ADDITIONAL5           1        -        -        -16192
short    port_ended_additional6           PORT_ENDED_ADDITIONAL6           1        -        -        -16192
short    port_ended_additional7           PORT_ENDED_ADDITIONAL7           1        -        -        -16192
short    port_ended_additional8           PORT_ENDED_ADDITIONAL8           1        -        -        -16192
short    port_ended_additional9           PORT_ENDED_ADDITIONAL9           1        -        -        -16192
short    port_ended_additional10          PORT_ENDED_ADDITIONAL10          1        -        -        -16192
string   dtsp                             DTSP                             1        -        4        "@@"
string   rtsp                             RTSP                             1        -        4        "@@"
string   pNpTrxOrdRecrowid                PNPTRXORDRECROWID                1        -        19       "@@"
double   pNpTrxOrdRecint_order_id         PNPTRXORDRECINT_ORDER_ID         1        -        -        -8577.505882352939800
string   pNpTrxOrdRecsys_creation_date    PNPTRXORDRECSYS_CREATION_DATE    1        -        15       "@@"
string   pNpTrxOrdRecsys_update_date      PNPTRXORDRECSYS_UPDATE_DATE      1        -        15       "@@"
long     pNpTrxOrdRecoperator_id          PNPTRXORDRECOPERATOR_ID          1        -        -        -1061109568
string   pNpTrxOrdRecapplication_id       PNPTRXORDRECAPPLICATION_ID       1        -        7        "@@"
string   pNpTrxOrdRecdl_service_code      PNPTRXORDRECDL_SERVICE_CODE      1        -        6        "@@"
short    pNpTrxOrdRecdl_update_stamp      PNPTRXORDRECDL_UPDATE_STAMP      1        -        -        -16192
char     order_status                     ORDER_STATUS                     1        -        -        "@"
string   last_sts_date                    LAST_STS_DATE                    1        -        9        "@@"
string   ordid_str                        ORDID_STR                        1        -        21       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   NpTrxErrBufrowid                 NPTRXERRBUFROWID                 500      -        19       "@@"
long     NpTrxErrBuferror_uniq_id         NPTRXERRBUFERROR_UNIQ_ID         500      -        -        -1061109568
long     rej_err_seq                      REJ_ERR_SEQ                      500      -        -        -1061109568
string   NpTrxErrBufsys_creation_date     NPTRXERRBUFSYS_CREATION_DATE     500      -        15       "@@"
string   NpTrxErrBufsys_update_date       NPTRXERRBUFSYS_UPDATE_DATE       500      -        15       "@@"
long     NpTrxErrBufoperator_id           NPTRXERRBUFOPERATOR_ID           500      -        -        -1061109568
string   NpTrxErrBufapplication_id        NPTRXERRBUFAPPLICATION_ID        500      -        7        "@@"
string   NpTrxErrBufdl_service_code       NPTRXERRBUFDL_SERVICE_CODE       500      -        6        "@@"
short    NpTrxErrBufdl_update_stamp       NPTRXERRBUFDL_UPDATE_STAMP       500      -        -        -16192
long     rej_err_cd                       REJ_ERR_CD                       500      -        -        -1061109568
string   rej_err_txt                      REJ_ERR_TXT                      500      -        256      "@@"
string   err_field                        ERR_FIELD                        500      -        256      "@@"
END

VIEW vo_csCrNpTrx
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_csCrNpInfo
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
double   ext_order_id                     EXT_ORDER_ID                     1        -        -        -8577.505882352939800
END

VIEW vo_csCrNpInfo
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_csGtNpRlsSub
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   primary_number                   PRIMARY_NUMBER                   1        -        21       "@@"
END

VIEW vo_csGtNpRlsSub
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
long     ban                              BAN                              1        -        -        -1061109568
char     ban_status                       BAN_STATUS                       1        -        -        "@"
END


VIEW vi_csCrNpCncl
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   trx_code                         TRX_CODE                         1        -        4        "@@"
string   rowid                            ROWID                            1        -        19       "@@"
short    pNpTrxNewRectrx_code             PNPTRXNEWRECTRX_CODE             1        -        -        -16192
double   int_order_id                     INT_ORDER_ID                     1        -        -        -8577.505882352939800
string   trx_source                       TRX_SOURCE                       1        -        4        "@@"
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     pNpTrxNewRecoperator_id          PNPTRXNEWRECOPERATOR_ID          1        -        -        -1061109568
string   pNpTrxNewRecapplication_id       PNPTRXNEWRECAPPLICATION_ID       1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   ext_unique_id                    EXT_UNIQUE_ID                    1        -        13       "@@"
long     int_trx_seq                      INT_TRX_SEQ                      1        -        -        -1061109568
long     initi_order_seq                  INITI_ORDER_SEQ                  1        -        -        -1061109568
string   cont_category                    CONT_CATEGORY                    1        -        4        "@@"
double   ext_order_id                     EXT_ORDER_ID                     1        -        -        -8577.505882352939800
string   trx_datetime                     TRX_DATETIME                     1        -        15       "@@"
char     trx_status                       TRX_STATUS                       1        -        -        "@"
string   trx_sts_date                     TRX_STS_DATE                     1        -        15       "@@"
string   customer_name                    CUSTOMER_NAME                    1        -        255      "@@"
string   pNpTrxNewReccustomer_id          PNPTRXNEWRECCUSTOMER_ID          1        -        61       "@@"
string   np_product_type                  NP_PRODUCT_TYPE                  1        -        255      "@@"
string   new_num_type                     NEW_NUM_TYPE                     1        -        255      "@@"
string   main_number                      MAIN_NUMBER                      1        -        21       "@@"
string   additional_number_1              ADDITIONAL_NUMBER_1              1        -        255      "@@"
string   additional_number_2              ADDITIONAL_NUMBER_2              1        -        255      "@@"
string   additional_number_3              ADDITIONAL_NUMBER_3              1        -        255      "@@"
string   additional_number_4              ADDITIONAL_NUMBER_4              1        -        255      "@@"
string   additional_number_5              ADDITIONAL_NUMBER_5              1        -        255      "@@"
string   additional_number_6              ADDITIONAL_NUMBER_6              1        -        255      "@@"
string   additional_number_7              ADDITIONAL_NUMBER_7              1        -        255      "@@"
string   additional_number_8              ADDITIONAL_NUMBER_8              1        -        255      "@@"
string   additional_number_9              ADDITIONAL_NUMBER_9              1        -        255      "@@"
string   additional_number_10             ADDITIONAL_NUMBER_10             1        -        255      "@@"
string   primary_num                      PRIMARY_NUM                      1        -        21       "@@"
string   request_exec_date                REQUEST_EXEC_DATE                1        -        15       "@@"
string   conf_exec_date                   CONF_EXEC_DATE                   1        -        15       "@@"
string   conf_status                      CONF_STATUS                      1        -        4        "@@"
long     error_uniq_id                    ERROR_UNIQ_ID                    1        -        -        -1061109568
long     series_uniq_id                   SERIES_UNIQ_ID                   1        -        -        -1061109568
string   curr_serv_oper                   CURR_SERV_OPER                   1        -        6        "@@"
string   recip_serv_oper                  RECIP_SERV_OPER                  1        -        6        "@@"
string   curr_net_oper                    CURR_NET_OPER                    1        -        6        "@@"
string   recip_net_oper                   RECIP_NET_OPER                   1        -        6        "@@"
string   initi_order_tp                   INITI_ORDER_TP                   1        -        6        "@@"
string   text_comment                     TEXT_COMMENT                     1        -        256      "@@"
char     delay_ind                        DELAY_IND                        1        -        -        "@"
string   file_name                        FILE_NAME                        1        -        256      "@@"
string   municipality                     MUNICIPALITY                     1        -        4        "@@"
string   ext_trx_sts                      EXT_TRX_STS                      1        -        11       "@@"
string   last_trx_sts                     LAST_TRX_STS                     1        -        11       "@@"
string   initi_timestamp                  INITI_TIMESTAMP                  1        -        15       "@@"
string   other_operator                   OTHER_OPERATOR                   1        -        6        "@@"
string   point_of_connection              POINT_OF_CONNECTION              1        -        61       "@@"
char     range_upd_tp                     RANGE_UPD_TP                     1        -        -        "@"
string   csnpspc                          CSNPSPC                          1        -        7        "@@"
string   routing_info                     ROUTING_INFO                     1        -        9        "@@"
string   rating_tp                        RATING_TP                        1        -        5        "@@"
char     man_aut                          MAN_AUT                          1        -        -        "@"
string   term_conf_date                   TERM_CONF_DATE                   1        -        9        "@@"
string   service_provider                 SERVICE_PROVIDER                 1        -        6        "@@"
string   np_card_sts                      NP_CARD_STS                      1        -        13       "@@"
string   charging_info                    CHARGING_INFO                    1        -        9        "@@"
string   directory_info                   DIRECTORY_INFO                   1        -        14       "@@"
char     num_ported_ind                   NUM_PORTED_IND                   1        -        -        "@"
string   porting_case                     PORTING_CASE                     1        -        61       "@@"
string   porting_tp                       PORTING_TP                       1        -        61       "@@"
string   range                            RANGE                            1        -        18       "@@"
string   series_count                     SERIES_COUNT                     1        -        4        "@@"
string   eidnodsign                       EIDNODSIGN                       1        -        7        "@@"
string   eidntyp                          EIDNTYP                          1        -        5        "@@"
string   eidntypnumb                      EIDNTYPNUMB                      1        -        5        "@@"
string   neidnodsign                      NEIDNODSIGN                      1        -        7        "@@"
string   neidntyp                         NEIDNTYP                         1        -        5        "@@"
string   neidntypnumb                     NEIDNTYPNUMB                     1        -        5        "@@"
string   contact_name                     CONTACT_NAME                     1        -        255      "@@"
string   contact_number                   CONTACT_NUMBER                   1        -        255      "@@"
string   contact_email                    CONTACT_EMAIL                    1        -        255      "@@"
string   error_contact_name               ERROR_CONTACT_NAME               1        -        255      "@@"
string   error_contact_number             ERROR_CONTACT_NUMBER             1        -        255      "@@"
string   error_contact_email              ERROR_CONTACT_EMAIL              1        -        255      "@@"
string   text_1                           TEXT_1                           1        -        255      "@@"
string   text_2                           TEXT_2                           1        -        255      "@@"
string   text_3                           TEXT_3                           1        -        255      "@@"
string   text_4                           TEXT_4                           1        -        255      "@@"
string   text_5                           TEXT_5                           1        -        255      "@@"
string   text_6                           TEXT_6                           1        -        255      "@@"
string   text_7                           TEXT_7                           1        -        255      "@@"
string   text_8                           TEXT_8                           1        -        255      "@@"
string   text_9                           TEXT_9                           1        -        255      "@@"
string   text_10                          TEXT_10                          1        -        255      "@@"
string   rpsp                             RPSP                             1        -        255      "@@"
string   trx_sent_datetime                TRX_SENT_DATETIME                1        -        15       "@@"
string   originating_number               ORIGINATING_NUMBER               1        -        255      "@@"
string   icc                              ICC                              1        -        61       "@@"
char     coordination_ind                 COORDINATION_IND                 1        -        -        "@"
short    port_ended                       PORT_ENDED                       1        -        -        -16192
short    port_ended_main                  PORT_ENDED_MAIN                  1        -        -        -16192
short    port_ended_additional1           PORT_ENDED_ADDITIONAL1           1        -        -        -16192
short    port_ended_additional2           PORT_ENDED_ADDITIONAL2           1        -        -        -16192
short    port_ended_additional3           PORT_ENDED_ADDITIONAL3           1        -        -        -16192
short    port_ended_additional4           PORT_ENDED_ADDITIONAL4           1        -        -        -16192
short    port_ended_additional5           PORT_ENDED_ADDITIONAL5           1        -        -        -16192
short    port_ended_additional6           PORT_ENDED_ADDITIONAL6           1        -        -        -16192
short    port_ended_additional7           PORT_ENDED_ADDITIONAL7           1        -        -        -16192
short    port_ended_additional8           PORT_ENDED_ADDITIONAL8           1        -        -        -16192
short    port_ended_additional9           PORT_ENDED_ADDITIONAL9           1        -        -        -16192
short    port_ended_additional10          PORT_ENDED_ADDITIONAL10          1        -        -        -16192
string   dtsp                             DTSP                             1        -        4        "@@"
string   rtsp                             RTSP                             1        -        4        "@@"
string   pNpTrxOrdRecrowid                PNPTRXORDRECROWID                1        -        19       "@@"
double   pNpTrxOrdRecint_order_id         PNPTRXORDRECINT_ORDER_ID         1        -        -        -8577.505882352939800
string   pNpTrxOrdRecsys_creation_date    PNPTRXORDRECSYS_CREATION_DATE    1        -        15       "@@"
string   pNpTrxOrdRecsys_update_date      PNPTRXORDRECSYS_UPDATE_DATE      1        -        15       "@@"
long     pNpTrxOrdRecoperator_id          PNPTRXORDRECOPERATOR_ID          1        -        -        -1061109568
string   pNpTrxOrdRecapplication_id       PNPTRXORDRECAPPLICATION_ID       1        -        7        "@@"
string   pNpTrxOrdRecdl_service_code      PNPTRXORDRECDL_SERVICE_CODE      1        -        6        "@@"
short    pNpTrxOrdRecdl_update_stamp      PNPTRXORDRECDL_UPDATE_STAMP      1        -        -        -16192
char     order_status                     ORDER_STATUS                     1        -        -        "@"
string   last_sts_date                    LAST_STS_DATE                    1        -        9        "@@"
string   ordid_str                        ORDID_STR                        1        -        21       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   NpTrxErrBufrowid                 NPTRXERRBUFROWID                 500      -        19       "@@"
long     NpTrxErrBuferror_uniq_id         NPTRXERRBUFERROR_UNIQ_ID         500      -        -        -1061109568
long     rej_err_seq                      REJ_ERR_SEQ                      500      -        -        -1061109568
string   NpTrxErrBufsys_creation_date     NPTRXERRBUFSYS_CREATION_DATE     500      -        15       "@@"
string   NpTrxErrBufsys_update_date       NPTRXERRBUFSYS_UPDATE_DATE       500      -        15       "@@"
long     NpTrxErrBufoperator_id           NPTRXERRBUFOPERATOR_ID           500      -        -        -1061109568
string   NpTrxErrBufapplication_id        NPTRXERRBUFAPPLICATION_ID        500      -        7        "@@"
string   NpTrxErrBufdl_service_code       NPTRXERRBUFDL_SERVICE_CODE       500      -        6        "@@"
short    NpTrxErrBufdl_update_stamp       NPTRXERRBUFDL_UPDATE_STAMP       500      -        -        -16192
long     rej_err_cd                       REJ_ERR_CD                       500      -        -        -1061109568
string   rej_err_txt                      REJ_ERR_TXT                      500      -        256      "@@"
string   err_field                        ERR_FIELD                        500      -        256      "@@"
long     ban                              BAN                              1        -        -        -1061109568
long     pCtnParamReccustomer_id          PCTNPARAMRECCUSTOMER_ID          1        -        -        -1061109568
string   activity_date                    ACTIVITY_DATE                    1        -        9        "@@"
string   restore_date                     RESTORE_DATE                     1        -        9        "@@"
char     dep_return_method                DEP_RETURN_METHOD                1        -        -        "@"
char     new_ban_status                   NEW_BAN_STATUS                   1        -        -        "@"
short    exp_cycle_code                   EXP_CYCLE_CODE                   1        -        -        -16192
char     ban_waive_ind                    BAN_WAIVE_IND                    1        -        -        "@"
string   ban_waive_rsn                    BAN_WAIVE_RSN                    1        -        7        "@@"
string   waiver_uid                       WAIVER_UID                       1        -        9        "@@"
char     hold_coll_treatment              HOLD_COLL_TREATMENT              1        -        -        "@"
long     row_count                        ROW_COUNT                        1        -        -        -1061109568
string   ctn                              CTN                              100      -        21       "@@"
char     sub_status                       SUB_STATUS                       100      -        -        "@"
string   comm_start_date                  COMM_START_DATE                  100      -        9        "@@"
string   comm_end_date                    COMM_END_DATE                    100      -        9        "@@"
short    remaining_months                 REMAINING_MONTHS                 100      -        -        -16192
double   deposit                          DEPOSIT                          100      -        -        -8577.505882352939800
double   deposit_interest                 DEPOSIT_INTEREST                 100      -        -        -8577.505882352939800
double   penalty                          PENALTY                          100      -        -        -8577.505882352939800
char     waive_indicator                  WAIVE_INDICATOR                  100      -        -        "@"
string   waive_reason                     WAIVE_REASON                     100      -        7        "@@"
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939800
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939800
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   pcsActParamwaive_reason          PCSACTPARAMWAIVE_REASON          1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_csCrNpCncl
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_csExpNpTrx
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
double   int_order_id                     INT_ORDER_ID                     1        -        -        -8577.505882352939800
END

VIEW vo_csExpNpTrx
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_csLsNPRejCtn
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
char     link_type                        LINK_TYPE                        1        -        -        "@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
string   product_type                     PRODUCT_TYPE                     1        -        4        "@@"
string   department_code                  DEPARTMENT_CODE                  1        -        5        "@@"
long     page                             PAGE                             1        -        -        -1061109568
long     pageSize                         PAGESIZE                         1        -        -        -1061109568
END

VIEW vo_csLsNPRejCtn
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     totalCount                       TOTALCOUNT                       1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            1000     -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1000     -        21       "@@"
string   effective_date                   EFFECTIVE_DATE                   1000     -        15       "@@"
string   init_activation_date             INIT_ACTIVATION_DATE             1000     -        9        "@@"
char     sub_status                       SUB_STATUS                       1000     -        -        "@"
string   sub_status_date                  SUB_STATUS_DATE                  1000     -        9        "@@"
string   sub_status_last_act              SUB_STATUS_LAST_ACT              1000     -        4        "@@"
string   sub_status_rsn_code              SUB_STATUS_RSN_CODE              1000     -        5        "@@"
string   soc                              SOC                              1000     -        10       "@@"
string   campaign                         CAMPAIGN                         1000     -        10       "@@"
string   anl_rowid                        ANL_ROWID                        1000     -        19       "@@"
char     link_type                        LINK_TYPE                        1000     -        -        "@"
string   control_name                     CONTROL_NAME                     1000     -        41       "@@"
string   adr_zip                          ADR_ZIP                          1000     -        10       "@@"
string   adr_street_name                  ADR_STREET_NAME                  1000     -        61       "@@"
string   adr_city                         ADR_CITY                         1000     -        40       "@@"
string   adr_pob                          ADR_POB                          1000     -        11       "@@"
long     name_id                          NAME_ID                          1000     -        -        -1061109568
long     address_id                       ADDRESS_ID                       1000     -        -        -1061109568
char     name_format                      NAME_FORMAT                      1000     -        -        "@"
string   additional_title                 ADDITIONAL_TITLE                 1000     -        61       "@@"
char     listed_ind                       LISTED_IND                       1000     -        -        "@"
string   next_ctn                         NEXT_CTN                         1000     -        21       "@@"
long     next_ban                         NEXT_BAN                         1000     -        -        -1061109568
END


