VIEW vi_ifChkCrdEvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   cas_request_type                 CAS_REQUEST_TYPE                 1        -        3        "@@"
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939800
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939800
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_ifChkCrdEvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   request_status                   REQUEST_STATUS                   1        -        3        "@@"
string   status_date                      STATUS_DATE                      1        -        15       "@@"
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
string   cas_record_number                CAS_RECORD_NUMBER                1        -        13       "@@"
long     cas_dtl_seq                      CAS_DTL_SEQ                      1        -        -        -1061109568
long     product_limit                    PRODUCT_LIMIT                    1        -        -        -1061109568
double   deposit_amount                   DEPOSIT_AMOUNT                   1        -        -        -8577.505882352939800
string   business_instruction             BUSINESS_INSTRUCTION             1        -        3        "@@"
char     dep_status                       DEP_STATUS                       1        -        -        "@"
char     dep_mode                         DEP_MODE                         1        -        -        "@"
char     credit_class                     CREDIT_CLASS                     1        -        -        "@"
char     current_strategy_code            CURRENT_STRATEGY_CODE            1        -        -        "@"
char     scorex_credit_class              SCOREX_CREDIT_CLASS              1        -        -        "@"
char     scorex_strategy_code             SCOREX_STRATEGY_CODE             1        -        -        "@"
double   credit_limit                     CREDIT_LIMIT                     1        -        -        -8577.505882352939800
char     dd_allow_pym_mtd                 DD_ALLOW_PYM_MTD                 1        -        -        "@"
string   product_taken                    PRODUCT_TAKEN                    1        -        4        "@@"
long     credit_score                     CREDIT_SCORE                     1        -        -        -1061109568
string   system_decision                  SYSTEM_DECISION                  1        -        4        "@@"
string   final_decision                   FINAL_DECISION                   1        -        4        "@@"
long     row_count                        ROW_COUNT                        1        -        -        -1061109568
char     condition_1                      CONDITION_1                      8        -        -        "@"
char     condition_2                      CONDITION_2                      8        -        -        "@"
char     condition_3                      CONDITION_3                      8        -        -        "@"
char     condition_4                      CONDITION_4                      8        -        -        "@"
char     condition_5                      CONDITION_5                      8        -        -        "@"
char     condition_6                      CONDITION_6                      8        -        -        "@"
char     condition_7                      CONDITION_7                      8        -        -        "@"
char     condition_8                      CONDITION_8                      8        -        -        "@"
char     condition_9                      CONDITION_9                      8        -        -        "@"
char     condition_10                     CONDITION_10                     8        -        -        "@"
char     condition_11                     CONDITION_11                     8        -        -        "@"
string   cas_dpst_amt                     CAS_DPST_AMT                     8        -        6        "@@"
string   cas_crd_lmt                      CAS_CRD_LMT                      8        -        6        "@@"
string   cas_sdw_lmt                      CAS_SDW_LMT                      8        -        6        "@@"
string   cvLlRsltsystem_decision          CVLLRSLTSYSTEM_DECISION          1        -        4        "@@"
string   cvLlRsltfinal_decision           CVLLRSLTFINAL_DECISION           1        -        4        "@@"
long     cvLlRsltrow_count                CVLLRSLTROW_COUNT                1        -        -        -1061109568
char     cvMobLlRsltDatacondition_1       CVMOBLLRSLTDATACONDITION_1       8        -        -        "@"
char     cvMobLlRsltDatacondition_2       CVMOBLLRSLTDATACONDITION_2       8        -        -        "@"
char     cvMobLlRsltDatacondition_3       CVMOBLLRSLTDATACONDITION_3       8        -        -        "@"
char     cvMobLlRsltDatacondition_4       CVMOBLLRSLTDATACONDITION_4       8        -        -        "@"
char     cvMobLlRsltDatacondition_5       CVMOBLLRSLTDATACONDITION_5       8        -        -        "@"
char     cvMobLlRsltDatacondition_6       CVMOBLLRSLTDATACONDITION_6       8        -        -        "@"
char     cvMobLlRsltDatacondition_7       CVMOBLLRSLTDATACONDITION_7       8        -        -        "@"
char     cvMobLlRsltDatacondition_8       CVMOBLLRSLTDATACONDITION_8       8        -        -        "@"
char     cvMobLlRsltDatacondition_9       CVMOBLLRSLTDATACONDITION_9       8        -        -        "@"
char     cvMobLlRsltDatacondition_10      CVMOBLLRSLTDATACONDITION_10      8        -        -        "@"
char     cvMobLlRsltDatacondition_11      CVMOBLLRSLTDATACONDITION_11      8        -        -        "@"
string   cvMobLlRsltDatacas_dpst_amt      CVMOBLLRSLTDATACAS_DPST_AMT      8        -        6        "@@"
string   cvMobLlRsltDatacas_crd_lmt       CVMOBLLRSLTDATACAS_CRD_LMT       8        -        6        "@@"
string   cvMobLlRsltDatacas_sdw_lmt       CVMOBLLRSLTDATACAS_SDW_LMT       8        -        6        "@@"
string   cvIspRsltsystem_decision         CVISPRSLTSYSTEM_DECISION         1        -        4        "@@"
string   cvIspRsltfinal_decision          CVISPRSLTFINAL_DECISION          1        -        4        "@@"
long     cvIspRsltrow_count               CVISPRSLTROW_COUNT               1        -        -        -1061109568
char     cvIspRsltDatacondition_1         CVISPRSLTDATACONDITION_1         8        -        -        "@"
char     cvIspRsltDatacondition_2         CVISPRSLTDATACONDITION_2         8        -        -        "@"
char     cvIspRsltDatacondition_3         CVISPRSLTDATACONDITION_3         8        -        -        "@"
char     cvIspRsltDatacondition_4         CVISPRSLTDATACONDITION_4         8        -        -        "@"
char     cvIspRsltDatacondition_5         CVISPRSLTDATACONDITION_5         8        -        -        "@"
char     cvIspRsltDatacondition_6         CVISPRSLTDATACONDITION_6         8        -        -        "@"
string   cvIspRsltDatacas_dpst_amt        CVISPRSLTDATACAS_DPST_AMT        8        -        6        "@@"
string   cvIspRsltDatacas_crd_lmt         CVISPRSLTDATACAS_CRD_LMT         8        -        6        "@@"
string   cvIspRsltDatacas_sdw_lmt         CVISPRSLTDATACAS_SDW_LMT         8        -        6        "@@"
END


VIEW vi_ifGtCasDtl
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   cas_request_type                 CAS_REQUEST_TYPE                 1        -        3        "@@"
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939800
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939800
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_ifGtCasDtl
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     work_listoperator_id             WORK_LISTOPERATOR_ID             1        -        -        -1061109568
string   work_listapplication_id          WORK_LISTAPPLICATION_ID          1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
long     ban                              BAN                              1        -        -        -1061109568
long     init_oper_id                     INIT_OPER_ID                     1        -        -        -1061109568
string   request_date                     REQUEST_DATE                     1        -        15       "@@"
string   request_status                   REQUEST_STATUS                   1        -        3        "@@"
string   status_date                      STATUS_DATE                      1        -        15       "@@"
long     retry_no                         RETRY_NO                         1        -        -        -1061109568
string   cas_error_message                CAS_ERROR_MESSAGE                1        -        71       "@@"
string   cas_date                         CAS_DATE                         1        -        15       "@@"
long     cas_error_count                  CAS_ERROR_COUNT                  1        -        -        -1061109568
long     cas_dtl_seq                      CAS_DTL_SEQ                      1        -        -        -1061109568
string   cas_request_type                 CAS_REQUEST_TYPE                 1        -        3        "@@"
string   cas_record_number                CAS_RECORD_NUMBER                1        -        13       "@@"
string   work_detailsrowid                WORK_DETAILSROWID                1        -        19       "@@"
long     work_detailscas_order_no         WORK_DETAILSCAS_ORDER_NO         1        -        -        -1061109568
string   work_detailssys_creation_date    WORK_DETAILSSYS_CREATION_DATE    1        -        15       "@@"
string   work_detailssys_update_date      WORK_DETAILSSYS_UPDATE_DATE      1        -        15       "@@"
long     work_detailsoperator_id          WORK_DETAILSOPERATOR_ID          1        -        -        -1061109568
string   work_detailsapplication_id       WORK_DETAILSAPPLICATION_ID       1        -        7        "@@"
string   work_detailsdl_service_code      WORK_DETAILSDL_SERVICE_CODE      1        -        6        "@@"
short    work_detailsdl_update_stamp      WORK_DETAILSDL_UPDATE_STAMP      1        -        -        -16192
char     account_type                     ACCOUNT_TYPE                     1        -        -        "@"
string   account_sub_type                 ACCOUNT_SUB_TYPE                 1        -        3        "@@"
string   application_datetime             APPLICATION_DATETIME             1        -        15       "@@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   nationality                      NATIONALITY                      1        -        4        "@@"
char     gender                           GENDER                           1        -        -        "@"
string   marital_status                   MARITAL_STATUS                   1        -        5        "@@"
string   accommodation_type               ACCOMMODATION_TYPE               1        -        5        "@@"
string   employment_type                  EMPLOYMENT_TYPE                  1        -        5        "@@"
string   employment_date                  EMPLOYMENT_DATE                  1        -        9        "@@"
string   open_bank_account_date           OPEN_BANK_ACCOUNT_DATE           1        -        9        "@@"
string   payment_method                   PAYMENT_METHOD                   1        -        3        "@@"
string   preferred_lang                   PREFERRED_LANG                   1        -        3        "@@"
string   dealer_id                        DEALER_ID                        1        -        6        "@@"
string   home_telno                       HOME_TELNO                       1        -        21       "@@"
string   work_telno                       WORK_TELNO                       1        -        21       "@@"
string   business_est_date                BUSINESS_EST_DATE                1        -        9        "@@"
string   name_title_salutation            NAME_TITLE_SALUTATION            1        -        21       "@@"
string   last_name                        LAST_NAME                        1        -        61       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   middle_name                      MIDDLE_NAME                      1        -        61       "@@"
string   id_type                          ID_TYPE                          1        -        5        "@@"
string   id_number                        ID_NUMBER                        1        -        21       "@@"
string   curr_adr_start_date              CURR_ADR_START_DATE              1        -        9        "@@"
string   curr_adr_zip_code                CURR_ADR_ZIP_CODE                1        -        10       "@@"
string   curr_adr_street_name             CURR_ADR_STREET_NAME             1        -        61       "@@"
string   curr_adr_street_no               CURR_ADR_STREET_NO               1        -        21       "@@"
string   curr_adr_house_let               CURR_ADR_HOUSE_LET               1        -        3        "@@"
string   curr_adr_storey                  CURR_ADR_STOREY                  1        -        3        "@@"
string   curr_adr_door_no                 CURR_ADR_DOOR_NO                 1        -        5        "@@"
string   curr_adr_city                    CURR_ADR_CITY                    1        -        40       "@@"
string   curr_adr_country_cd              CURR_ADR_COUNTRY_CD              1        -        4        "@@"
string   prev_adr_start_date              PREV_ADR_START_DATE              1        -        9        "@@"
string   prev_adr_zip_code                PREV_ADR_ZIP_CODE                1        -        10       "@@"
string   prev_adr_street_name             PREV_ADR_STREET_NAME             1        -        61       "@@"
string   prev_adr_street_no               PREV_ADR_STREET_NO               1        -        21       "@@"
string   prev_adr_house_let               PREV_ADR_HOUSE_LET               1        -        3        "@@"
string   prev_adr_storey                  PREV_ADR_STOREY                  1        -        3        "@@"
string   prev_adr_door_no                 PREV_ADR_DOOR_NO                 1        -        5        "@@"
string   prev_adr_city                    PREV_ADR_CITY                    1        -        40       "@@"
string   prev_adr_country_cd              PREV_ADR_COUNTRY_CD              1        -        4        "@@"
string   bill_adr_start_date              BILL_ADR_START_DATE              1        -        9        "@@"
string   bill_adr_zip_code                BILL_ADR_ZIP_CODE                1        -        10       "@@"
string   bill_adr_street_name             BILL_ADR_STREET_NAME             1        -        61       "@@"
string   bill_adr_street_no               BILL_ADR_STREET_NO               1        -        21       "@@"
string   bill_adr_house_let               BILL_ADR_HOUSE_LET               1        -        3        "@@"
string   bill_adr_storey                  BILL_ADR_STOREY                  1        -        3        "@@"
string   bill_adr_door_no                 BILL_ADR_DOOR_NO                 1        -        5        "@@"
string   bill_adr_city                    BILL_ADR_CITY                    1        -        40       "@@"
string   bill_adr_country_cd              BILL_ADR_COUNTRY_CD              1        -        4        "@@"
string   work_detailsrun_date             WORK_DETAILSRUN_DATE             1        -        15       "@@"
long     credit_score                     CREDIT_SCORE                     1        -        -        -1061109568
string   freq_mon_prod_lim                FREQ_MON_PROD_LIM                1        -        6        "@@"
long     product_limit                    PRODUCT_LIMIT                    1        -        -        -1061109568
string   airtime_limit                    AIRTIME_LIMIT                    1        -        6        "@@"
double   deposit_amount                   DEPOSIT_AMOUNT                   1        -        -        -8577.505882352939800
string   business_instr                   BUSINESS_INSTR                   1        -        3        "@@"
short    cred_bureau                      CRED_BUREAU                      1        -        -        -16192
short    subscription_limit               SUBSCRIPTION_LIMIT               1        -        -        -16192
char     strategy_code                    STRATEGY_CODE                    1        -        -        "@"
double   credit_limit                     CREDIT_LIMIT                     1        -        -        -8577.505882352939800
char     dd_allow_pym_mtd                 DD_ALLOW_PYM_MTD                 1        -        -        "@"
string   work_detailscas_record_number    WORK_DETAILSCAS_RECORD_NUMBER    1        -        13       "@@"
short    num_of_employees                 NUM_OF_EMPLOYEES                 1        -        -        -16192
string   company_type_code                COMPANY_TYPE_CODE                1        -        4        "@@"
string   mobile_telno                     MOBILE_TELNO                     1        -        21       "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   bank_code                        BANK_CODE                        1        -        11       "@@"
char     allow_advertising_ind            ALLOW_ADVERTISING_IND            1        -        -        "@"
string   cs_def_product_type              CS_DEF_PRODUCT_TYPE              1        -        4        "@@"
double   curr_debt                        CURR_DEBT                        1        -        -        -8577.505882352939800
double   prev_debt                        PREV_DEBT                        1        -        -        -8577.505882352939800
string   start_service_date               START_SERVICE_DATE               1        -        9        "@@"
char     bypass_strategy_code             BYPASS_STRATEGY_CODE             1        -        -        "@"
char     bypass_reason_cd                 BYPASS_REASON_CD                 1        -        -        "@"
string   product_taken                    PRODUCT_TAKEN                    1        -        4        "@@"
string   policy_rules                     POLICY_RULES                     1        -        401      "@@"
string   dealer_code                      DEALER_CODE                      1        -        6        "@@"
string   marketing_code                   MARKETING_CODE                   1        -        4        "@@"
string   business_type_code               BUSINESS_TYPE_CODE               1        -        4        "@@"
char     vip_ind                          VIP_IND                          1        -        -        "@"
short    num_of_mub_subs                  NUM_OF_MUB_SUBS                  1        -        -        -16192
short    num_of_ll_subs                   NUM_OF_LL_SUBS                   1        -        -        -16192
short    num_of_isp_subs                  NUM_OF_ISP_SUBS                  1        -        -        -16192
char     dep_status                       DEP_STATUS                       1        -        -        "@"
char     dep_mode                         DEP_MODE                         1        -        -        "@"
char     credit_class                     CREDIT_CLASS                     1        -        -        "@"
END


VIEW vi_ifUpCrdt
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     ban                              BAN                              1        -        -        -1061109568
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
string   run_date                         RUN_DATE                         1        -        15       "@@"
long     credit_score                     CREDIT_SCORE                     1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
string   freq_mon_prod_lim                FREQ_MON_PROD_LIM                1        -        6        "@@"
long     product_limit                    PRODUCT_LIMIT                    1        -        -        -1061109568
string   airtime_limit                    AIRTIME_LIMIT                    1        -        6        "@@"
double   deposit_amount                   DEPOSIT_AMOUNT                   1        -        -        -8577.505882352939800
string   business_instruction             BUSINESS_INSTRUCTION             1        -        3        "@@"
short    subscription_limit               SUBSCRIPTION_LIMIT               1        -        -        -16192
short    cred_bureau                      CRED_BUREAU                      1        -        -        -16192
END

VIEW vo_ifUpCrdt
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     ban                              BAN                              1        -        -        -1061109568
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
string   run_date                         RUN_DATE                         1        -        15       "@@"
long     credit_score                     CREDIT_SCORE                     1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
string   freq_mon_prod_lim                FREQ_MON_PROD_LIM                1        -        6        "@@"
long     product_limit                    PRODUCT_LIMIT                    1        -        -        -1061109568
string   airtime_limit                    AIRTIME_LIMIT                    1        -        6        "@@"
double   deposit_amount                   DEPOSIT_AMOUNT                   1        -        -        -8577.505882352939800
string   business_instruction             BUSINESS_INSTRUCTION             1        -        3        "@@"
short    subscription_limit               SUBSCRIPTION_LIMIT               1        -        -        -16192
short    cred_bureau                      CRED_BUREAU                      1        -        -        -16192
string   request_status                   REQUEST_STATUS                   1        -        3        "@@"
long     wf_service_status                WF_SERVICE_STATUS                1        -        -        -1061109568
END


VIEW vi_ifDlCrdEvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939800
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939800
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_ifDlCrdEvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_ifLsCrdEvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   from_date                        FROM_DATE                        1        -        9        "@@"
string   until_date                       UNTIL_DATE                       1        -        9        "@@"
long     init_oper_id                     INIT_OPER_ID                     1        -        -        -1061109568
string   request_status                   REQUEST_STATUS                   1        -        3        "@@"
string   cas_request_type                 CAS_REQUEST_TYPE                 1        -        3        "@@"
long     page                             PAGE                             1        -        -        -1061109568
long     pageSize                         PAGESIZE                         1        -        -        -1061109568
END

VIEW vo_ifLsCrdEvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
short    moreRows                         MOREROWS                         1        -        -        -16192
long     totalCount                       TOTALCOUNT                       1        -        -        -1061109568
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            600      -        19       "@@"
long     cas_order_no                     CAS_ORDER_NO                     600      -        -        -1061109568
long     ban                              BAN                              600      -        -        -1061109568
long     init_oper_id                     INIT_OPER_ID                     600      -        -        -1061109568
string   request_date                     REQUEST_DATE                     600      -        15       "@@"
string   request_status                   REQUEST_STATUS                   600      -        3        "@@"
string   status_date                      STATUS_DATE                      600      -        15       "@@"
long     product_limit                    PRODUCT_LIMIT                    600      -        -        -1061109568
double   deposit_amount                   DEPOSIT_AMOUNT                   600      -        -        -8577.505882352939800
char     account_type                     ACCOUNT_TYPE                     600      -        -        "@"
string   account_sub_type                 ACCOUNT_SUB_TYPE                 600      -        3        "@@"
string   dealer_id                        DEALER_ID                        600      -        6        "@@"
string   name_title_salutation            NAME_TITLE_SALUTATION            600      -        21       "@@"
string   last_name                        LAST_NAME                        600      -        61       "@@"
string   first_name                       FIRST_NAME                       600      -        33       "@@"
string   middle_name                      MIDDLE_NAME                      600      -        61       "@@"
string   id_type                          ID_TYPE                          600      -        5        "@@"
string   id_number                        ID_NUMBER                        600      -        21       "@@"
double   credit_limit                     CREDIT_LIMIT                     600      -        -        -8577.505882352939800
char     dd_allow_pym_mtd                 DD_ALLOW_PYM_MTD                 600      -        -        "@"
char     credit_class                     CREDIT_CLASS                     600      -        -        "@"
char     strategy_code                    STRATEGY_CODE                    600      -        -        "@"
string   cas_request_type                 CAS_REQUEST_TYPE                 600      -        3        "@@"
long     credit_score                     CREDIT_SCORE                     600      -        -        -1061109568
string   cas_record_num                   CAS_RECORD_NUM                   600      -        13       "@@"
END


