VIEW vi_csEnvActCtn
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
char     actvFeeInd                       ACTVFEEIND                       1        -        -        "@"
double   activationFee                    ACTIVATIONFEE                    1        -        -        -8577.505882352939800
char     changeInd                        CHANGEIND                        1        -        -        "@"
char     waiveRsnInd                      WAIVERSNIND                      1        -        -        "@"
string   waiveRsn                         WAIVERSN                         1        -        7        "@@"
string   numLoc                           NUMLOC                           1        -        4        "@@"
string   pprwrk_sts_cd                    PPRWRK_STS_CD                    1        -        3        "@@"
char     rmsActvInd                       RMSACTVIND                       1        -        -        "@"
long     rowcount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            50       -        19       "@@"
string   soc                              SOC                              50       -        10       "@@"
string   soc_effective_date               SOC_EFFECTIVE_DATE               50       -        9        "@@"
string   commitment_end_date              COMMITMENT_END_DATE              50       -        9        "@@"
char     service_type                     SERVICE_TYPE                     50       -        -        "@"
string   effective_date                   EFFECTIVE_DATE                   50       -        9        "@@"
string   expiration_date                  EXPIRATION_DATE                  50       -        9        "@@"
char     soc_level_code                   SOC_LEVEL_CODE                   50       -        -        "@"
string   dealer_code                      DEALER_CODE                      50       -        6        "@@"
string   sales_agent                      SALES_AGENT                      50       -        6        "@@"
char     srv_mode                         SRV_MODE                         50       -        -        "@"
char     srv_sub_mode                     SRV_SUB_MODE                     50       -        -        "@"
long     soc_seq_no                       SOC_SEQ_NO                       50       -        -        -1061109568
long     srv_trx_id                       SRV_TRX_ID                       50       -        -        -1061109568
long     campaign_seq                     CAMPAIGN_SEQ                     50       -        -        -1061109568
string   campaign                         CAMPAIGN                         50       -        10       "@@"
short    commit_orig_no_month             COMMIT_ORIG_NO_MONTH             50       -        -        -16192
string   product_type                     PRODUCT_TYPE                     50       -        4        "@@"
long     loan_ver_no                      LOAN_VER_NO                      50       -        -        -1061109568
long     loan_seq_no                      LOAN_SEQ_NO                      50       -        -        -1061109568
double   soc_actv_fee                     SOC_ACTV_FEE                     50       -        -        -8577.505882352939800
string   promotional_soc                  PROMOTIONAL_SOC                  50       -        10       "@@"
string   reason_code                      REASON_CODE                      50       -        5        "@@"
string   soc_start_rc_date                SOC_START_RC_DATE                50       -        9        "@@"
char     rc_date_copy_ind                 RC_DATE_COPY_IND                 50       -        -        "@"
string   pAgrRecrowid                     PAGRRECROWID                     1        -        19       "@@"
string   pAgrRecsoc                       PAGRRECSOC                       1        -        10       "@@"
string   pAgrRecsoc_effective_date        PAGRRECSOC_EFFECTIVE_DATE        1        -        9        "@@"
string   pAgrReccommitment_end_date       PAGRRECCOMMITMENT_END_DATE       1        -        9        "@@"
char     pAgrRecservice_type              PAGRRECSERVICE_TYPE              1        -        -        "@"
string   pAgrReceffective_date            PAGRRECEFFECTIVE_DATE            1        -        9        "@@"
string   pAgrRecexpiration_date           PAGRRECEXPIRATION_DATE           1        -        9        "@@"
char     pAgrRecsoc_level_code            PAGRRECSOC_LEVEL_CODE            1        -        -        "@"
string   pAgrRecdealer_code               PAGRRECDEALER_CODE               1        -        6        "@@"
string   pAgrRecsales_agent               PAGRRECSALES_AGENT               1        -        6        "@@"
char     pAgrRecsrv_mode                  PAGRRECSRV_MODE                  1        -        -        "@"
char     pAgrRecsrv_sub_mode              PAGRRECSRV_SUB_MODE              1        -        -        "@"
long     pAgrRecsoc_seq_no                PAGRRECSOC_SEQ_NO                1        -        -        -1061109568
long     pAgrRecsrv_trx_id                PAGRRECSRV_TRX_ID                1        -        -        -1061109568
long     pAgrReccampaign_seq              PAGRRECCAMPAIGN_SEQ              1        -        -        -1061109568
string   pAgrReccampaign                  PAGRRECCAMPAIGN                  1        -        10       "@@"
short    pAgrReccommit_orig_no_month      PAGRRECCOMMIT_ORIG_NO_MONTH      1        -        -        -16192
string   pAgrRecproduct_type              PAGRRECPRODUCT_TYPE              1        -        4        "@@"
long     pAgrRecloan_ver_no               PAGRRECLOAN_VER_NO               1        -        -        -1061109568
long     pAgrRecloan_seq_no               PAGRRECLOAN_SEQ_NO               1        -        -        -1061109568
double   pAgrRecsoc_actv_fee              PAGRRECSOC_ACTV_FEE              1        -        -        -8577.505882352939800
string   pAgrRecpromotional_soc           PAGRRECPROMOTIONAL_SOC           1        -        10       "@@"
string   pAgrRecreason_code               PAGRRECREASON_CODE               1        -        5        "@@"
string   pAgrRecsoc_start_rc_date         PAGRRECSOC_START_RC_DATE         1        -        9        "@@"
char     pAgrRecrc_date_copy_ind          PAGRRECRC_DATE_COPY_IND          1        -        -        "@"
long     pEsnBufferrowCount               PESNBUFFERROWCOUNT               1        -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     50       -        21       "@@"
long     phd_seq_no                       PHD_SEQ_NO                       50       -        -        -1061109568
short    equipment_level                  EQUIPMENT_LEVEL                  50       -        -        -16192
string   imsi                             IMSI                             50       -        16       "@@"
string   phyDevArrayexpiration_date       PHYDEVARRAYEXPIRATION_DATE       50       -        15       "@@"
string   phyDevArrayeffective_date        PHYDEVARRAYEFFECTIVE_DATE        50       -        15       "@@"
string   ownership_code                   OWNERSHIP_CODE                   50       -        3        "@@"
char     sw_state_ind                     SW_STATE_IND                     50       -        -        "@"
string   last_sw_actv_date                LAST_SW_ACTV_DATE                50       -        9        "@@"
char     next_actv_code                   NEXT_ACTV_CODE                   50       -        -        "@"
string   next_actv_date                   NEXT_ACTV_DATE                   50       -        9        "@@"
string   next_actv_issue_dt               NEXT_ACTV_ISSUE_DT               50       -        9        "@@"
char     device_type                      DEVICE_TYPE                      50       -        -        "@"
char     esn_mode                         ESN_MODE                         50       -        -        "@"
string   item_id                          ITEM_ID                          50       -        16       "@@"
string   pool                             POOL                             50       -        3        "@@"
string   location_id                      LOCATION_ID                      50       -        5        "@@"
string   activity_code                    ACTIVITY_CODE                    50       -        5        "@@"
string   activity_date                    ACTIVITY_DATE                    50       -        15       "@@"
char     operation_status                 OPERATION_STATUS                 50       -        -        "@"
char     item_ownership                   ITEM_OWNERSHIP                   50       -        -        "@"
string   item_ownership_dt                ITEM_OWNERSHIP_DT                50       -        15       "@@"
char     curr_possession                  CURR_POSSESSION                  50       -        -        "@"
string   curr_possession_dt               CURR_POSSESSION_DT               50       -        15       "@@"
char     missing_ind                      MISSING_IND                      50       -        -        "@"
char     in_repair_ind                    IN_REPAIR_IND                    50       -        -        "@"
char     in_transit_ind                   IN_TRANSIT_IND                   50       -        -        "@"
char     comited_to_pos_ind               COMITED_TO_POS_IND               50       -        -        "@"
string   comited_date                     COMITED_DATE                     50       -        15       "@@"
string   activity_reason                  ACTIVITY_REASON                  50       -        4        "@@"
char     upgrade_ind                      UPGRADE_IND                      50       -        -        "@"
string   expected_rtrn_date               EXPECTED_RTRN_DATE               50       -        15       "@@"
string   police_report_no                 POLICE_REPORT_NO                 50       -        16       "@@"
string   police_report_date               POLICE_REPORT_DATE               50       -        15       "@@"
string   police_station                   POLICE_STATION                   50       -        31       "@@"
long     puk                              PUK                              50       -        -        -1061109568
long     puk2                             PUK2                             50       -        -        -1061109568
string   first_used_date                  FIRST_USED_DATE                  50       -        15       "@@"
char     sim_status                       SIM_STATUS                       50       -        -        "@"
char     suspend_ind                      SUSPEND_IND                      50       -        -        "@"
string   suspend_date                     SUSPEND_DATE                     50       -        15       "@@"
char     sent_to_auc_ind                  SENT_TO_AUC_IND                  50       -        -        "@"
string   hlr_cd                           HLR_CD                           50       -        4        "@@"
string   k4id                             K4ID                             50       -        41       "@@"
string   phyDevArraydealer_code           PHYDEVARRAYDEALER_CODE           50       -        6        "@@"
string   pCtnRecrowid                     PCTNRECROWID                     1        -        19       "@@"
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
long     customer_id                      CUSTOMER_ID                      1        -        -        -1061109568
string   sys_creation_date                SYS_CREATION_DATE                1        -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  1        -        15       "@@"
long     pCtnRecoperator_id               PCTNRECOPERATOR_ID               1        -        -        -1061109568
string   pCtnRecapplication_id            PCTNRECAPPLICATION_ID            1        -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  1        -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  1        -        -        -16192
string   pCtnReceffective_date            PCTNRECEFFECTIVE_DATE            1        -        15       "@@"
string   init_activation_date             INIT_ACTIVATION_DATE             1        -        9        "@@"
char     sub_status                       SUB_STATUS                       1        -        -        "@"
string   sub_status_date                  SUB_STATUS_DATE                  1        -        9        "@@"
string   original_init_date               ORIGINAL_INIT_DATE               1        -        15       "@@"
string   sub_status_last_act              SUB_STATUS_LAST_ACT              1        -        4        "@@"
string   sub_status_rsn_code              SUB_STATUS_RSN_CODE              1        -        5        "@@"
string   pCtnRecproduct_type              PCTNRECPRODUCT_TYPE              1        -        4        "@@"
long     customer_ban                     CUSTOMER_BAN                     1        -        -        -1061109568
long     ctn_seq_no                       CTN_SEQ_NO                       1        -        -        -1061109568
string   req_st_grace_period              REQ_ST_GRACE_PERIOD              1        -        9        "@@"
string   req_end_grace_period             REQ_END_GRACE_PERIOD             1        -        9        "@@"
string   commit_start_date                COMMIT_START_DATE                1        -        9        "@@"
string   commit_end_date                  COMMIT_END_DATE                  1        -        9        "@@"
string   commit_reason_code               COMMIT_REASON_CODE               1        -        4        "@@"
short    pCtnReccommit_orig_no_month      PCTNRECCOMMIT_ORIG_NO_MONTH      1        -        -        -16192
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   contract_no                      CONTRACT_NO                      1        -        11       "@@"
long     cnt_seq_no                       CNT_SEQ_NO                       1        -        -        -1061109568
string   pCtnRecdealer_code               PCTNRECDEALER_CODE               1        -        6        "@@"
string   org_dealer_code                  ORG_DEALER_CODE                  1        -        6        "@@"
string   pCtnRecsales_agent               PCTNRECSALES_AGENT               1        -        6        "@@"
string   org_sales_agent                  ORG_SALES_AGENT                  1        -        6        "@@"
double   req_deposit_amt                  REQ_DEPOSIT_AMT                  1        -        -        -8577.505882352939800
string   leading_number                   LEADING_NUMBER                   1        -        21       "@@"
char     pabx_ind                         PABX_IND                         1        -        -        "@"
string   next_ctn                         NEXT_CTN                         1        -        21       "@@"
string   next_ctn_chg_date                NEXT_CTN_CHG_DATE                1        -        9        "@@"
string   prv_ctn                          PRV_CTN                          1        -        21       "@@"
string   prv_ctn_chg_date                 PRV_CTN_CHG_DATE                 1        -        9        "@@"
long     next_ban                         NEXT_BAN                         1        -        -        -1061109568
string   next_ban_move_date               NEXT_BAN_MOVE_DATE               1        -        9        "@@"
long     prv_ban                          PRV_BAN                          1        -        -        -1061109568
string   prv_ban_move_date                PRV_BAN_MOVE_DATE                1        -        9        "@@"
string   sub_sts_issue_date               SUB_STS_ISSUE_DATE               1        -        9        "@@"
string   activate_waive_rsn               ACTIVATE_WAIVE_RSN               1        -        7        "@@"
string   earliest_actv_date               EARLIEST_ACTV_DATE               1        -        9        "@@"
string   sub_actv_location                SUB_ACTV_LOCATION                1        -        5        "@@"
double   cust_watch_lmt                   CUST_WATCH_LMT                   1        -        -        -8577.505882352939800
string   cust_watch_date                  CUST_WATCH_DATE                  1        -        9        "@@"
double   basic_watch_lmt                  BASIC_WATCH_LMT                  1        -        -        -8577.505882352939800
short    credit_watch_pin_cd              CREDIT_WATCH_PIN_CD              1        -        -        -16192
string   sub_market_code                  SUB_MARKET_CODE                  1        -        4        "@@"
short    limit_reserved_days              LIMIT_RESERVED_DAYS              1        -        -        -16192
string   ff_expiration_date               FF_EXPIRATION_DATE               1        -        15       "@@"
char     flex_ind                         FLEX_IND                         1        -        -        "@"
char     duo_ind                          DUO_IND                          1        -        -        "@"
char     listed_ind                       LISTED_IND                       1        -        -        "@"
string   sub_department_cd                SUB_DEPARTMENT_CD                1        -        5        "@@"
string   last_subs_disc_dt                LAST_SUBS_DISC_DT                1        -        9        "@@"
string   last_subs_disc_dt_ud             LAST_SUBS_DISC_DT_UD             1        -        9        "@@"
short    last_subscr_disc_sn              LAST_SUBSCR_DISC_SN              1        -        -        -16192
short    last_subscr_disc_sn_ud           LAST_SUBSCR_DISC_SN_UD           1        -        -        -16192
string   pni                              PNI                              1        -        11       "@@"
string   rms_ref_store_id                 RMS_REF_STORE_ID                 1        -        5        "@@"
char     rms_ref_type                     RMS_REF_TYPE                     1        -        -        "@"
long     rms_ref_od                       RMS_REF_OD                       1        -        -        -1061109568
double   dlr_act_fee                      DLR_ACT_FEE                      1        -        -        -8577.505882352939800
double   prep_amount                      PREP_AMOUNT                      1        -        -        -8577.505882352939800
long     subscriber_id                    SUBSCRIBER_ID                    1        -        -        -1061109568
string   sub_lang                         SUB_LANG                         1        -        3        "@@"
string   sms_rcv_style_code               SMS_RCV_STYLE_CODE               1        -        3        "@@"
short    conv_run_no                      CONV_RUN_NO                      1        -        -        -16192
char     allow_advertising_ind            ALLOW_ADVERTISING_IND            1        -        -        "@"
short    ivr_wrong_access_no              IVR_WRONG_ACCESS_NO              1        -        -        -16192
double   threshold_amt                    THRESHOLD_AMT                    1        -        -        -8577.505882352939800
string   publish_level                    PUBLISH_LEVEL                    1        -        31       "@@"
char     auto_release_ind                 AUTO_RELEASE_IND                 1        -        -        "@"
string   cust_watch_eff_date              CUST_WATCH_EFF_DATE              1        -        9        "@@"
string   cust_watch_exp_date              CUST_WATCH_EXP_DATE              1        -        9        "@@"
double   operator_cw_lmt                  OPERATOR_CW_LMT                  1        -        -        -8577.505882352939800
char     send_sms_for_match               SEND_SMS_FOR_MATCH               1        -        -        "@"
char     cps_status                       CPS_STATUS                       1        -        -        "@"
short    cps_transaction                  CPS_TRANSACTION                  1        -        -        -16192
short    cps_type                         CPS_TYPE                         1        -        -        -16192
string   isp_pass                         ISP_PASS                         1        -        31       "@@"
string   isp_type                         ISP_TYPE                         1        -        3        "@@"
string   operator_tmp_date                OPERATOR_TMP_DATE                1        -        9        "@@"
double   operator_tmp_lmt                 OPERATOR_TMP_LMT                 1        -        -        -8577.505882352939800
string   sub_org_cd                       SUB_ORG_CD                       1        -        11       "@@"
string   org_member_no                    ORG_MEMBER_NO                    1        -        21       "@@"
long     pNameAdrBufrowCount              PNAMEADRBUFROWCOUNT              1        -        -        -1061109568
char     link_mode                        LINK_MODE                        20       -        -        "@"
long     link_ban                         LINK_BAN                         20       -        -        -1061109568
string   link_subscriber                  LINK_SUBSCRIBER                  20       -        21       "@@"
string   link_row_id                      LINK_ROW_ID                      20       -        19       "@@"
long     link_seq_no                      LINK_SEQ_NO                      20       -        -        -1061109568
long     lnkReccustomer_id                LNKRECCUSTOMER_ID                20       -        -        -1061109568
long     ban                              BAN                              20       -        -        -1061109568
string   lnkRecsubscriber_no              LNKRECSUBSCRIBER_NO              20       -        21       "@@"
char     link_type                        LINK_TYPE                        20       -        -        "@"
string   lnkReceffective_date             LNKRECEFFECTIVE_DATE             20       -        9        "@@"
long     foreign_seq_no                   FOREIGN_SEQ_NO                   20       -        -        -1061109568
char     billing_ind                      BILLING_IND                      20       -        -        "@"
char     mailing_ind                      MAILING_IND                      20       -        -        "@"
char     user_ind                         USER_IND                         20       -        -        "@"
char     link_billing_ind                 LINK_BILLING_IND                 20       -        -        "@"
char     link_mailing_ind                 LINK_MAILING_IND                 20       -        -        "@"
char     link_user_ind                    LINK_USER_IND                    20       -        -        "@"
char     nm_mode                          NM_MODE                          20       -        -        "@"
char     nm_up_type                       NM_UP_TYPE                       20       -        -        "@"
string   nm_expire_date                   NM_EXPIRE_DATE                   20       -        9        "@@"
string   NameRecrowid                     NAMERECROWID                     20       -        19       "@@"
long     name_id                          NAME_ID                          20       -        -        -1061109568
string   NameRecsys_creation_date         NAMERECSYS_CREATION_DATE         20       -        15       "@@"
string   NameRecsys_update_date           NAMERECSYS_UPDATE_DATE           20       -        15       "@@"
long     NameRecoperator_id               NAMERECOPERATOR_ID               20       -        -        -1061109568
string   NameRecapplication_id            NAMERECAPPLICATION_ID            20       -        7        "@@"
string   NameRecdl_service_code           NAMERECDL_SERVICE_CODE           20       -        6        "@@"
short    NameRecdl_update_stamp           NAMERECDL_UPDATE_STAMP           20       -        -        -16192
string   control_name                     CONTROL_NAME                     20       -        41       "@@"
string   last_business_name               LAST_BUSINESS_NAME               20       -        61       "@@"
string   first_name                       FIRST_NAME                       20       -        33       "@@"
string   additional_title                 ADDITIONAL_TITLE                 20       -        61       "@@"
char     name_format                      NAME_FORMAT                      20       -        -        "@"
string   birth_date                       BIRTH_DATE                       20       -        9        "@@"
string   identify                         IDENTIFY                         20       -        21       "@@"
string   id_type                          ID_TYPE                          20       -        5        "@@"
string   comp_reg_id                      COMP_REG_ID                      20       -        21       "@@"
double   kob                              KOB                              20       -        -        -8577.505882352939800
string   middle_initial                   MIDDLE_INITIAL                   20       -        33       "@@"
string   telemarket_id                    TELEMARKET_ID                    20       -        11       "@@"
short    NameRecconv_run_no               NAMERECCONV_RUN_NO               20       -        -        -16192
string   name_title_salutation            NAME_TITLE_SALUTATION            20       -        21       "@@"
string   nationality_cd                   NATIONALITY_CD                   20       -        4        "@@"
char     gender                           GENDER                           20       -        -        "@"
string   marital_status                   MARITAL_STATUS                   20       -        5        "@@"
char     role_ind                         ROLE_IND                         20       -        -        "@"
char     adr_mode                         ADR_MODE                         20       -        -        "@"
char     adr_up_type                      ADR_UP_TYPE                      20       -        -        "@"
string   adr_expire_date                  ADR_EXPIRE_DATE                  20       -        9        "@@"
string   addressRecrowid                  ADDRESSRECROWID                  20       -        19       "@@"
long     address_id                       ADDRESS_ID                       20       -        -        -1061109568
string   addressRecsys_creation_date      ADDRESSRECSYS_CREATION_DATE      20       -        15       "@@"
string   addressRecsys_update_date        ADDRESSRECSYS_UPDATE_DATE        20       -        15       "@@"
long     addressRecoperator_id            ADDRESSRECOPERATOR_ID            20       -        -        -1061109568
string   addressRecapplication_id         ADDRESSRECAPPLICATION_ID         20       -        7        "@@"
string   addressRecdl_service_code        ADDRESSRECDL_SERVICE_CODE        20       -        6        "@@"
short    addressRecdl_update_stamp        ADDRESSRECDL_UPDATE_STAMP        20       -        -        -16192
char     adr_type                         ADR_TYPE                         20       -        -        "@"
char     adr_status                       ADR_STATUS                       20       -        -        "@"
string   adr_status_date                  ADR_STATUS_DATE                  20       -        9        "@@"
string   adr_secondary_ln                 ADR_SECONDARY_LN                 20       -        101      "@@"
string   adr_primary_ln                   ADR_PRIMARY_LN                   20       -        101      "@@"
string   adr_city                         ADR_CITY                         20       -        40       "@@"
string   adr_zip                          ADR_ZIP                          20       -        10       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     20       -        21       "@@"
string   adr_street_name                  ADR_STREET_NAME                  20       -        61       "@@"
string   adr_direction                    ADR_DIRECTION                    20       -        3        "@@"
string   adr_pob                          ADR_POB                          20       -        11       "@@"
string   adr_country                      ADR_COUNTRY                      20       -        4        "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 20       -        3        "@@"
string   adr_story                        ADR_STORY                        20       -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      20       -        5        "@@"
string   adr_email                        ADR_EMAIL                        20       -        151      "@@"
string   since_date                       SINCE_DATE                       20       -        9        "@@"
string   adr_district                     ADR_DISTRICT                     20       -        41       "@@"
char     co_ind                           CO_IND                           20       -        -        "@"
short    addressRecconv_run_no            ADDRESSRECCONV_RUN_NO            20       -        -        -16192
string   accommodation_type               ACCOMMODATION_TYPE               20       -        5        "@@"
string   county_code                      COUNTY_CODE                      20       -        3        "@@"
string   community_name                   COMMUNITY_NAME                   20       -        31       "@@"
string   adr_co_name                      ADR_CO_NAME                      20       -        61       "@@"
string   adr_house_name                   ADR_HOUSE_NAME                   20       -        61       "@@"
string   adr_p1                           ADR_P1                           20       -        61       "@@"
string   adr_p2                           ADR_P2                           20       -        61       "@@"
string   adr_p3                           ADR_P3                           20       -        61       "@@"
string   adr_p4                           ADR_P4                           20       -        61       "@@"
string   adr_p5                           ADR_P5                           20       -        61       "@@"
string   adr_p6                           ADR_P6                           20       -        61       "@@"
string   adr_p7                           ADR_P7                           20       -        61       "@@"
string   adr_p8                           ADR_P8                           20       -        61       "@@"
string   adr_p9                           ADR_P9                           20       -        61       "@@"
string   adr_p10                          ADR_P10                          20       -        61       "@@"
char     fullTable                        FULLTABLE                        1        -        -        "@"
string   paper_work_status                PAPER_WORK_STATUS                1        -        3        "@@"
char     paper_work_required              PAPER_WORK_REQUIRED              1        -        -        "@"
string   paper_work_date                  PAPER_WORK_DATE                  1        -        9        "@@"
string   paper_work_ref_no                PAPER_WORK_REF_NO                1        -        12       "@@"
string   paper_work_trns_no               PAPER_WORK_TRNS_NO               1        -        26       "@@"
char     delivery_type                    DELIVERY_TYPE                    1        -        -        "@"
long     pArInpban                        PARINPBAN                        1        -        -        -1061109568
long     partition_root_ban               PARTITION_ROOT_BAN               1        -        -        -1061109568
string   pArInpsubscriber_no              PARINPSUBSCRIBER_NO              1        -        21       "@@"
string   pArInpsub_market_code            PARINPSUB_MARKET_CODE            1        -        4        "@@"
string   requirement_date                 REQUIREMENT_DATE                 1        -        9        "@@"
double   activation_amount                ACTIVATION_AMOUNT                1        -        -        -8577.505882352939800
double   prepayment_amount                PREPAYMENT_AMOUNT                1        -        -        -8577.505882352939800
double   prep_actv_amt                    PREP_ACTV_AMT                    1        -        -        -8577.505882352939800
char     rc_only_ind                      RC_ONLY_IND                      1        -        -        "@"
string   pArInpdealer_code                PARINPDEALER_CODE                1        -        6        "@@"
char     actv_exmp_ind                    ACTV_EXMP_IND                    1        -        -        "@"
char     prep_exmp_ind                    PREP_EXMP_IND                    1        -        -        "@"
char     source_appl_code                 SOURCE_APPL_CODE                 1        -        -        "@"
string   feature_code                     FEATURE_CODE                     1        -        7        "@@"
string   pArInpsoc                        PARINPSOC                        1        -        10       "@@"
string   soc_date                         SOC_DATE                         1        -        9        "@@"
long     pFtrListrowcount                 PFTRLISTROWCOUNT                 1        -        -        -1061109568
string   FtrArrayfeature_code             FTRARRAYFEATURE_CODE             200      -        7        "@@"
string   feature_type                     FEATURE_TYPE                     200      -        4        "@@"
string   ftr_param_name                   FTR_PARAM_NAME                   200      -        31       "@@"
string   ftr_param_value                  FTR_PARAM_VALUE                  200      -        31       "@@"
END

VIEW vo_csEnvActCtn
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     pFtrListrowcount                 PFTRLISTROWCOUNT                 1        -        -        -1061109568
string   FtrArrayfeature_code             FTRARRAYFEATURE_CODE             200      -        7        "@@"
string   feature_type                     FEATURE_TYPE                     200      -        4        "@@"
string   ftr_param_name                   FTR_PARAM_NAME                   200      -        31       "@@"
string   ftr_param_value                  FTR_PARAM_VALUE                  200      -        31       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
long     code                             CODE                             100      -        -        -1061109568
char     faxInd                           FAXIND                           1        -        -        "@"
long     pMsisBufrowCount                 PMSISBUFROWCOUNT                 1        -        -        -1061109568
string   msisdn                           MSISDN                           100      -        21       "@@"
string   nl                               NL                               100      -        4        "@@"
long     gsmbufcode                       GSMBUFCODE                       100      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    100      -        21       "@@"
string   feature_code                     FEATURE_CODE                     100      -        7        "@@"
short    cycle_code                       CYCLE_CODE                       1        -        -        -16192
END


VIEW vi_csGtProvQue
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   subno                            SUBNO                            1        -        21       "@@"
string   trxtype                          TRXTYPE                          1        -        4        "@@"
END

VIEW vo_csGtProvQue
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     time_before                      TIME_BEFORE                      1        -        -        -1061109568
long     time_with                        TIME_WITH                        1        -        -        -1061109568
long     trx_before                       TRX_BEFORE                       1        -        -        -1061109568
END


VIEW vi_csEnvActCDA
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   creation_date                    CREATION_DATE                    1        -        9        "@@"
string   dealer_code                      DEALER_CODE                      1        -        6        "@@"
string   sales_rep_code                   SALES_REP_CODE                   1        -        6        "@@"
string   msisdn                           MSISDN                           1        -        21       "@@"
string   code_access_no                   CODE_ACCESS_NO                   1        -        21       "@@"
string   soc                              SOC                              1        -        10       "@@"
char     service_type                     SERVICE_TYPE                     1        -        -        "@"
string   promotionsoc                     PROMOTIONSOC                     1        -        10       "@@"
char     promotionservice_type            PROMOTIONSERVICE_TYPE            1        -        -        "@"
END

VIEW vo_csEnvActCDA
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
char     actv_status                      ACTV_STATUS                      1        -        -        "@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
long     code                             CODE                             100      -        -        -1061109568
END


VIEW vi_csGtAddIf
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
END

VIEW vo_csGtAddIf
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   field_name                       FIELD_NAME                       500      -        31       "@@"
string   field_value                      FIELD_VALUE                      500      -        256      "@@"
END


VIEW vi_csUpAddIf
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   field_name                       FIELD_NAME                       500      -        31       "@@"
string   field_value                      FIELD_VALUE                      500      -        256      "@@"
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939800
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939800
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_csUpAddIf
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


VIEW vi_csCallFrwd
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   tn                               TN                               1        -        21       "@@"
string   srv_trx_tp_cd                    SRV_TRX_TP_CD                    1        -        4        "@@"
string   trx_src                          TRX_SRC                          1        -        4        "@@"
string   imsi                             IMSI                             1        -        16       "@@"
string   hlr_id                           HLR_ID                           1        -        4        "@@"
string   feature_code                     FEATURE_CODE                     1        -        7        "@@"
string   features                         FEATURES                         1        -        2001     "@@"
string   product_type                     PRODUCT_TYPE                     1        -        4        "@@"
string   act_code                         ACT_CODE                         1        -        4        "@@"
string   act_reason                       ACT_REASON                       1        -        5        "@@"
char     susp_rc_rate_type                SUSP_RC_RATE_TYPE                1        -        -        "@"
string   memo_ctn                         MEMO_CTN                         1        -        21       "@@"
string   user_text                        USER_TEXT                        1        -        2001     "@@"
char     memo_source                      MEMO_SOURCE                      1        -        -        "@"
long     param_count                      PARAM_COUNT                      1        -        -        -1061109568
string   p1                               P1                               1        -        21       "@@"
string   p2                               P2                               1        -        21       "@@"
string   p3                               P3                               1        -        21       "@@"
string   p4                               P4                               1        -        21       "@@"
string   p5                               P5                               1        -        21       "@@"
string   p6                               P6                               1        -        21       "@@"
string   p7                               P7                               1        -        21       "@@"
string   p8                               P8                               1        -        21       "@@"
string   p9                               P9                               1        -        21       "@@"
string   p10                              P10                              1        -        21       "@@"
double   memo_amt                         MEMO_AMT                         1        -        -        -8577.505882352939800
string   rms_act_code                     RMS_ACT_CODE                     1        -        5        "@@"
double   charge_amt                       CHARGE_AMT                       1        -        -        -8577.505882352939800
char     charge_amt_ind                   CHARGE_AMT_IND                   1        -        -        "@"
string   waive_reason                     WAIVE_REASON                     1        -        7        "@@"
char     waive_ind                        WAIVE_IND                        1        -        -        "@"
END

VIEW vo_csCallFrwd
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
END


