VIEW vi_csGtBanOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     ban                              BAN                              1        -        -        -1061109568
string   effective_date                   EFFECTIVE_DATE                   1        -        15       "@@"
string   link_type_str                    LINK_TYPE_STR                    1        -        21       "@@"
string   msisdn                           MSISDN                           1        -        21       "@@"
string   pOleMsisdnInpReceffective_date   POLEMSISDNINPRECEFFECTIVE_DATE   1        -        15       "@@"
END

VIEW vo_csGtBanOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   rowid                            ROWID                            100      -        19       "@@"
long     ban                              BAN                              100      -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    100      -        21       "@@"
char     link_type                        LINK_TYPE                        100      -        -        "@"
string   birth_date                       BIRTH_DATE                       100      -        9        "@@"
string   nm_rowid                         NM_ROWID                         100      -        19       "@@"
string   first_name                       FIRST_NAME                       100      -        33       "@@"
string   last_business_name               LAST_BUSINESS_NAME               100      -        61       "@@"
string   additional_title                 ADDITIONAL_TITLE                 100      -        61       "@@"
string   ad_rowid                         AD_ROWID                         100      -        19       "@@"
string   adr_street_name                  ADR_STREET_NAME                  100      -        61       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     100      -        21       "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 100      -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      100      -        5        "@@"
string   adr_story                        ADR_STORY                        100      -        3        "@@"
string   adr_direction                    ADR_DIRECTION                    100      -        3        "@@"
string   adr_city                         ADR_CITY                         100      -        40       "@@"
string   adr_zip                          ADR_ZIP                          100      -        10       "@@"
string   adr_country                      ADR_COUNTRY                      100      -        4        "@@"
string   adr_pob                          ADR_POB                          100      -        11       "@@"
string   adr_email                        ADR_EMAIL                        100      -        151      "@@"
string   adr_district                     ADR_DISTRICT                     100      -        41       "@@"
char     co_ind                           CO_IND                           100      -        -        "@"
string   adr_co_name                      ADR_CO_NAME                      100      -        61       "@@"
char     account_type                     ACCOUNT_TYPE                     1        -        -        "@"
string   account_sub_type                 ACCOUNT_SUB_TYPE                 1        -        3        "@@"
string   customer_telno                   CUSTOMER_TELNO                   1        -        21       "@@"
string   customer_fax                     CUSTOMER_FAX                     1        -        21       "@@"
long     pOleBufrowCount                  POLEBUFROWCOUNT                  1        -        -        -1061109568
string   PhyDvcInforowid                  PHYDVCINFOROWID                  500      -        19       "@@"
long     PhyDvcInfoban                    PHYDVCINFOBAN                    500      -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     500      -        21       "@@"
string   imsi                             IMSI                             500      -        16       "@@"
string   sbs_rowid                        SBS_ROWID                        500      -        19       "@@"
string   PhyDvcInfosubscriber_no          PHYDVCINFOSUBSCRIBER_NO          500      -        21       "@@"
char     sub_status                       SUB_STATUS                       500      -        -        "@"
short    credit_watch_pin_cd              CREDIT_WATCH_PIN_CD              500      -        -        -16192
long     sbs_customer_id                  SBS_CUSTOMER_ID                  500      -        -        -1061109568
string   SitinvInforowid                  SITINVINFOROWID                  500      -        19       "@@"
string   serial_number                    SERIAL_NUMBER                    500      -        21       "@@"
string   sys_creation_date                SYS_CREATION_DATE                500      -        15       "@@"
string   sys_update_date                  SYS_UPDATE_DATE                  500      -        15       "@@"
long     SitinvInfooperator_id            SITINVINFOOPERATOR_ID            500      -        -        -1061109568
string   SitinvInfoapplication_id         SITINVINFOAPPLICATION_ID         500      -        7        "@@"
string   dl_service_code                  DL_SERVICE_CODE                  500      -        6        "@@"
short    dl_update_stamp                  DL_UPDATE_STAMP                  500      -        -        -16192
string   act_issue_date                   ACT_ISSUE_DATE                   500      -        15       "@@"
string   item_id                          ITEM_ID                          500      -        16       "@@"
string   pool                             POOL                             500      -        3        "@@"
string   location_id                      LOCATION_ID                      500      -        5        "@@"
string   document_loc_id                  DOCUMENT_LOC_ID                  500      -        5        "@@"
char     document_type                    DOCUMENT_TYPE                    500      -        -        "@"
long     document_oid                     DOCUMENT_OID                     500      -        -        -1061109568
string   activity_code                    ACTIVITY_CODE                    500      -        5        "@@"
string   activity_date                    ACTIVITY_DATE                    500      -        15       "@@"
char     operation_status                 OPERATION_STATUS                 500      -        -        "@"
char     item_ownership                   ITEM_OWNERSHIP                   500      -        -        "@"
string   item_ownership_dt                ITEM_OWNERSHIP_DT                500      -        15       "@@"
char     curr_possession                  CURR_POSSESSION                  500      -        -        "@"
string   curr_possession_dt               CURR_POSSESSION_DT               500      -        15       "@@"
char     missing_ind                      MISSING_IND                      500      -        -        "@"
char     in_repair_ind                    IN_REPAIR_IND                    500      -        -        "@"
char     in_transit_ind                   IN_TRANSIT_IND                   500      -        -        "@"
char     comited_to_pos_ind               COMITED_TO_POS_IND               500      -        -        "@"
string   comited_date                     COMITED_DATE                     500      -        15       "@@"
string   pos_document_locid               POS_DOCUMENT_LOCID               500      -        5        "@@"
char     pos_document_type                POS_DOCUMENT_TYPE                500      -        -        "@"
long     pos_document_oid                 POS_DOCUMENT_OID                 500      -        -        -1061109568
string   activity_reason                  ACTIVITY_REASON                  500      -        4        "@@"
string   last_counted_date                LAST_COUNTED_DATE                500      -        15       "@@"
char     upgrade_ind                      UPGRADE_IND                      500      -        -        "@"
string   expected_rtrn_date               EXPECTED_RTRN_DATE               500      -        15       "@@"
string   repair_location_id               REPAIR_LOCATION_ID               500      -        5        "@@"
double   initial_book_value               INITIAL_BOOK_VALUE               500      -        -        -8577.505882352939800
string   initial_dpr_date                 INITIAL_DPR_DATE                 500      -        9        "@@"
short    ini_no_months_to_dpr             INI_NO_MONTHS_TO_DPR             500      -        -        -16192
string   last_dpr_date                    LAST_DPR_DATE                    500      -        15       "@@"
double   current_book_value               CURRENT_BOOK_VALUE               500      -        -        -8577.505882352939800
short    cur_no_months_to_dpr             CUR_NO_MONTHS_TO_DPR             500      -        -        -16192
string   police_report_no                 POLICE_REPORT_NO                 500      -        16       "@@"
string   police_report_date               POLICE_REPORT_DATE               500      -        15       "@@"
string   police_station                   POLICE_STATION                   500      -        31       "@@"
string   msn                              MSN                              500      -        11       "@@"
long     puk                              PUK                              500      -        -        -1061109568
long     package_id                       PACKAGE_ID                       500      -        -        -1061109568
string   package_msisdn                   PACKAGE_MSISDN                   500      -        21       "@@"
long     puk2                             PUK2                             500      -        -        -1061109568
string   SitinvInfoimsi                   SITINVINFOIMSI                   500      -        16       "@@"
string   ki                               KI                               500      -        33       "@@"
string   first_used_date                  FIRST_USED_DATE                  500      -        15       "@@"
char     sim_status                       SIM_STATUS                       500      -        -        "@"
char     suspend_ind                      SUSPEND_IND                      500      -        -        "@"
string   suspend_date                     SUSPEND_DATE                     500      -        15       "@@"
short    initial_pin                      INITIAL_PIN                      500      -        -        -16192
char     sent_to_auc_ind                  SENT_TO_AUC_IND                  500      -        -        "@"
string   hlr_cd                           HLR_CD                           500      -        4        "@@"
short    initial_pin2                     INITIAL_PIN2                     500      -        -        -16192
string   k4id                             K4ID                             500      -        41       "@@"
string   SrvAgrInforowid                  SRVAGRINFOROWID                  500      -        19       "@@"
string   soc                              SOC                              500      -        10       "@@"
long     soc_seq_no                       SOC_SEQ_NO                       500      -        -        -1061109568
string   soc_effective_date               SOC_EFFECTIVE_DATE               500      -        9        "@@"
string   dealer_code                      DEALER_CODE                      500      -        6        "@@"
string   campaign                         CAMPAIGN                         500      -        10       "@@"
string   SubNmAddrrowid                   SUBNMADDRROWID                   500      -        19       "@@"
long     SubNmAddrban                     SUBNMADDRBAN                     500      -        -        -1061109568
string   SubNmAddrsubscriber_no           SUBNMADDRSUBSCRIBER_NO           500      -        21       "@@"
char     SubNmAddrlink_type               SUBNMADDRLINK_TYPE               500      -        -        "@"
string   SubNmAddrbirth_date              SUBNMADDRBIRTH_DATE              500      -        9        "@@"
string   SubNmAddrnm_rowid                SUBNMADDRNM_ROWID                500      -        19       "@@"
string   SubNmAddrfirst_name              SUBNMADDRFIRST_NAME              500      -        33       "@@"
string   SubNmAddrlast_business_name      SUBNMADDRLAST_BUSINESS_NAME      500      -        61       "@@"
string   SubNmAddradditional_title        SUBNMADDRADDITIONAL_TITLE        500      -        61       "@@"
string   SubNmAddrad_rowid                SUBNMADDRAD_ROWID                500      -        19       "@@"
string   SubNmAddradr_street_name         SUBNMADDRADR_STREET_NAME         500      -        61       "@@"
string   SubNmAddradr_house_no            SUBNMADDRADR_HOUSE_NO            500      -        21       "@@"
string   SubNmAddradr_house_letter        SUBNMADDRADR_HOUSE_LETTER        500      -        3        "@@"
string   SubNmAddradr_door_no             SUBNMADDRADR_DOOR_NO             500      -        5        "@@"
string   SubNmAddradr_story               SUBNMADDRADR_STORY               500      -        3        "@@"
string   SubNmAddradr_direction           SUBNMADDRADR_DIRECTION           500      -        3        "@@"
string   SubNmAddradr_city                SUBNMADDRADR_CITY                500      -        40       "@@"
string   SubNmAddradr_zip                 SUBNMADDRADR_ZIP                 500      -        10       "@@"
string   SubNmAddradr_country             SUBNMADDRADR_COUNTRY             500      -        4        "@@"
string   SubNmAddradr_pob                 SUBNMADDRADR_POB                 500      -        11       "@@"
string   SubNmAddradr_email               SUBNMADDRADR_EMAIL               500      -        151      "@@"
string   SubNmAddradr_district            SUBNMADDRADR_DISTRICT            500      -        41       "@@"
char     SubNmAddrco_ind                  SUBNMADDRCO_IND                  500      -        -        "@"
string   SubNmAddradr_co_name             SUBNMADDRADR_CO_NAME             500      -        61       "@@"
string   product_type                     PRODUCT_TYPE                     500      -        4        "@@"
string   vm_number                        VM_NUMBER                        500      -        21       "@@"
string   vm_fax                           VM_FAX                           500      -        21       "@@"
END


VIEW vi_csGtMsisdnOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   msisdn                           MSISDN                           1        -        21       "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        15       "@@"
END

VIEW vo_csGtMsisdnOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
char     link_type                        LINK_TYPE                        1        -        -        "@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   nm_rowid                         NM_ROWID                         1        -        19       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   last_business_name               LAST_BUSINESS_NAME               1        -        61       "@@"
string   additional_title                 ADDITIONAL_TITLE                 1        -        61       "@@"
string   ad_rowid                         AD_ROWID                         1        -        19       "@@"
string   adr_street_name                  ADR_STREET_NAME                  1        -        61       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     1        -        21       "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 1        -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      1        -        5        "@@"
string   adr_story                        ADR_STORY                        1        -        3        "@@"
string   adr_direction                    ADR_DIRECTION                    1        -        3        "@@"
string   adr_city                         ADR_CITY                         1        -        40       "@@"
string   adr_zip                          ADR_ZIP                          1        -        10       "@@"
string   adr_country                      ADR_COUNTRY                      1        -        4        "@@"
string   adr_pob                          ADR_POB                          1        -        11       "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   adr_district                     ADR_DISTRICT                     1        -        41       "@@"
char     co_ind                           CO_IND                           1        -        -        "@"
string   adr_co_name                      ADR_CO_NAME                      1        -        61       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   PhyDvcInfoBufrowid               PHYDVCINFOBUFROWID               500      -        19       "@@"
long     PhyDvcInfoBufban                 PHYDVCINFOBUFBAN                 500      -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     500      -        21       "@@"
string   imsi                             IMSI                             500      -        16       "@@"
string   sbs_rowid                        SBS_ROWID                        500      -        19       "@@"
string   PhyDvcInfoBufsubscriber_no       PHYDVCINFOBUFSUBSCRIBER_NO       500      -        21       "@@"
char     sub_status                       SUB_STATUS                       500      -        -        "@"
short    credit_watch_pin_cd              CREDIT_WATCH_PIN_CD              500      -        -        -16192
long     sbs_customer_id                  SBS_CUSTOMER_ID                  500      -        -        -1061109568
END


VIEW vi_csGtSimOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   sim                              SIM                              1        -        21       "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        15       "@@"
END

VIEW vo_csGtSimOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
char     link_type                        LINK_TYPE                        1        -        -        "@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   nm_rowid                         NM_ROWID                         1        -        19       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   last_business_name               LAST_BUSINESS_NAME               1        -        61       "@@"
string   additional_title                 ADDITIONAL_TITLE                 1        -        61       "@@"
string   ad_rowid                         AD_ROWID                         1        -        19       "@@"
string   adr_street_name                  ADR_STREET_NAME                  1        -        61       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     1        -        21       "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 1        -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      1        -        5        "@@"
string   adr_story                        ADR_STORY                        1        -        3        "@@"
string   adr_direction                    ADR_DIRECTION                    1        -        3        "@@"
string   adr_city                         ADR_CITY                         1        -        40       "@@"
string   adr_zip                          ADR_ZIP                          1        -        10       "@@"
string   adr_country                      ADR_COUNTRY                      1        -        4        "@@"
string   adr_pob                          ADR_POB                          1        -        11       "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   adr_district                     ADR_DISTRICT                     1        -        41       "@@"
char     co_ind                           CO_IND                           1        -        -        "@"
string   adr_co_name                      ADR_CO_NAME                      1        -        61       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   PhyDvcInfoBufrowid               PHYDVCINFOBUFROWID               500      -        19       "@@"
long     PhyDvcInfoBufban                 PHYDVCINFOBUFBAN                 500      -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     500      -        21       "@@"
string   imsi                             IMSI                             500      -        16       "@@"
string   sbs_rowid                        SBS_ROWID                        500      -        19       "@@"
string   PhyDvcInfoBufsubscriber_no       PHYDVCINFOBUFSUBSCRIBER_NO       500      -        21       "@@"
char     sub_status                       SUB_STATUS                       500      -        -        "@"
short    credit_watch_pin_cd              CREDIT_WATCH_PIN_CD              500      -        -        -16192
long     sbs_customer_id                  SBS_CUSTOMER_ID                  500      -        -        -1061109568
END


VIEW vi_csGtImsiOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   imsi                             IMSI                             1        -        16       "@@"
string   effective_date                   EFFECTIVE_DATE                   1        -        15       "@@"
END

VIEW vo_csGtImsiOle
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   rowid                            ROWID                            1        -        19       "@@"
long     ban                              BAN                              1        -        -        -1061109568
string   subscriber_no                    SUBSCRIBER_NO                    1        -        21       "@@"
char     link_type                        LINK_TYPE                        1        -        -        "@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   nm_rowid                         NM_ROWID                         1        -        19       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   last_business_name               LAST_BUSINESS_NAME               1        -        61       "@@"
string   additional_title                 ADDITIONAL_TITLE                 1        -        61       "@@"
string   ad_rowid                         AD_ROWID                         1        -        19       "@@"
string   adr_street_name                  ADR_STREET_NAME                  1        -        61       "@@"
string   adr_house_no                     ADR_HOUSE_NO                     1        -        21       "@@"
string   adr_house_letter                 ADR_HOUSE_LETTER                 1        -        3        "@@"
string   adr_door_no                      ADR_DOOR_NO                      1        -        5        "@@"
string   adr_story                        ADR_STORY                        1        -        3        "@@"
string   adr_direction                    ADR_DIRECTION                    1        -        3        "@@"
string   adr_city                         ADR_CITY                         1        -        40       "@@"
string   adr_zip                          ADR_ZIP                          1        -        10       "@@"
string   adr_country                      ADR_COUNTRY                      1        -        4        "@@"
string   adr_pob                          ADR_POB                          1        -        11       "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   adr_district                     ADR_DISTRICT                     1        -        41       "@@"
char     co_ind                           CO_IND                           1        -        -        "@"
string   adr_co_name                      ADR_CO_NAME                      1        -        61       "@@"
long     rowCount                         ROWCOUNT                         1        -        -        -1061109568
string   PhyDvcInfoBufrowid               PHYDVCINFOBUFROWID               500      -        19       "@@"
long     PhyDvcInfoBufban                 PHYDVCINFOBUFBAN                 500      -        -        -1061109568
string   equipment_no                     EQUIPMENT_NO                     500      -        21       "@@"
string   imsi                             IMSI                             500      -        16       "@@"
string   sbs_rowid                        SBS_ROWID                        500      -        19       "@@"
string   PhyDvcInfoBufsubscriber_no       PHYDVCINFOBUFSUBSCRIBER_NO       500      -        21       "@@"
char     sub_status                       SUB_STATUS                       500      -        -        "@"
short    credit_watch_pin_cd              CREDIT_WATCH_PIN_CD              500      -        -        -16192
long     sbs_customer_id                  SBS_CUSTOMER_ID                  500      -        -        -1061109568
END


VIEW vi_csEnvInBan
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
char     AccType                          ACCTYPE                          1        -        -        "@"
string   AccSubType                       ACCSUBTYPE                       1        -        3        "@@"
string   PymMethod                        PYMMETHOD                        1        -        3        "@@"
string   PymSubMtd                        PYMSUBMTD                        1        -        3        "@@"
string   BusinessCategory                 BUSINESSCATEGORY                 1        -        4        "@@"
string   BillLang                         BILLLANG                         1        -        3        "@@"
string   TelNo                            TELNO                            1        -        21       "@@"
string   CreationDate                     CREATIONDATE                     1        -        9        "@@"
string   ContLastName                     CONTLASTNAME                     1        -        61       "@@"
string   ContFirstName                    CONTFIRSTNAME                    1        -        33       "@@"
string   Locs                             LOCS                             1        -        4        "@@"
string   CompanyTaxId                     COMPANYTAXID                     1        -        21       "@@"
string   CompanyRegId                     COMPANYREGID                     1        -        21       "@@"
string   CustomerFax                      CUSTOMERFAX                      1        -        21       "@@"
string   WorkPhone                        WORKPHONE                        1        -        21       "@@"
char     MarketingInd                     MARKETINGIND                     1        -        -        "@"
string   BirthDate                        BIRTHDATE                        1        -        9        "@@"
string   LastName                         LASTNAME                         2        -        61       "@@"
string   FirstName                        FIRSTNAME                        2        -        33       "@@"
string   Zip                              ZIP                              2        -        10       "@@"
string   HouseNo                          HOUSENO                          2        -        21       "@@"
string   StreetName                       STREETNAME                       2        -        61       "@@"
string   City                             CITY                             2        -        40       "@@"
string   Country                          COUNTRY                          2        -        4        "@@"
string   HouseLetter                      HOUSELETTER                      2        -        3        "@@"
string   Story                            STORY                            2        -        3        "@@"
string   Email                            EMAIL                            2        -        151      "@@"
char     coInd                            COIND                            2        -        -        "@"
string   coName                           CONAME                           2        -        61       "@@"
END

VIEW vo_csEnvInBan
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     directive                        DIRECTIVE                        1        -        -        -1061109568
long     first_directive                  FIRST_DIRECTIVE                  1        -        -        -1061109568
long     second_directive                 SECOND_DIRECTIVE                 1        -        -        -1061109568
long     operator_id                      OPERATOR_ID                      1        -        -        -1061109568
string   application_id                   APPLICATION_ID                   1        -        7        "@@"
char     transaction_mode                 TRANSACTION_MODE                 1        -        -        "@"
string   run_date                         RUN_DATE                         1        -        9        "@@"
string   market_code                      MARKET_CODE                      1        -        4        "@@"
char     svc_status                       SVC_STATUS                       1        -        -        "@"
string   last_update_date                 LAST_UPDATE_DATE                 1        -        15       "@@"
short    last_update_stamp                LAST_UPDATE_STAMP                1        -        -        -16192
string   env_code                         ENV_CODE                         1        -        11       "@@"
long     session_id                       SESSION_ID                       1        -        -        -1061109568
long     online_trx_no                    ONLINE_TRX_NO                    1        -        -        -1061109568
long     group_trx_id                     GROUP_TRX_ID                     1        -        -        -1061109568
string   insert_status                    INSERT_STATUS                    1        -        5        "@@"
long     ban                              BAN                              1        -        -        -1061109568
END


