VIEW vi_ifCrCvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
string   cas_activity                     CAS_ACTIVITY                     1        -        4        "@@"
string   request_status                   REQUEST_STATUS                   1        -        3        "@@"
string   status_date                      STATUS_DATE                      1        -        15       "@@"
string   cas_record_number                CAS_RECORD_NUMBER                1        -        13       "@@"
long     cas_dtl_seq                      CAS_DTL_SEQ                      1        -        -        -1061109568
char     account_type                     ACCOUNT_TYPE                     1        -        -        "@"
string   account_sub_type                 ACCOUNT_SUB_TYPE                 1        -        3        "@@"
long     ban                              BAN                              1        -        -        -1061109568
string   application_datetime             APPLICATION_DATETIME             1        -        15       "@@"
string   birth_date                       BIRTH_DATE                       1        -        9        "@@"
string   nationality                      NATIONALITY                      1        -        4        "@@"
char     gender                           GENDER                           1        -        -        "@"
string   marital_status                   MARITAL_STATUS                   1        -        5        "@@"
string   accommodation_type               ACCOMMODATION_TYPE               1        -        5        "@@"
string   employment_type                  EMPLOYMENT_TYPE                  1        -        5        "@@"
string   employment_date                  EMPLOYMENT_DATE                  1        -        9        "@@"
string   bank_start_date                  BANK_START_DATE                  1        -        9        "@@"
string   payment_method                   PAYMENT_METHOD                   1        -        3        "@@"
string   preferred_lang                   PREFERRED_LANG                   1        -        3        "@@"
string   dealer_id                        DEALER_ID                        1        -        6        "@@"
string   home_telno                       HOME_TELNO                       1        -        21       "@@"
string   work_telno                       WORK_TELNO                       1        -        21       "@@"
string   mobile_telno                     MOBILE_TELNO                     1        -        21       "@@"
string   business_est_date                BUSINESS_EST_DATE                1        -        9        "@@"
string   name_title                       NAME_TITLE                       1        -        21       "@@"
string   last_name                        LAST_NAME                        1        -        61       "@@"
string   first_name                       FIRST_NAME                       1        -        33       "@@"
string   middle_name                      MIDDLE_NAME                      1        -        61       "@@"
string   id_type                          ID_TYPE                          1        -        5        "@@"
string   id_number                        ID_NUMBER                        1        -        21       "@@"
string   curr_adr_start_date              CURR_ADR_START_DATE              1        -        9        "@@"
string   curr_adr_zip_code                CURR_ADR_ZIP_CODE                1        -        10       "@@"
string   curr_adr_street_name             CURR_ADR_STREET_NAME             1        -        61       "@@"
string   curr_adr_street_no               CURR_ADR_STREET_NO               1        -        21       "@@"
string   curr_adr_house_letter            CURR_ADR_HOUSE_LETTER            1        -        3        "@@"
string   curr_adr_storey                  CURR_ADR_STOREY                  1        -        3        "@@"
string   curr_adr_door_no                 CURR_ADR_DOOR_NO                 1        -        5        "@@"
string   curr_adr_city                    CURR_ADR_CITY                    1        -        40       "@@"
string   curr_adr_country_code            CURR_ADR_COUNTRY_CODE            1        -        4        "@@"
string   prev_adr_start_date              PREV_ADR_START_DATE              1        -        9        "@@"
string   prev_adr_zip_code                PREV_ADR_ZIP_CODE                1        -        10       "@@"
string   prev_adr_street_name             PREV_ADR_STREET_NAME             1        -        61       "@@"
string   prev_adr_street_no               PREV_ADR_STREET_NO               1        -        21       "@@"
string   prev_adr_house_letter            PREV_ADR_HOUSE_LETTER            1        -        3        "@@"
string   prev_adr_storey                  PREV_ADR_STOREY                  1        -        3        "@@"
string   prev_adr_door_no                 PREV_ADR_DOOR_NO                 1        -        5        "@@"
string   prev_adr_city                    PREV_ADR_CITY                    1        -        40       "@@"
string   prev_adr_country_code            PREV_ADR_COUNTRY_CODE            1        -        4        "@@"
string   bill_adr_start_date              BILL_ADR_START_DATE              1        -        9        "@@"
string   bill_adr_zip_code                BILL_ADR_ZIP_CODE                1        -        10       "@@"
string   bill_adr_street_name             BILL_ADR_STREET_NAME             1        -        61       "@@"
string   bill_adr_street_no               BILL_ADR_STREET_NO               1        -        21       "@@"
string   bill_adr_house_letter            BILL_ADR_HOUSE_LETTER            1        -        3        "@@"
string   bill_adr_storey                  BILL_ADR_STOREY                  1        -        3        "@@"
string   bill_adr_door_no                 BILL_ADR_DOOR_NO                 1        -        5        "@@"
string   bill_adr_city                    BILL_ADR_CITY                    1        -        40       "@@"
string   bill_adr_country_code            BILL_ADR_COUNTRY_CODE            1        -        4        "@@"
string   adr_email                        ADR_EMAIL                        1        -        151      "@@"
string   bank_code                        BANK_CODE                        1        -        11       "@@"
string   bank_desc                        BANK_DESC                        1        -        36       "@@"
string   direction                        DIRECTION                        1        -        3        "@@"
string   district                         DISTRICT                         1        -        41       "@@"
short    num_of_employees                 NUM_OF_EMPLOYEES                 1        -        -        -16192
char     allow_advertising_ind            ALLOW_ADVERTISING_IND            1        -        -        "@"
string   cs_def_product_type              CS_DEF_PRODUCT_TYPE              1        -        4        "@@"
double   curr_debt                        CURR_DEBT                        1        -        -        -8577.505882352939800
double   prev_debt                        PREV_DEBT                        1        -        -        -8577.505882352939800
string   start_service_date               START_SERVICE_DATE               1        -        9        "@@"
string   company_type_code                COMPANY_TYPE_CODE                1        -        4        "@@"
string   business_type_code               BUSINESS_TYPE_CODE               1        -        4        "@@"
string   dealer_code                      DEALER_CODE                      1        -        6        "@@"
string   marketing_code                   MARKETING_CODE                   1        -        4        "@@"
char     vip_ind                          VIP_IND                          1        -        -        "@"
short    num_of_mub_subs                  NUM_OF_MUB_SUBS                  1        -        -        -16192
short    num_of_ll_subs                   NUM_OF_LL_SUBS                   1        -        -        -16192
short    num_of_isp_subs                  NUM_OF_ISP_SUBS                  1        -        -        -16192
char     credit_class                     CREDIT_CLASS                     1        -        -        "@"
char     ur_reason_cd                     UR_REASON_CD                     1        -        -        "@"
string   mob_final_decision               MOB_FINAL_DECISION               1        -        4        "@@"
string   uw_mob_data                      UW_MOB_DATA                      1        -        27       "@@"
string   ll_final_decision                LL_FINAL_DECISION                1        -        4        "@@"
string   uw_ll_data                       UW_LL_DATA                       1        -        27       "@@"
string   isp_final_decision               ISP_FINAL_DECISION               1        -        4        "@@"
string   uw_isp_data                      UW_ISP_DATA                      1        -        22       "@@"
string   product_taken                    PRODUCT_TAKEN                    1        -        4        "@@"
double   credit_limit                     CREDIT_LIMIT                     1        -        -        -8577.505882352939800
double   deposit_amount                   DEPOSIT_AMOUNT                   1        -        -        -8577.505882352939800
char     dd_allow_pym_mtd                 DD_ALLOW_PYM_MTD                 1        -        -        "@"
END

VIEW vo_ifCrCvReq
$
#type    cname                            fname                            count    flag     size     null    
long     generation                       GENERATION                       1        -        -        -
long     ban                              BAN                              1        -        -        -1061109568
string   application_datetime             APPLICATION_DATETIME             1        -        15       "@@"
long     cas_order_no                     CAS_ORDER_NO                     1        -        -        -1061109568
short    cvs_status                       CVS_STATUS                       1        -        -        -16192
string   cvs_failcode                     CVS_FAILCODE                     1        -        257      "@@"
string   request_status                   REQUEST_STATUS                   1        -        3        "@@"
string   cas_return_text                  CAS_RETURN_TEXT                  1        -        71       "@@"
string   soc_list                         SOC_LIST                         1        -        51       "@@"
long     row_count                        ROW_COUNT                        1        -        -        -1061109568
string   addr_line                        ADDR_LINE                        25       -        81       "@@"
long     cvPersonListrow_count            CVPERSONLISTROW_COUNT            1        -        -        -1061109568
string   person_name                      PERSON_NAME                      10       -        121      "@@"
string   street_name                      STREET_NAME                      10       -        51       "@@"
string   country_cd                       COUNTRY_CD                       10       -        4        "@@"
string   post_no                          POST_NO                          10       -        6        "@@"
string   comm_reg_no                      COMM_REG_NO                      10       -        4        "@@"
string   cvr_no                           CVR_NO                           10       -        9        "@@"
string   date_of_birth                    DATE_OF_BIRTH                    10       -        9        "@@"
END


