
-- Set in_use flag to make sure it's generated by any full generation later, 
-- and set a comment.
update tux_services_new a
set in_use = 'Y', comments = 'Added as part of Fokus 15.2.5.8. Checks that a special telephone number (eg VoIP, ie that ends up in the service_feature.ftr_special_telno column) is not already used - it uses an index on that column if I understand it correctly.'
-- select * from tux_services_new a
where 1 = 1
  --and in_use = 'Y'
  --and svc_name like 'cs%'
  -- and svc_name in ('csGtDumSIM', 'csValFandFLst', 'csGtSplTlFtr')
  and svc_name = 'csGtSplTlFtr'
--order by a.svc_name
;

