#!/usr/bin/env bash
svn status | grep java | grep '4_service_classes' | awk '{printf "cp -p %s\t/Users/hakgu/Projects/gerrit/NinjaCore/ninja-core-root/core/src/no/netcom/ninja/core/system/tuxedo/service/\n", $2}'
svn status | grep java | grep '5_dataset_classes' | awk '{printf "cp -p %s\t/Users/hakgu/Projects/gerrit/NinjaCore/ninja-core-root/core/src/no/netcom/ninja/core/system/tuxedo/service/parameters/\n", $2}'
